eclipse-tractusx/bpdm

.github/workflows/deploy-maven.yaml
bpdm-common/pom.xml

* deploy to GitHub packages maven registry of ng owner
* only deploy on push to main branch

cicd(Workflows): add deployment of bpdm-common library to pipeline

---

charts/pool/Chart.yaml
charts/pool/values-beta.yaml

* increase patch version of both pool chart as it influences the digest of the packaged chart

cicd(Charts): add beta environment values to pool chart

---

CHANGELOG.md
bpdm-common/pom.xml
bpdm-gate/pom.xml
bpdm-pool/pom.xml
pom.xml

* documented changes between 3.0.0 and 3.0.1 in changelog

feat(Version): increase application version to 3.0.1

---

charts/gate/Chart.yaml
charts/gate/values.yaml
charts/pool/Chart.yaml
charts/pool/values-beta.yaml
charts/pool/values.yaml

* increase referenced app version
* increase also default tag to v3.0.1

cicd(Charts): increase app version to 3.0.1

---

.github/workflows/build-docker.yaml

Fix typo that broke docker build workflow

cicd(Workflows): fix typo

---

INSTALL.md
README.md

* refactor formatting of links
* refactor formatting of enumerations in auth sections

refactor(README): fix formatting

---

bpdm-gate/Dockerfile
bpdm-pool/Dockerfile

fix(dockerfile): add apk upgrade to bpdm pool and gate images

---

DEPENDENCIES
bpdm-pool/pom.xml

* increase opensearch dependency version

fix(Opensearch): fix vulnerability of current opensearch dependency

---

bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/component/saas/config/SaasAdapterConfigProperties.kt
bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/component/saas/controller/SaasController.kt
bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/component/saas/dto/ImportIdFilterRequest.kt
bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/component/saas/dto/ImportIdMappingResponse.kt
bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/component/saas/service/ImportStarterService.kt
bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/component/saas/service/PartnerImportPageService.kt
bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/exception/BpdmRequestSizeException.kt
bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/repository/ImportEntryRepository.kt
bpdm-pool/src/main/resources/application-saas.properties
bpdm-pool/src/main/resources/db/migration/V3_1_0_0__add_import_entries_constraints.sql

* Endpoint for paginating the mappings between import identifier and BPN
* Endpoint for filtering BPN by import identifier

feat(SaaS-Import): add endpoints to query import identifiers mappings

---

bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/config/BpdmSecurityConfigurerAdapterImpl.kt
bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/config/BpdmSecurityConfigurerAdapterImpl.kt

Added path /error to BpdmSecurityConfigurerAdapter and BpdmSecurityConfigurerAdapter to avoid getting a wrong error message.

Fix(gate/pool): Fixed error on gate and pool connection

---

.github/workflows/deploy-maven.yaml

Fix workflow call to deploy maven library modules

cicd(worfklows): fix maven command to deploy library modules

---

DEPENDENCIES
pom.xml

Increase Spring Boot version to mitigate vulnerabilities.
Adapted dependencies and also created license issues with Eclipse.

feat(pom): increase to spring boot starter version 3.0.5

---

bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/GateAddressApi.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/controller/AddressController.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/AddressService.kt
bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/AddressControllerInputIT.kt

Get address partners by filter with externalids

Add new Endpoint For Address

---

bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/GateSiteApi.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/controller/SiteController.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/SiteService.kt
bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/SiteControllerInputIT.kt

Add new endpoint for getting site bpn with externalIds filter

Site new endpoint

---

docs/postman/BPDM Gate.postman_collection.json
docs/postman/BPDM Pool.postman_collection.json
docs/postman/Local.postman_environment.json

- add collection for BPDM Pool requests
- add collection for BPDM Gate requests
- add environment file for local environment adjusted to default properties

docs(postman): add postman collections for BPDM requests

---

SECURITY.md

Update the SECURITY.md file to the newest version according to release guidelines.
Relevant issue: #107

Update SECURITY.md to newest version

---

README.md

Replace all mentions of "Catena-X" in the README with "Eclipse Tractus-X".
Relevant Issue: #109

Replace mentions of "Catena-X"

---

pom.xml

Fixes some critical vulnerabilties introduced by transivitve dependencies included in the spring boot start parent dependency

fix(pom): increase used spring boot version to 3.0.6

---

charts/gate/CHANGELOG.md
charts/gate/Chart.yaml
charts/gate/templates/ingress.yaml
charts/pool/CHANGELOG.md
charts/pool/Chart.yaml
charts/pool/templates/ingress.yaml

move license headers under the if-clause to ensure compatibility with helm-v2 (See issue #113)

fix(helm): add license headers to ingress template files

---

CHANGELOG.md

Update changelog to be according commits until version 3.2.2

fix(Gate-Pool): Update CHANGELOG.md to current versions 3.2.2

---

.github/workflows/build-docker-all.yaml
bpdm-bridge-dummy/Dockerfile

Creating workflow for dummy bridge image

feat(Gate-Pool): Creating workflow for dummy bridge image

---

bpdm-bridge-dummy/src/main/kotlin/com/catenax/bpdm/bridge/dummy/config/BpdmSecurityConfigurerAdapterImpl.kt
bpdm-bridge-dummy/src/main/kotlin/com/catenax/bpdm/bridge/dummy/config/ClientsConfig.kt
bpdm-bridge-dummy/src/main/kotlin/com/catenax/bpdm/bridge/dummy/config/GateConfigProperties.kt
bpdm-bridge-dummy/src/main/kotlin/com/catenax/bpdm/bridge/dummy/config/PoolConfigProperties.kt
bpdm-bridge-dummy/src/main/resources/application-auth.properties

Don't merge before https://github.com/eclipse-tractusx/bpdm/pull/166 !

Brige Dummy: Add authorization config and properties

---

bpdm-bridge-dummy/src/main/kotlin/com/catenax/bpdm/bridge/dummy/config/BridgeConfigProperties.kt
bpdm-bridge-dummy/src/main/kotlin/com/catenax/bpdm/bridge/dummy/service/GateQueryService.kt
bpdm-bridge-dummy/src/main/resources/application.properties

Don't merge before https://github.com/eclipse-tractusx/bpdm/pull/186

Bridge: use pagination for querying

---

INSTALL.md
bpdm-gate/src/main/resources/application.properties

Changed information from Install.md and application properties, removing not needed SaaS instructions, Update Swagger-UI url, and wrote run instructions saying that the project must be run from root pom file

fix(gate/pool): Updated Install and read me instructions

---

bpdm-bridge-dummy/src/main/kotlin/com/catenax/bpdm/bridge/dummy/dto/GateLegalEntityInfo.kt
bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/LegalEntityGateInputRequest.kt
bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/LegalEntityGateInputResponse.kt
bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/LegalEntityGateOutput.kt
bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/LegalEntityGateOutputRequest.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/LegalEntityService.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/ResponseMappings.kt
bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/util/RequestValues.kt
bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/util/ResponseValues.kt

Refactor: Replace Array with List in NameParts field

fix(Gate-Bridge): Replace Array with Collection Type #263

---

mvnw.cmd

added Maven wrapper file to work with windows and fix #188

feat: added maven wrapper for windows.

---

bpdm-bridge-dummy/pom.xml
bpdm-bridge-dummy/src/main/kotlin/com/catenax/bpdm/bridge/dummy/config/BpdmSecurityConfigurerAdapterImpl.kt
bpdm-bridge-dummy/src/main/kotlin/com/catenax/bpdm/bridge/dummy/config/BridgeAuthProperties.kt
bpdm-bridge-dummy/src/main/kotlin/com/catenax/bpdm/bridge/dummy/controller/BridgeController.kt
bpdm-bridge-dummy/src/main/resources/application-auth.properties
bpdm-bridge-dummy/src/main/resources/application.properties
bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/config/SecurityConfig.kt

title: '(feat): Configured Spring Security to use roles from JWT for API
This Pull Request introduces significant enhancements to the security of our API endpoints by implementing Role-Based Access Control (RBAC) using JWT claims and Spring Security.
Fixes [# (issuenumber from PR destination repo)](https://github.com/eclipse-tractusx/bpdm/issues/266)
- Check out our guide on …

Feat(Bridge): Configured Spring Security to use roles from JWT for API

---

charts/bpdm/Chart.yaml
charts/bpdm/charts/bpdm-bridge-dummy/Chart.yaml
charts/bpdm/charts/bpdm-bridge-dummy/values.yaml
charts/bpdm/charts/bpdm-gate/Chart.yaml
charts/bpdm/charts/bpdm-gate/values.yaml
charts/bpdm/charts/bpdm-pool/Chart.yaml
charts/bpdm/charts/bpdm-pool/values.yaml

This pull request increases the supported BPDM app version to 4.0.0-alpha.7.
- [x ] DEPENDENCIES are up to date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [ x] Copyright and license header are present on all affected files

Helm Charts: Increase App Version to 4.0.0-alpha.7

---

charts/bpdm/Chart.yaml
charts/bpdm/README.md
charts/bpdm/charts/bpdm-bridge-dummy/Chart.yaml
charts/bpdm/charts/bpdm-bridge-dummy/README.md
charts/bpdm/charts/bpdm-bridge-dummy/values.yaml
charts/bpdm/charts/bpdm-gate/Chart.yaml
charts/bpdm/charts/bpdm-gate/README.md
charts/bpdm/charts/bpdm-gate/values.yaml
charts/bpdm/charts/bpdm-pool/Chart.yaml
charts/bpdm/charts/bpdm-pool/README.md
charts/bpdm/charts/bpdm-pool/values.yaml
charts/bpdm/values.yaml

BPDM Helm Chart: Fixed README.md files for all BPDM services and added README.md file for umbrella chart.
Also, streamlined resource's limits for each service to run on cluster.

fix(helm): change readme files and streamline resources

---

bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/dto/response/AreaDistrictAlternativVerboseDto.kt
bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/dto/response/AreaDistrictVerboseDto.kt
bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/dto/response/RegionDto.kt
bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/util/CommonValues.kt
bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/PoolMetadataApi.kt
bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/controller/MetadataController.kt
bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/MetadataService.kt
bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/ResponseMappings.kt
bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/util/CommonValues.kt

Created endpoint to persist and get the Region metadata
Fixes #267

feat(gate): created endpoint for Regions Metadata

---

INSTALL.md
README.md

In this pull request, Adapting changes as per the tractusx release guidelines.

fix(docs): updates file as per tractusx release guidelines

---

bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/LogisticAddress.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/AddressPersistenceService.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/LegalEntityPersistenceService.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/ResponseMappings.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/SitePersistenceService.kt
bpdm-gate/src/main/resources/db/migration/V4_0_0_8__create table address_identifiers.sql
bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/AddressControllerInputIT.kt
bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/AddressControllerOutputIT.kt
bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/util/ResponseValues.kt

fixed the persistence of the identifiers collection on LogisticAddress

fix(gate): fixed the persistence of AddressIdentifier

---

.github/workflows/execute-tests.yaml
bpdm-bridge-dummy/build-docker.bat
bpdm-bridge-dummy/build-docker.sh
bpdm-bridge-dummy/src/test/kotlin/com/catenax/bpdm/bridge/dummy/util/BpdmGateContextInitializer.kt
bpdm-bridge-dummy/src/test/kotlin/com/catenax/bpdm/bridge/dummy/util/BpdmPoolContextInitializer.kt
bpdm-bridge-dummy/src/test/kotlin/com/catenax/bpdm/bridge/dummy/util/OpenSearchContextInitializer.kt
bpdm-gate/Dockerfile
bpdm-pool/Dockerfile
docker-compose.build.yml

Create gate and pool docker images with tags locally. Reference image tags in ContextInitializer
Fixes #

bridge dummy: build images locally

---

docs/edc/EDC_BPDM_Setup.postman_collection.json
docs/edc/EDC_BPDM_Usage.postman_collection.json
docs/edc/README.md

This pull request updates the documentation for the EDC in version 0.5. As before the documentation contains instructions and Postman collections for setting up and using the EDC in the context of BPDM. 
In this version the Postman collection describes the assets for all endpoints on the BPDM Gate and BPDM Pool that a sharing member may find useful.
Fixes #370

doc: Update EDC Documentation for Version 0.5

---

bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/repository/RegionRepository.kt
bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/BusinessPartnerBuildService.kt

---
Name: Added persistence of region on pool
---
In this PR, regions can now be persisted on the pool DB
- Check out our guide on [how to contribute](https://eclipse-tractusx.github.io/docs/oss/how-to-contribute)
- Check out our [Release Guidelines](https://eclipse-tractusx.github.io/docs/release)
- Check out the [Eclipse Foundation contribution …

Feat(pool) - Added persistence of regions on pool 

---

charts/bpdm/Chart.yaml
charts/bpdm/charts/bpdm-bridge-dummy/Chart.yaml
charts/bpdm/charts/bpdm-gate/Chart.yaml
charts/bpdm/charts/bpdm-pool/Chart.yaml

This pull requests updates the BPDM chart and its subcharts to appversion 4.0.0-alpha.10
This version is intended to be the final release candidate for version 4.0.0

Feat: BPDM Chart Appversion 4.0.0-alpha.10

---

CHANGELOG.md
bpdm-bridge-dummy/pom.xml
bpdm-common/pom.xml
bpdm-gate-api/pom.xml
bpdm-gate/pom.xml
bpdm-pool-api/pom.xml
bpdm-pool/pom.xml
docs/api/bridge-dummy.json
docs/api/bridge-dummy.yaml
docs/api/gate.json
docs/api/gate.yaml
docs/api/pool.json
docs/api/pool.yaml
pom.xml

This pull request increases the BPDM application version to the 4.0.0 release version.
In addition to the actual version increase I also adapted the changelog and API-docs accordingly now referencing the release version.

Feat: BPDM 4.0.0

---

bpdm-bridge-dummy/pom.xml
bpdm-common/pom.xml
bpdm-gate-api/pom.xml
bpdm-gate/pom.xml
bpdm-pool-api/pom.xml
bpdm-pool/pom.xml
pom.xml

This pull request increases the Maven version of the BPDM app to 4.0.1-SNAPSHOT.
Contributions will now be prepared towards a future 4.0.1 release.

Feat: BPDM 4.0.1 SNAPSHOT version

---

charts/bpdm/.helmignore
charts/bpdm/Chart.yaml
charts/bpdm/LICENSE
charts/bpdm/charts/bpdm-bridge-dummy/CHANGELOG.md
charts/bpdm/charts/bpdm-bridge-dummy/Chart.yaml
charts/bpdm/charts/bpdm-gate/CHANGELOG.md
charts/bpdm/charts/bpdm-gate/Chart.yaml
charts/bpdm/charts/bpdm-pool/CHANGELOG.md
charts/bpdm/charts/bpdm-pool/Chart.yaml

This pull request increases the appversion of the BPDM chart and subcharts to 4.0.0 and by this releases the charts from alpha status. For the release I also adjusted the Changelog, updated the maintainers list and added some missing files to the Umbrella chart folder.

Feat: BPDM Charts appversion 4.0.0

---

CHANGELOG.md
bpdm-bridge-dummy/pom.xml
bpdm-common/pom.xml
bpdm-gate-api/pom.xml
bpdm-gate/pom.xml
bpdm-pool-api/pom.xml
bpdm-pool/pom.xml
pom.xml

##Description
This pull request raises the BPDM maven version from SNAPSHOT to version 4.0.1
CHANGELOG is updated accordingly

Feat: BPDM 4.0.1

---

charts/bpdm/CHANGELOG.md
charts/bpdm/Chart.yaml
charts/bpdm/charts/bpdm-bridge-dummy/CHANGELOG.md
charts/bpdm/charts/bpdm-bridge-dummy/Chart.yaml
charts/bpdm/charts/bpdm-gate/CHANGELOG.md
charts/bpdm/charts/bpdm-gate/Chart.yaml
charts/bpdm/charts/bpdm-pool/CHANGELOG.md
charts/bpdm/charts/bpdm-pool/Chart.yaml

This pull request increases the BPDM Chart version to 3.0.4 and increases the supported app version to 4.0.1.
Also updates the CHANGELOG files of the charts accordingly.

Feat: BPDM Chart 3.0.4

---

docs/decision-records/003-orchestrator_serviceApi_vs_messagebus_approach.md

Proposal for an ADR on how to implement the orchestrator component for bpdm solution.
Co-Authored-By: nicoprow <nico.koprowski@mercedes-benz.com>

docs(adr-3): adr proposal regarding orchestrator

---

docs/postman/automated-test/BPDM Automated Test.postman_collection.json

This pull request contains postman collection for automated tests in BPDM. where user can select environment as per the need and perform actions like creating metadata, query metadata, creating business partner referencing metadata, query business partner, syncing new business partners to pool, query business partner in pool, updating business partner, syncing again, query business partner update in one click. 
Create local or any specific environment variables then import BPDM Automated Test.postman_collection.json into postman.
After importing, simply run collection by selecting particular intended environment. Result will show passed and failed test cases in postman.

feat(docs): postman collection for automated api tests

---

bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/model/StageType.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/controller/ChangelogController.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/ChangelogEntry.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/LegalEntity.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/LogisticAddress.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/Site.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/repository/ChangelogRepository.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/repository/GateAddressRepository.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/repository/LegalEntityRepository.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/repository/SiteRepository.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/AddressPersistenceService.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/AddressService.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/ChangelogService.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/LegalEntityPersistenceService.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/LegalEntityService.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/ResponseMappings.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/SitePersistenceService.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/SiteService.kt
bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/AddressControllerOutputIT.kt
bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/LegalEntityControllerOutputIT.kt
bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/SiteControllerOutputIT.kt

For better readability change the enum class OutputInputEnum (with options Input, Output) to StageType. Also adjust the fields and parameters to stage where appriopriate.
Solves #444

refactor(model): Rename OutputInputEnum to StageType

---

bpdm-bridge-dummy/pom.xml
bpdm-common/pom.xml
bpdm-gate-api/pom.xml
bpdm-gate/pom.xml
bpdm-pool-api/pom.xml
bpdm-pool/pom.xml
pom.xml

This pull request increases the maven BPDM version to snapshot version 4.0.2-SNAPSHOT

Feat: BPDM 4.0.2-SNAPSHOT

---

.github/workflows/build-docker-all.yaml

Add workflow to build images for cleaning service

feat(Cleaning): Add workflow for cleaning service

---

CHANGELOG.md
bpdm-bridge-dummy/pom.xml
bpdm-cleaning-service-dummy/pom.xml
bpdm-common/pom.xml
bpdm-gate-api/pom.xml
bpdm-gate/pom.xml
bpdm-pool-api/pom.xml
bpdm-pool/pom.xml
pom.xml

Due to the introduction of the generic business partner endpoints in the Gate this pull request increases the snapshot version to 4.1.0. Our next release target is therefore minor version 4.1.0
I also updated the changelog file to reflect the changes so far

Feat: BPDM 4.1.0 SNAPSHOT

---

charts/bpdm/CHANGELOG.md
charts/bpdm/Chart.yaml
charts/bpdm/charts/bpdm-bridge-dummy/CHANGELOG.md
charts/bpdm/charts/bpdm-bridge-dummy/Chart.yaml
charts/bpdm/charts/bpdm-gate/CHANGELOG.md
charts/bpdm/charts/bpdm-gate/Chart.yaml
charts/bpdm/charts/bpdm-pool/CHANGELOG.md
charts/bpdm/charts/bpdm-pool/Chart.yaml

This pull request raises the appversion of the BPDM charts to 4.1.0-alpha.0
I edited the changelog entries accordingly.

Feat: BPDM Charts appversion 4.1.0-alpha.0

---

README.md
bpdm-orchestrator/DOCKER_NOTICE.md
bpdm-orchestrator/Dockerfile
bpdm-orchestrator/pom.xml
bpdm-orchestrator/src/main/kotlin/org/eclipse/tractusx/bpdm/orchestrator/Application.kt
bpdm-orchestrator/src/main/resources/application.properties
bpdm-orchestrator/src/test/kotlin/org/eclipse/tractusx/bpdm/orchestrator/ApplicationTests.kt
pom.xml

Create maven module for the orchestrator
At the moment no persistence to a database is configured.
#422

Feat: Module Orchestrator

---

docs/postman/automated-test/EDC-BPDM Automated Test.postman_collection.json

This pull request contains postman collection for automated tests in EDC. where user can change environment details as per the need and perform actions like Query the catalog, Initiate Negotiation and get authentication code to hit public api. All the steps can be performed using postman run for created collection.
Create INT or any specific environment variables then import EDC-BPDM Automated Test.postman_collection.json into postman.After importing, simply run collection and result will show passed and failed test cases in postman.

Docs: Postman collection of automated test for EDC

---

.github/workflows/deploy-maven.yaml
bpdm-orchestrator-api/pom.xml
bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/client/OrchestrationApiClient.kt
bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/client/OrchestrationApiClientImpl.kt
pom.xml

create of orchestrator api base structure
solves issue #424

feat(orchestrator-api):create of orchestrator api base structure

---

bpdm-bridge-dummy/src/main/kotlin/com/catenax/bpdm/bridge/dummy/dto/DtoConversionHelper.kt
bpdm-bridge-dummy/src/main/kotlin/com/catenax/bpdm/bridge/dummy/service/PoolUpdateService.kt
bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/AlternativePostalAddressGateDto.kt
bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/BusinessPartnerPostalAddressDto.kt
bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/LogisticAddressGateDto.kt
bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/request/BusinessPartnerInputRequest.kt
bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/response/BusinessPartnerInputDto.kt
bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/response/BusinessPartnerOutputDto.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/AlternativePostalAddress.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/PhysicalPostalAddress.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/generic/PostalAddress.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/BusinessPartnerMappings.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/ResponseMappings.kt
bpdm-gate/src/main/resources/db/migration/V4_0_0_15__make_postal_adress_fields_nullable.sql
bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/entity/generic/BusinessPartnerIT.kt

Make fields in Business Partner Input optional, only External-ID should be required.
Solves #476

Feat: Make fields in Business Partner Input optional

---

docs/arc42/diagrams/gate/address/get-addresses-by-external-id.md
docs/arc42/diagrams/gate/address/get-addresses-by-many-external-id.md
docs/arc42/diagrams/gate/address/get-addresses-input.md
docs/arc42/diagrams/gate/address/get-addresses-output.md
docs/arc42/diagrams/gate/address/upsert-addresses-input.md
docs/arc42/diagrams/gate/address/upsert-addresses-output.md
docs/arc42/diagrams/gate/changelog/changelog-input-search.md
docs/arc42/diagrams/gate/changelog/changelog-output-search.md
docs/arc42/diagrams/gate/legal-entity/get-legal-entities-search-input.md
docs/arc42/diagrams/gate/legal-entity/get-legal-entities-search-output.md
docs/arc42/diagrams/gate/legal-entity/get-legal-entity-by-many-external-id.md
docs/arc42/diagrams/gate/legal-entity/get-legal-entity-external-id.md
docs/arc42/diagrams/gate/legal-entity/upsert-legal-entity-input.md
docs/arc42/diagrams/gate/legal-entity/upsert-legal-entity-output.md
docs/arc42/diagrams/gate/site/get-sites-by-many-external-id.md
docs/arc42/diagrams/gate/site/get-sites-external-id.md
docs/arc42/diagrams/gate/site/get-sites-search-input.md
docs/arc42/diagrams/gate/site/get-sites-search-output.md
docs/arc42/diagrams/gate/site/upsert-site-input.md
docs/arc42/diagrams/gate/site/upsert-site-output.md

Create mermaid sequence diagrams showing the different services/components of the BPDM Gate and how they interact each other on these this case:
Upsert legal entity input/output
Get legal entities by external IDs
Related to #486

Feat(Gate) - Gate Internal Runtime View

---

docs/postman/BPDM Gate.postman_collection.json

Gate postman collections updated for business partners endpoints
solves  #471

Doc: Gate postman collection for generic endpoint

---

.github/workflows/trivy.yml

Add Model Cleaning Service to trivy scan
https://github.com/eclipse-tractusx/bpdm/issues/421

CICD: Add Cleaning Service Dummy to trivy.yml

---

bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/dto/BusinessPartnerType.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/ChangelogEntry.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/BusinessPartnerService.kt
bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/SharingStateControllerIT.kt

Added business partner type 'Generic' to Changelog and Sharing State
Solves #519

Feat: Add business partner type 'Generic' to Gate

---

bpdm-cleaning-service-dummy/src/main/kotlin/org/eclipse/tractusx/bpdm/cleaning/service/CleaningServiceDummy.kt

Add logic for when schedule runs to trigger also clean flow 
With this we validate also when a bpn is updated from the pool 
https://github.com/eclipse-tractusx/bpdm/issues/452 

Feat(Cleaning): Add logic for bpn cleaning upon pool update

---

docs/edc/EDC_BPDM_Setup.postman_collection.json
docs/edc/EDC_BPDM_Usage.postman_collection.json
docs/postman/automated-test/EDC-BPDM Automated Test.postman_collection.json

Added the generic endpoints to the existing EDC Postman collections analogous to the other endpoints.
Solves issue #509 

Docs: add generic endpoints to the EDC postman collections

---

bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/config/OpenApiConfig.kt

Add new flow for auth with token on swagger
Fix for issue: https://github.com/eclipse-tractusx/bpdm/issues/543

feat(Common): Add bearer token to swagger auth flow

---

docs/api/bridge-dummy.yaml
docs/api/gate.yaml
docs/api/orchestrator.yaml

This pull request updates the BPDM Gate und Bridge Dummy openAPI specs for version 4.1.0

Docs/api/gate bridge 4.1.0

---

CHANGELOG.md
bpdm-bridge-dummy/pom.xml
bpdm-cleaning-service-dummy/pom.xml
bpdm-common/pom.xml
bpdm-gate-api/pom.xml
bpdm-gate/pom.xml
bpdm-orchestrator-api/pom.xml
bpdm-orchestrator/pom.xml
bpdm-pool-api/pom.xml
bpdm-pool/pom.xml
pom.xml

This pull request increases the version of the BPDM applications to 4.1.0.
Appropriate entries for the changelog have been added.

Feat(App): Increase BPDM to version 4.1.0

---

charts/bpdm/CHANGELOG.md
charts/bpdm/Chart.yaml
charts/bpdm/charts/bpdm-bridge-dummy/CHANGELOG.md
charts/bpdm/charts/bpdm-bridge-dummy/Chart.yaml
charts/bpdm/charts/bpdm-cleaning-service-dummy/CHANGELOG.md
charts/bpdm/charts/bpdm-cleaning-service-dummy/Chart.yaml
charts/bpdm/charts/bpdm-gate/CHANGELOG.md
charts/bpdm/charts/bpdm-gate/Chart.yaml
charts/bpdm/charts/bpdm-orchestrator/CHANGELOG.md
charts/bpdm/charts/bpdm-orchestrator/Chart.yaml
charts/bpdm/charts/bpdm-pool/CHANGELOG.md
charts/bpdm/charts/bpdm-pool/Chart.yaml

This pull requests updates the Charts from alpha status to point to the release appversion 4.1.0

feat(Charts): update to app version 4.1.0

---

bpdm-bridge-dummy/pom.xml
bpdm-cleaning-service-dummy/pom.xml
bpdm-common/pom.xml
bpdm-gate-api/pom.xml
bpdm-gate/pom.xml
bpdm-orchestrator-api/pom.xml
bpdm-orchestrator/pom.xml
bpdm-pool-api/pom.xml
bpdm-pool/pom.xml
pom.xml

This pull request advances the main branch to SNAPSHOT version 5.0.0 of the BPDM application. By this we are indicating to advance to a next breaking change version.

feat(Pom): increase to SNAPSHOT version 5.0.0

---

bpdm-bridge-dummy/src/main/kotlin/com/catenax/bpdm/bridge/dummy/service/GateQueryService.kt
bpdm-bridge-dummy/src/main/kotlin/com/catenax/bpdm/bridge/dummy/service/GateUpdateService.kt
bpdm-bridge-dummy/src/main/kotlin/com/catenax/bpdm/bridge/dummy/service/PoolUpdateService.kt
bpdm-bridge-dummy/src/main/kotlin/com/catenax/bpdm/bridge/dummy/service/SyncService.kt
bpdm-orchestrator/src/main/kotlin/org/eclipse/tractusx/bpdm/orchestrator/service/GoldenRecordTaskService.kt
bpdm-orchestrator/src/main/kotlin/org/eclipse/tractusx/bpdm/orchestrator/service/GoldenRecordTaskStateMachine.kt
bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/BpnIssuingService.kt
bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/BusinessPartnerSearchService.kt
bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/GateDocumentationService.kt
bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/MetadataService.kt
bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/PartnerChangelogService.kt

refactored injected services, changed fields to private
solves #564

feat(): refactored injected services, changed fields to private

---

bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/service/BaseSyncRecordService.kt
bpdm-gate/pom.xml
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/config/ClientsConfig.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/SyncRecord.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/SyncType.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/repository/SyncRecordRepository.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/repository/generic/BusinessPartnerRepository.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/BusinessPartnerMappings.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/BusinessPartnerService.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/SyncRecordService.kt
bpdm-gate/src/main/resources/application.yml
bpdm-gate/src/main/resources/db/migration/V4_1_0_3__create_table_sync_record.sql
bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/BusinessPartnerControllerIT.kt
bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/util/BusinessPartnerGenericValues.kt

Request Cleaning for BPN Update
solves #431

feat(gate): Request Cleaning for BPN Update

---

bpdm-cleaning-service-dummy/src/main/kotlin/org/eclipse/tractusx/bpdm/cleaning/service/CleaningServiceDummy.kt
bpdm-cleaning-service-dummy/src/test/kotlin/org/eclipse/tractusx/bpdm/cleaning/service/CleaningServiceDummyTest.kt
bpdm-cleaning-service-dummy/src/test/kotlin/org/eclipse/tractusx/bpdm/cleaning/testdata/CommonValues.kt
bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/dto/IBaseBusinessPartnerDto.kt
bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/BusinessPartnerIdentifierDto.kt
bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/IBaseBusinessPartnerGateDto.kt
bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/request/BusinessPartnerInputRequest.kt
bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/response/BusinessPartnerDto.kt
bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/response/BusinessPartnerOutputDto.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/BusinessPartnerMappings.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/OrchestratorMappings.kt
bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/BusinessPartnerControllerIT.kt
bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/util/BusinessPartnerGenericValues.kt
bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/util/BusinessPartnerNonVerboseValues.kt
bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/util/BusinessPartnerVerboseValues.kt
bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/model/BusinessPartnerGenericDto.kt
bpdm-orchestrator/src/test/kotlin/org/eclipse/tractusx/bpdm/orchestrator/controller/GoldenRecordTaskControllerIT.kt
bpdm-orchestrator/src/test/kotlin/org/eclipse/tractusx/bpdm/orchestrator/testdata/BusinessPartnerTestValues.kt
bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/TaskStepBuildService.kt
bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/service/TaskStepFetchAndReserveServiceTest.kt

This pull request adjusts the OpenAPI descriptions of the new L/S/A separared business partner model to the current API standard for version 5.0.0.

Doc: adjust openApi documentation for new generic business partner model to standard

---

bpdm-bridge-dummy/src/main/kotlin/com/catenax/bpdm/bridge/dummy/dto/DtoConversionHelper.kt
bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/dto/IBaseStreetDto.kt
bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/dto/IStreetDetailedDto.kt
bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/model/StreetDto.kt
bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/entity/PhysicalPostalAddress.kt
bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/entity/Street.kt
bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/BusinessPartnerBuildService.kt
bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/ResponseMappings.kt
bpdm-pool/src/main/resources/db/migration/V5_0_0_3__add_additional_street_fields.sql
bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/util/BusinessPartnerVerboseValues.kt

Added Street Name Additional Fields information
Solves #673

feat(pool): Added Street Name Additional Fields information

---

bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/StatsApi.kt
bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/response/StatsStagesResponse.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/repository/generic/BusinessPartnerRepository.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/StatsService.kt

This pull request adds an endpoint to count business partners by stage (output and input).

feat(Gate): add stats endpoint for counting business partners per stage

---

bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/dto/BusinessPartnerRole.kt

This pull request adds  "ONE_TIME_SUPPLIER" and "ONE_TIME_CUSTOMER" as new possible roles for a generic business partner. The new roles can be set by the sharing member upon sharing business partner data.

feat(Generic): add additional possible roles to generic business partner

---

docs/api/gate.json
docs/api/gate.yaml
docs/api/pool.json
docs/api/pool.yaml

This pull request updates the OpenAPI documentation for the BPDM Pool and Gate APIs to version 5.0.0

docs(Api): add updated API documentation for BPDM version 5.0.0

---

bpdm-bridge-dummy/pom.xml
bpdm-gate/pom.xml
bpdm-orchestrator/pom.xml
bpdm-pool/pom.xml

This pull request adds automatically project descritions like name, version and summary to the OpenaAPI docs of Pool, Gate, Orchestrator and Bridge.

Docs: Open API Project Description

---

charts/bpdm/Chart.yaml
charts/bpdm/charts/bpdm-bridge-dummy/Chart.yaml
charts/bpdm/charts/bpdm-cleaning-service-dummy/Chart.yaml
charts/bpdm/charts/bpdm-gate/Chart.yaml
charts/bpdm/charts/bpdm-orchestrator/Chart.yaml
charts/bpdm/charts/bpdm-pool/Chart.yaml

This pull request increases the appversion to 5.0.0-alpha.6

feat(Charts): increase appversion to 5.0.0-alpha.6

---

docs/postman/BPDM Tests.postman_collection.json

This pull request introduces a Postman collection as a documentation for using the BPDM services for version 5.0.0 from perspective of operator, sharing members, VAS and cleaning providers.

Docs: Add Postman use case documentation for BPDM 5.0.0

---

CHANGELOG.md
bpdm-bridge-dummy/pom.xml
bpdm-cleaning-service-dummy/pom.xml
bpdm-common/pom.xml
bpdm-gate-api/pom.xml
bpdm-gate/pom.xml
bpdm-orchestrator-api/pom.xml
bpdm-orchestrator/pom.xml
bpdm-pool-api/pom.xml
bpdm-pool/pom.xml
pom.xml

This pull request increases the BPDM application to release version 5.0.0

feat(app): inrease BPDM to version 5.0.0

---

bpdm-bridge-dummy/pom.xml
bpdm-cleaning-service-dummy/pom.xml
bpdm-common/pom.xml
bpdm-gate-api/pom.xml
bpdm-gate/pom.xml
bpdm-orchestrator-api/pom.xml
bpdm-orchestrator/pom.xml
bpdm-pool-api/pom.xml
bpdm-pool/pom.xml
pom.xml

This pull request increases the BPDM version to 5.0.1-SNAPSHOT

feat(app): inrease the BPDM version to 5.0.1-SNAPSHOT

---

docs/Security_Assessment.md

Creation of the security assessment file including Mermaid diagram for the BPDM App.

Docs(Security): Create Security Md File

---

charts/bpdm/charts/bpdm-gate/CHANGELOG.md

- typo in heading
fixes https://github.com/eclipse-tractusx/bpdm/issues/762

fix: typo update CHANGELOG.md

---

bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/LegalEntityControllerInputIT.kt
bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/LegalEntityControllerOutputIT.kt
bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/SiteControllerInputIT.kt
bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/SiteControllerOutputIT.kt

This PR contains some changes to some Unit tests, regarding the use of the Recursive Comparison function 
Solves #677

Feat(bpdm) - Usage of recursive comparison on Unit Tests

---

bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/LegalEntityControllerInputIT.kt
bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/LegalEntityControllerOutputIT.kt
bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/SiteControllerInputIT.kt
bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/SiteControllerOutputIT.kt

This pull request fixes some Gate tests using outdated helper functions.

fix(Gate Test): using correct utility helper classes

---

bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/config/SecurityConfig.kt

Fix path request for BPDM Gate Endpoints

fix(Gate): Fix url path for Gate

---

bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/config/CustomJwtAuthenticationConverter.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/ChangelogEntryDb.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/SharingStateDb.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/generic/BusinessPartnerDb.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/repository/ChangelogRepository.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/repository/SharingStateRepository.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/repository/generic/BusinessPartnerRepository.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/AddressPersistenceService.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/BusinessPartnerService.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/ChangelogService.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/GoldenRecordTaskService.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/LegalEntityPersistenceService.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/OrchestratorMappings.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/SharingStateService.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/SitePersistenceService.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/util/Extensions.kt
bpdm-gate/src/main/resources/application.yml
bpdm-gate/src/main/resources/db/migration/V6_0_0_0__add_owner_bpnl_column.sql

Add new logic for controllers ( Sharing , Business Partner and Changelog) to get results based on the owners BPNL 
Extract BPNL from the token when its available 
Modify unit test to cover new functionalities 
Fixes: https://github.com/eclipse-tractusx/bpdm/issues/780

feat(Gate): Change logic for Search and Input Requests

---

bpdm-common-test/src/main/kotlin/org/eclipse/tractusx/bpdm/test/testdata/pool/BusinessPartnerHierachies.kt
bpdm-common-test/src/main/kotlin/org/eclipse/tractusx/bpdm/test/testdata/pool/BusinessPartnerRequestFactory.kt
bpdm-common-test/src/main/kotlin/org/eclipse/tractusx/bpdm/test/testdata/pool/ExpectedBusinessPartnerResultFactory.kt
bpdm-common-test/src/main/kotlin/org/eclipse/tractusx/bpdm/test/testdata/pool/TestDataHelper.kt
bpdm-common-test/src/main/kotlin/org/eclipse/tractusx/bpdm/test/util/CustomComparators.kt
bpdm-common-test/src/main/kotlin/org/eclipse/tractusx/bpdm/test/util/PoolAssertHelper.kt
bpdm-common-test/src/main/kotlin/org/eclipse/tractusx/bpdm/test/util/PoolDataHelpers.kt
bpdm-common-test/src/main/kotlin/org/eclipse/tractusx/bpdm/test/util/Timeframe.kt
bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/client/MembersApiClient.kt
bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/client/PoolClientImpl.kt
bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/config/AssertConfig.kt
bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/config/TestdataConfig.kt
bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/controller/MembersControllerIT.kt

This pull request  adds tests for pool member filter endpoints
- added  logic for generating business partner test data
- added logic for creating expected results from generated test data
- added reusable assertion logic for business partners
Contributes to #793 

 test(pool): add tests for pool member filter endpoints

---

bpdm-cleaning-service-dummy/src/test/kotlin/org/eclipse/tractusx/bpdm/cleaning/service/CleaningServiceApiCallsTest.kt
bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/ApiCommons.kt
bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/GateBusinessPartnerApi.kt
bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/GateChangelogApi.kt
bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/GateSharingStateApi.kt
bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/StatsApi.kt
bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/client/BusinessPartnerApiClient.kt
bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/client/ChangelogApiClient.kt
bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/client/SharingStateApiClient.kt
bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/util/EndpointValues.kt
bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/util/MockAndAssertUtils.kt
bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/GoldenRecordTaskApi.kt
bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/client/GoldenRecordTaskApiClient.kt
bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/ApiCommons.kt
bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/PoolAddressApi.kt
bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/PoolBpnApi.kt
bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/PoolChangelogApi.kt
bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/PoolLegalEntityApi.kt
bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/PoolMembersApi.kt
bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/PoolMetadataApi.kt
bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/PoolSiteApi.kt
bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/client/LegalEntityApiClient.kt
bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/client/MetadataApiClient.kt
bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/client/SiteApiClient.kt

This pull request adds the API version to the endpoint paths. In this way we can support several versions in the same API at the same time.

feat(api): add version prefix to API endpoints

---

bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/request/ChangelogSearchRequest.kt
bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/response/ChangelogGateDto.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/controller/ChangelogController.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/ChangelogEntryDb.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/repository/ChangelogRepository.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/BusinessPartnerService.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/ChangelogService.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/ResponseMappings.kt
bpdm-gate/src/main/resources/db/migration/V6_0_0_3__drop_changelog_bp_type.sql
bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/ChangeLogControllerIT.kt

This pull request removes the business partner type from the changelog entries. Since the Gate now only deals with generic business partners this additional type is not needed.

Feat: prune changelog

---

DEPENDENCIES
pom.xml

This pull request increases the used spring boot version to 3.2.4. By this we remove some vulnerabilities.

feat(app): increase to Spring Boot version 3.2.4

---

.github/dependabot.yml

this pull request adds dependabot configuration to the repository as is suggested by TRG 2.06

cidc(dependabot): add dependabot configuration to repository

---

.github/workflows/codeql.yml
.github/workflows/deploy-maven.yaml
.github/workflows/execute-tests.yaml
.github/workflows/sonar-scan.yaml
docker/cleaning-service-dummy/Dockerfile
docker/gate/Dockerfile
docker/orchestrator/Dockerfile
docker/pool/Dockerfile
pom.xml

This pull request increases the JAVA version from 17 to 21. 
Adapted Docker images and workflows accordingly.
Satisifies TRG 4.02

feat(app): increase java version to 21

---

bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/client/GateClient.kt
bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/client/GateClientImpl.kt
bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/client/StatsApiClient.kt

This pull request adds the stats endpoints to the BPDM Gate client

feat(Gate): add stats endpoints to BPDM Gate client

---

bpdm-orchestrator/src/main/kotlin/org/eclipse/tractusx/bpdm/orchestrator/config/PermissionConfigProperties.kt
bpdm-orchestrator/src/main/kotlin/org/eclipse/tractusx/bpdm/orchestrator/controller/GoldenRecordTaskController.kt
bpdm-orchestrator/src/main/resources/application-auth.yml

This pull request changes the permissions in the BPDM Orchestrator in a major way

feat(Orchestrator): change structure and naming for permissions

---

bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/GoldenRecordTaskService.kt

This pull request makes the Gate return more feedback in case errors happen during writing back results from the golden record process.

feat(Gate): when resolving golden record tasks now more error feedback

---

charts/bpdm/CHANGELOG.md
charts/bpdm/Chart.yaml
charts/bpdm/charts/bpdm-cleaning-service-dummy/Chart.yaml
charts/bpdm/charts/bpdm-gate/Chart.yaml
charts/bpdm/charts/bpdm-orchestrator/Chart.yaml
charts/bpdm/charts/bpdm-pool/Chart.yaml
charts/bpdm/templates/keycloakRealmSecret.yaml
charts/bpdm/values.yaml

This pull request increases the app-version of the BPDM Charts to 6.0.0-alpha.3

feat(Charts): increase app version to 6.0.0-alpha.3

---

bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/BusinessPartnerService.kt

fix(gate): duplication of business partner output in rare circumstances

---

docs/postman/EDC BPDM Consumer.postman_collection.json

docs(EDC): replace EDC consumer postman collection with newest version

---

bpdm-cleaning-service-dummy/src/main/kotlin/org/eclipse/tractusx/bpdm/cleaning/service/CleaningServiceDummy.kt
bpdm-cleaning-service-dummy/src/test/kotlin/org/eclipse/tractusx/bpdm/cleaning/service/CleaningServiceApiCallsTest.kt
bpdm-common-test/src/main/kotlin/org/eclipse/tractusx/bpdm/test/testdata/orchestrator/BusinessPartnerHelpers.kt

fix(Dummy): not setting isCxMemberData to true for owned records

---

docs/arc42/arc42-bpdm.md

This pull request updates the Arc42 with the newest changes for the 24.5 release. 
- Removed sections about the LSA endpoints in the BPDM Gate
- Removed mentions of the Bridge Application

docs(arc42): Update Arc42 for 24.5 Release

---

pom.xml

Fixes security vulnerabilities for issue #913 

chore(pom): update nimbus-jose-jwt dependency to fix #913

---

CHANGELOG.md

docs: updated changelog for version 6.0.0

---

DEPENDENCIES

docs(Licenses): update DEPENDENCIES with the newest license information

---

charts/bpdm/CHANGELOG.md
charts/bpdm/Chart.yaml
charts/bpdm/charts/bpdm-cleaning-service-dummy/CHANGELOG.md
charts/bpdm/charts/bpdm-cleaning-service-dummy/Chart.yaml
charts/bpdm/charts/bpdm-gate/CHANGELOG.md
charts/bpdm/charts/bpdm-gate/Chart.yaml
charts/bpdm/charts/bpdm-orchestrator/CHANGELOG.md
charts/bpdm/charts/bpdm-orchestrator/Chart.yaml
charts/bpdm/charts/bpdm-pool/CHANGELOG.md
charts/bpdm/charts/bpdm-pool/Chart.yaml

docs: update BPDM Helm charts changelogs

---

charts/bpdm/CHANGELOG.md
charts/bpdm/Chart.yaml
charts/bpdm/charts/bpdm-cleaning-service-dummy/CHANGELOG.md
charts/bpdm/charts/bpdm-cleaning-service-dummy/Chart.yaml
charts/bpdm/charts/bpdm-cleaning-service-dummy/values.yaml
charts/bpdm/charts/bpdm-gate/CHANGELOG.md
charts/bpdm/charts/bpdm-gate/Chart.yaml
charts/bpdm/charts/bpdm-gate/values.yaml
charts/bpdm/charts/bpdm-orchestrator/CHANGELOG.md
charts/bpdm/charts/bpdm-orchestrator/Chart.yaml
charts/bpdm/charts/bpdm-orchestrator/values.yaml
charts/bpdm/charts/bpdm-pool/CHANGELOG.md
charts/bpdm/charts/bpdm-pool/Chart.yaml
charts/bpdm/charts/bpdm-pool/values.yaml

Change default pull policy from 'Always' to 'IfNotPresent'
Contributes to #795

fix(charts): change default pull policy from 'Always' to 'IfNotPresent'

---

bpdm-cleaning-service-dummy/pom.xml
bpdm-common-test/pom.xml
bpdm-common/pom.xml
bpdm-gate-api/pom.xml
bpdm-gate/pom.xml
bpdm-orchestrator-api/pom.xml
bpdm-orchestrator/pom.xml
bpdm-pool-api/pom.xml
bpdm-pool/pom.xml
pom.xml

version: increase BPDM version 6.0.1-SNAPSHOT

---

docs/arc42/arc42-bpdm.md

Add companies SAP and Bosch to the copyright text in the arc42.

docs(arc42): update copyright

---

bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/TaskStepBuildService.kt

This pull request fixes the Pool's behaviour of validating business partner fields that are actually not used for updating data. This lead to a too strict behaviour and now let's sharing members leave out unnecessary information in the business partner data.

fix(pool): validating business partner data unnecessarily

---

CHANGELOG.md
bpdm-cleaning-service-dummy/pom.xml
bpdm-common-test/pom.xml
bpdm-common/pom.xml
bpdm-gate-api/pom.xml
bpdm-gate/pom.xml
bpdm-orchestrator-api/pom.xml
bpdm-orchestrator/pom.xml
bpdm-pool-api/pom.xml
bpdm-pool/pom.xml
pom.xml

version: increase BPDM to version 6.0.1

---

charts/bpdm/CHANGELOG.md
charts/bpdm/Chart.yaml
charts/bpdm/README.md
charts/bpdm/charts/bpdm-cleaning-service-dummy/CHANGELOG.md
charts/bpdm/charts/bpdm-cleaning-service-dummy/Chart.yaml
charts/bpdm/charts/bpdm-cleaning-service-dummy/README.md
charts/bpdm/charts/bpdm-gate/CHANGELOG.md
charts/bpdm/charts/bpdm-gate/Chart.yaml
charts/bpdm/charts/bpdm-gate/README.md
charts/bpdm/charts/bpdm-orchestrator/CHANGELOG.md
charts/bpdm/charts/bpdm-orchestrator/Chart.yaml
charts/bpdm/charts/bpdm-orchestrator/README.md
charts/bpdm/charts/bpdm-pool/CHANGELOG.md
charts/bpdm/charts/bpdm-pool/Chart.yaml
charts/bpdm/charts/bpdm-pool/README.md

version(charts): increase Charts version to 5.0.1

---

.github/workflows/app-test-trivy-all.yaml
.github/workflows/app-test-trivy.yaml

This pull request adds a trivy check on new code contributions.

CICD: Add Trivy Check for Pull Requests

---

docs/api/README.md

This pull request adds various examples showcasing the behaviour of the dummy golden record process and illustrating the idea of the golden record process as a whole.

docs: examples for dummy golden record process

---

.github/workflows/check-versions.yaml

cicd: Check whether the chart's appVersion and maven version align

---

.github/workflows/deploy-docker.yaml

ci(workflows): fix tags for deploy-docker workflow

---

.github/workflows/chart-test-lint.yaml

ci(Linting): Check version increment only on Release

---

docs/api/README.md

docs(Api): add mapping diagrams from Gate model to Orchestrator model

---

bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/model/BusinessPartner.kt
docs/api/orchestrator.json
docs/api/orchestrator.yaml

This pull request adds more descriptions for the Orchestrator API's business partner model.

docs(Orchestrator-API): add more descriptions to Orchestrator API model

---

CHANGELOG.md

This pull request adds missing issue links to the changelog entries for the newest releases as is best practice stated in [TRG 1.03](https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-3)

docs(CHANGELOG): add issues links to all changelog entries

---

docs/architecture/11_Risks_And_Technical_Debts.md

This pull request adds a documentation of the technical debts regarding the Central-IDP integration.
- Add explanation of the debt
- Add configuration for integration with the Central-IDP and mitigating the debt

docs(architecture): add technical Central-IDP debts 

---

INSTALL.md
docs/architecture/08_Crosscutting_Concepts.md
docs/architecture/11_Risks_And_Technical_Debts.md

This pull request adds installation instructions for setting up the BPDM in conjunction with the Portal.
- add installation instructions
- add technical debts and mismatches regarding Portal and BPDM
Relating issues: 
- eclipse-tractusx/portal-backend#819 
- eclipse-tractusx/portal-iam#154
- #994

docs(Portal): add installation instructions for Portal integration

---

bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/TaskStepFetchAndReserveService.kt

This pull request fixes a bug in which the Pool sends too long error messages to the Orchestrator when resolving golden record tasks. I also made the communication between Pool and Orchestrator a little more robust to mitigate future dangling reservations.
- cut off too long error messages
- also make the communication more robust for future problems. On an exception the Pool now tries to resolve the tasks with a generic error
In order to check that the behaviour is now resolved you can send business partner data with an unknown metadata technical key to the golden record process, that is close to 250 characters (the Orchestrator's character limit). You should now see the error that the tehcnical key does not exist. Before this patch you can see the sharing state stuck in pending.
Please …

fix(Pool): sending too long error messages to the Orchestrator

---

charts/bpdm/Chart.yaml
charts/bpdm/charts/bpdm-cleaning-service-dummy/Chart.yaml
charts/bpdm/charts/bpdm-gate/Chart.yaml
charts/bpdm/charts/bpdm-orchestrator/Chart.yaml
charts/bpdm/charts/bpdm-pool/Chart.yaml
pom.xml

Create a first release candidate for the version 6.2.0

build(version): 6.2.0 release candidate 1

---

charts/bpdm/Chart.yaml
charts/bpdm/charts/bpdm-cleaning-service-dummy/Chart.yaml
charts/bpdm/charts/bpdm-gate/Chart.yaml
charts/bpdm/charts/bpdm-orchestrator/Chart.yaml
charts/bpdm/charts/bpdm-pool/Chart.yaml
pom.xml

build(version): 6.2.0 SNAPSHOT back from release candidate version

---

DEPENDENCIES

In this pull request, we are updating dependencies file as spring boot version bumped to 3.3.3 from 3.2.3.

docs(DEPENDENCIES): update

---

CHANGELOG.md
bpdm-cleaning-service-dummy/src/main/kotlin/org/eclipse/tractusx/bpdm/cleaning/service/CleaningServiceDummy.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/BusinessPartnerMappings.kt

In this pull request, we have removed assignment of uncategorized states while performing cleaning legal entity process.
Due to this assignment, states for legal entity will remain same which sharing member has been provided. 

fix(bpdm-clearing): refactored construction logic for legal entity states

---

charts/bpdm/Chart.yaml
charts/bpdm/charts/bpdm-cleaning-service-dummy/Chart.yaml
charts/bpdm/charts/bpdm-gate/Chart.yaml
charts/bpdm/charts/bpdm-orchestrator/Chart.yaml
charts/bpdm/charts/bpdm-pool/Chart.yaml
pom.xml

This pull request sets the projects version to release candidate 2 and trigger its workflows to release the app and charts for that release candidate.
Contributes to the release checks in #1082

build(version): 6.2.0 release candidate 2

---

charts/bpdm/Chart.yaml
charts/bpdm/charts/bpdm-cleaning-service-dummy/Chart.yaml
charts/bpdm/charts/bpdm-gate/Chart.yaml
charts/bpdm/charts/bpdm-orchestrator/Chart.yaml
charts/bpdm/charts/bpdm-pool/Chart.yaml
pom.xml

build(version): back to 6.2.0-SNAPSHOT after release candidate release

---

DEPENDENCIES

In this pull request, we updated the DEPENDENCIES file with the newest dependencies licence information.

docs: update DEPENDENCIES

---

CHANGELOG.md

In this pull request, we have updated CHANGELOG file for application version 6.2.0 where we have added references to the newly added and to changed entries.

docs(CHANGELOG): update

---

CHANGELOG.md
DEPENDENCIES
pom.xml

This pull request increases the netty-common version to fix a denial of service vulnerability.
#1112 

build(deps): increase netty-common version

---

CHANGELOG.md
bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/entity/LegalFormDb.kt
bpdm-pool/src/main/resources/db/migration/V6_2_0_4__make_legal_form_active_not_nullable.sql

This pull request fixes a bug when retrieving non-gleif legacy legal form data.
Fixes #1107 

fix(Pool): retrieving legacy legal form data

---

CHANGELOG.md
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/model/upsert/output/OutputUpsertData.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/OrchestratorMappings.kt
charts/bpdm/Chart.yaml
charts/bpdm/charts/bpdm-cleaning-service-dummy/Chart.yaml
charts/bpdm/charts/bpdm-gate/Chart.yaml
charts/bpdm/charts/bpdm-orchestrator/Chart.yaml
charts/bpdm/charts/bpdm-pool/Chart.yaml
pom.xml

This pull request fixes an error when the Gate tries to write a golden record task result to the output stage missing a legal name
fixes #1115 

fix(gate): write output without legal name

---

charts/bpdm/Chart.yaml
charts/bpdm/charts/bpdm-cleaning-service-dummy/Chart.yaml
charts/bpdm/charts/bpdm-gate/Chart.yaml
charts/bpdm/charts/bpdm-orchestrator/Chart.yaml
charts/bpdm/charts/bpdm-pool/Chart.yaml
pom.xml

This pull request creates the release candidate 5 for BPDM 6.2.0

build(release candidate): 6.2.0-rc5

---

.tractusx

In this pull request, we are uploading open api document for services in bpdm includes Pool, Gate and Orchestrator services to API-Hub.
Contributes to [#1012 ](https://github.com/eclipse-tractusx/bpdm/issues/1012)

chore(bpdm): Upload bpdm OpenAPI documents to Tractus-X API-Hub

---

docs/postman/EDC BPDM Consumer.postman_collection.json

This pull request updates the EDC consumer Postman collection for 6.2.0:
- update requests for EDC 0.8.0
- add examples

docs(Postman): update EDC consumer collection

---

docs/api/README.md
docs/architecture/11_Risks_And_Technical_Debts.md

this pull request updates the API README for 6.2.0 version:
- divided README into API descriptions and API use cases
- added API uses cases
- removed Gate Input/Output mappings and Pool mappings
- moved Cleaning Service Dummy restrictions to technical debts section
contributes to #1082

docs(api): update api README for 6.2.0

---

README.md
docs/developer/README.md

This pull request updates the information for Github workflows to the current state. Also the section is moved from the README to the Developer documentation as it is not so relevant for normal users.
Contributes to #1082 

docs(README): rework the Github workflows section

---

.tractusx
CHANGELOG.md
charts/bpdm/CHANGELOG.md
charts/bpdm/Chart.yaml
charts/bpdm/charts/bpdm-cleaning-service-dummy/CHANGELOG.md
charts/bpdm/charts/bpdm-cleaning-service-dummy/Chart.yaml
charts/bpdm/charts/bpdm-gate/CHANGELOG.md
charts/bpdm/charts/bpdm-gate/Chart.yaml
charts/bpdm/charts/bpdm-orchestrator/CHANGELOG.md
charts/bpdm/charts/bpdm-orchestrator/Chart.yaml
charts/bpdm/charts/bpdm-pool/CHANGELOG.md
charts/bpdm/charts/bpdm-pool/Chart.yaml
docs/api/gate.json
docs/api/gate.yaml
docs/api/orchestrator.json
docs/api/orchestrator.yaml
docs/api/pool.json
docs/api/pool.yaml
pom.xml

This pull request raises the current version of the main to 6.3.0 SNAPSHOT (5.3.0 SNAPSHOT for Charts).
Also made sure that the 6.3.0 SNAPSHOT versions of the API will be deployed as well.

build: BPDM 6.3.0-SNAPSHOT - BPDM Charts 5.3.0-SNAPSHOT

---

.github/workflows/app-test-charts.yaml
bpdm-common-test/src/main/resources/keycloak/CX-Central.json
charts/bpdm/CHANGELOG.md
charts/bpdm/Chart.yaml
charts/bpdm/charts/bpdm-cleaning-service-dummy/CHANGELOG.md
charts/bpdm/charts/bpdm-cleaning-service-dummy/Chart.yaml
charts/bpdm/charts/bpdm-gate/CHANGELOG.md
charts/bpdm/charts/bpdm-gate/Chart.yaml
charts/bpdm/charts/bpdm-orchestrator/CHANGELOG.md
charts/bpdm/charts/bpdm-orchestrator/Chart.yaml
charts/bpdm/charts/bpdm-pool/CHANGELOG.md
charts/bpdm/charts/bpdm-pool/Chart.yaml
charts/bpdm/values.yaml

Update the tested and BPDM Chart referenced Central IDP to version 4.0.0.

feat(Central-IDP): increase Central-IDP version to 4.0.0

---

CHANGELOG.md
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/GoldenRecordUpdateServices.kt
bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/AddressService.kt
bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/BusinessPartnerBuildService.kt
bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/ResponseMappings.kt
bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/TaskStepBuildService.kt
bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/service/TaskResolutionServiceTest.kt

This PR contains the development to update the linkage from LegalAddress to LegalAndSiteMainAddress and AdditionalAddress to SiteMainAddress. Also add the method in Gate to handle the update of BPNS based on the changeLog entries.
Issue: https://github.com/eclipse-tractusx/bpdm/issues/1121

feat: Update linkage between bpns and add support to update the data in gate from pool

---

docs/README.md
docs/admin/README.md

docs(admin): add small admin guide

---

charts/bpdm/Chart.yaml
charts/bpdm/charts/bpdm-cleaning-service-dummy/Chart.yaml
charts/bpdm/charts/bpdm-common/Chart.yaml
charts/bpdm/charts/bpdm-gate/Chart.yaml
charts/bpdm/charts/bpdm-orchestrator/Chart.yaml
charts/bpdm/charts/bpdm-pool/Chart.yaml
pom.xml

This pull request builds the release candidate 1 for the new BPDM 6.3.0 and BPDM Chart 5.3.0 versions.

build(release-candidate): BPDM 6.3.0-rc1 & BPDM Charts 5.3.0-rc1

---

charts/bpdm/Chart.yaml
charts/bpdm/charts/bpdm-cleaning-service-dummy/Chart.yaml
charts/bpdm/charts/bpdm-common/Chart.yaml
charts/bpdm/charts/bpdm-gate/Chart.yaml
charts/bpdm/charts/bpdm-orchestrator/Chart.yaml
charts/bpdm/charts/bpdm-pool/Chart.yaml
pom.xml

We need to switch back to snapshot version in order to apply more fixes for 6.3.0.

build: back to SNAPSHOT version for 6.3.0

---

charts/bpdm/Chart.yaml
charts/bpdm/charts/bpdm-cleaning-service-dummy/Chart.yaml
charts/bpdm/charts/bpdm-common/Chart.yaml
charts/bpdm/charts/bpdm-gate/Chart.yaml
charts/bpdm/charts/bpdm-orchestrator/Chart.yaml
charts/bpdm/charts/bpdm-pool/Chart.yaml
pom.xml

build: back to 6.3.0-SNAPSHOT/Charts 5.3.0-SNAPSHOT

---

docs/postman/EDC BPDM Consumer.postman_collection.json
docs/postman/EDC Provider Setup.postman_collection.json

Provider:
- Fix mistake in default value for client secret path variables
- Add a new variable for consumer name
Consumer:
- Add relation controller endpoints to input full access and input read access collections

docs: update EDC provider and consumer Postman collections

---

docs/postman/EDC BPDM Consumer.postman_collection.json

This pull request removes version tag present in resource url for releation controller in EDC consumer Postman collection/

docs: fixed EDC consumer Postman collection

---

CHANGELOG.md
charts/bpdm/CHANGELOG.md
charts/bpdm/Chart.yaml
charts/bpdm/README.md
charts/bpdm/charts/bpdm-cleaning-service-dummy/CHANGELOG.md
charts/bpdm/charts/bpdm-cleaning-service-dummy/Chart.yaml
charts/bpdm/charts/bpdm-cleaning-service-dummy/README.md
charts/bpdm/charts/bpdm-common/CHANGELOG.md
charts/bpdm/charts/bpdm-common/Chart.yaml
charts/bpdm/charts/bpdm-gate/CHANGELOG.md
charts/bpdm/charts/bpdm-gate/Chart.yaml
charts/bpdm/charts/bpdm-gate/README.md
charts/bpdm/charts/bpdm-orchestrator/CHANGELOG.md
charts/bpdm/charts/bpdm-orchestrator/Chart.yaml
charts/bpdm/charts/bpdm-orchestrator/README.md
charts/bpdm/charts/bpdm-pool/CHANGELOG.md
charts/bpdm/charts/bpdm-pool/Chart.yaml
charts/bpdm/charts/bpdm-pool/README.md
docs/api/gate.json
docs/api/gate.yaml
docs/api/orchestrator.json
docs/api/orchestrator.yaml
docs/api/pool.json
docs/api/pool.yaml
pom.xml

This pull request, added SNAPSHOT version for bpdm app and chart version. So, it can be used to build features and bugs which will tag to next app release 25.06.

build: BPDM 6.4.0-SNAPSHOT & BPDM Charts 5.4.0-SNAPSHOT

---

CHANGELOG.md
charts/bpdm/Chart.yaml
charts/bpdm/README.md
charts/bpdm/charts/bpdm-cleaning-service-dummy/CHANGELOG.md
charts/bpdm/charts/bpdm-cleaning-service-dummy/Chart.yaml
charts/bpdm/charts/bpdm-cleaning-service-dummy/README.md
charts/bpdm/charts/bpdm-gate/CHANGELOG.md
charts/bpdm/charts/bpdm-gate/Chart.yaml
charts/bpdm/charts/bpdm-gate/README.md
charts/bpdm/charts/bpdm-orchestrator/CHANGELOG.md
charts/bpdm/charts/bpdm-orchestrator/Chart.yaml
charts/bpdm/charts/bpdm-orchestrator/README.md
charts/bpdm/charts/bpdm-pool/CHANGELOG.md
charts/bpdm/charts/bpdm-pool/Chart.yaml
charts/bpdm/charts/bpdm-pool/README.md
docs/api/gate.json
docs/api/gate.yaml
docs/api/orchestrator.json
docs/api/orchestrator.yaml
docs/api/pool.json
docs/api/pool.yaml
pom.xml

This pull request, creates new SNAPSHOT version for BPDM app and BPDM charts.

build: BPDM 7.0.0-SNAPSHOT & BPDM Charts 6.0.0-SNAPSHOT

---

CHANGELOG.md
bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/model/RelationType.kt
bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/model/RelationVerboseDto.kt
bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/repository/RelationRepository.kt
bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/ResponseMappings.kt
bpdm-pool/src/main/resources/db/migration/V7_0_0_0__alter_relation_column.sql
bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/controller/LegalEntityControllerIT.kt
docs/api/pool.json
docs/api/pool.yaml

This pull request enhances logic for bpdm pool service to adapt relations on legal entity.
For now, I have added abstract unit test where manually relations being created but there is scope for changing test case logic in future once we have orchestrator logic present so then there will be no need to insert relation manually to the bpdm-pool service.
Contributes to #1254 

feat(bpdm-pool): enhanced logic for legal entity on relation

---

DEPENDENCIES
pom.xml

This fixes a vulnerability in the current spring boot security crypto module.
Fixes #1275 

build(dep): overwrite spring-security-crypto dependency version 

---

CHANGELOG.md
bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/RelationsGoldenRecordTaskApi.kt
bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/client/OrchestrationApiClientImpl.kt
bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/client/RelationsGoldenRecordTaskApiClient.kt
bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/model/BusinessPartnerRelations.kt
bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/model/TaskClientRelationsStateDto.kt
bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/model/TaskCreateRelationsRequest.kt
bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/model/TaskCreateRelationsRequestEntry.kt
bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/model/TaskCreateRelationsResponse.kt
bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/model/TaskProcessingRelationsStateDto.kt
bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/model/TaskRelationsErrorDto.kt
bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/model/TaskRelationsErrorType.kt
bpdm-orchestrator/src/main/kotlin/org/eclipse/tractusx/bpdm/orchestrator/controller/RelationsGoldenRecordTaskController.kt
bpdm-orchestrator/src/main/kotlin/org/eclipse/tractusx/bpdm/orchestrator/entity/RelationsGoldenRecordTaskDb.kt
bpdm-orchestrator/src/main/kotlin/org/eclipse/tractusx/bpdm/orchestrator/entity/RelationsTaskErrorDb.kt
bpdm-orchestrator/src/main/kotlin/org/eclipse/tractusx/bpdm/orchestrator/exception/RelationsIllegalStateException.kt
bpdm-orchestrator/src/main/kotlin/org/eclipse/tractusx/bpdm/orchestrator/repository/RelationsGoldenRecordTaskRepository.kt
bpdm-orchestrator/src/main/kotlin/org/eclipse/tractusx/bpdm/orchestrator/service/RelationsGoldenRecordTaskService.kt
bpdm-orchestrator/src/main/kotlin/org/eclipse/tractusx/bpdm/orchestrator/service/RelationsGoldenRecordTaskStateMachine.kt
bpdm-orchestrator/src/main/kotlin/org/eclipse/tractusx/bpdm/orchestrator/service/RelationsRequestMapper.kt
bpdm-orchestrator/src/main/kotlin/org/eclipse/tractusx/bpdm/orchestrator/service/RelationsResponseMapper.kt
bpdm-orchestrator/src/main/resources/db/migration/V7_0_0_0__create_relation_golden_record_table.sql
bpdm-orchestrator/src/test/kotlin/org/eclipse/tractusx/bpdm/orchestrator/auth/AuthAdminIT.kt
bpdm-orchestrator/src/test/kotlin/org/eclipse/tractusx/bpdm/orchestrator/auth/AuthTaskCreatorIT.kt
bpdm-orchestrator/src/test/kotlin/org/eclipse/tractusx/bpdm/orchestrator/auth/AuthTaskProcessorCleanIT.kt
bpdm-orchestrator/src/test/kotlin/org/eclipse/tractusx/bpdm/orchestrator/auth/AuthTaskProcessorPoolTaskProcessingJobApiSyncIT.kt
bpdm-orchestrator/src/test/kotlin/org/eclipse/tractusx/bpdm/orchestrator/auth/AuthTestBase.kt
bpdm-orchestrator/src/test/kotlin/org/eclipse/tractusx/bpdm/orchestrator/auth/NoAuthIT.kt

This pull request, adds new api endpoint for bpdm-orchestrator service to create business partner relations task.
This endpoint will be the POST endpoint.
Contributes to #1274

feat(bpdm-orchestrator): relation api create task

---

CHANGELOG.md
bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/GateRelationOutputApi.kt
bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/client/GateClientImpl.kt
bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/client/RelationOutputApiClient.kt
bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/RelationOutputDto.kt
bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/request/RelationOutputSearchRequest.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/config/GoldenRecordProcessConfigProperties.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/config/GoldenRecordTaskConfiguration.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/controller/RelationController.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/controller/RelationOutputController.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/RelationOutputDb.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/RelationSharingStateDb.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/repository/RelationRepository.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/IRelationService.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/RelationService.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/RelationSharingStateService.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/RelationTaskResolutionService.kt
bpdm-gate/src/main/resources/application.yml
bpdm-gate/src/main/resources/db/migration/V7_0_0_4__add_relation_output_columns.sql
bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/auth/AuthAdminIT.kt
bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/auth/AuthInputConsumerIT.kt
bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/auth/AuthInputManagerIT.kt
bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/auth/AuthOutputConsumerIT.kt
bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/auth/AuthTestBase.kt
bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/auth/NoAuthIT.kt
bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/RelationOutputControllerIT.kt
bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/service/RelationTaskResolutionServiceIT.kt
bpdm-gate/src/test/resources/application-test.yml
docs/api/gate.json
docs/api/gate.yaml

This pull request adds business partner relation outputs to BPDM Gate
- adds endpoints for querying outputs
- adds logic to resolve tasks and create outputs
Contributes to #1277

feat(Gate): add business partner relation outputs

---

CHANGELOG.md
bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/SharableRelationType.kt
bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/request/RelationOutputSearchRequest.kt
bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/response/BusinessPartnerOutputDto.kt
bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/response/BusinessPartnerOutputRelationDto.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/generic/BusinessPartnerDb.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/model/upsert/output/OutputUpsertData.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/model/upsert/output/OutputUpsertDataWithRelations.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/model/upsert/output/Relation.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/repository/RelationRepository.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/BusinessPartnerMappings.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/BusinessPartnerService.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/GoldenRecordUpdateServices.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/IRelationService.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/OutputUpsertMappings.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/RelationService.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/RelationTaskResolutionService.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/util/BusinessPartnerComparisonUtil.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/util/BusinessPartnerCopyUtil.kt
bpdm-gate/src/main/resources/db/migration/V7_0_0_5__add_business_partner_output_relations.sql
bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/RelationOutputControllerIT.kt
bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/service/GoldenRecordUpdateServiceIT.kt
bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/service/RelationTaskResolutionServiceIT.kt
docs/api/gate.json
docs/api/gate.yaml

This pull request adds relation information to the business partner output stage. Relations are updated with every update on the output stage.
- relations are retrieved when querying business partner outputs
- relations are updated on Pool golden record updates
Contributes to #1278 

feat(Gate): add relations to business partner output stage

---

bpdm-system-tester/src/main/kotlin/org/eclipse/tractusx/bpdm/test/system/stepdefinations/BusinessPartnerRelationStepDefs.kt
bpdm-system-tester/src/main/kotlin/org/eclipse/tractusx/bpdm/test/system/utils/TestRepository.kt

This pull request fixes a race conditon bug in the system tester by making the task reservation an atomic operation.
Sometimes the Chart testing fails due to a task-id not being found. This fixed race conditon was the likely reason for this behaviour.

test(System): fix race condition when reserving tasks

---

bpdm-pool/src/main/resources/db/migration/V7_0_0_2__create_identifier_types.sql

This pull request adds additional identifier types through a flyway migration script.

feat(Pool): add additional identifier types

---

bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/dto/openapidescription/IdentifierTypeDescription.kt
docs/api/pool.json
docs/api/pool.yaml

Add description for the enum values of the identifier type categories according to https://github.com/eclipse-tractusx/bpdm/issues/1297#issuecomment-2820315829 .
Contributes to #1297

docs(Api): add descriptions for identifier type categories

---

CHANGELOG.md
bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/ApiCommons.kt
bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/GateChangelogApi.kt
bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/client/ChangelogApiClient.kt
docs/api/gate.json
docs/api/gate.yaml

This pull request now adapts the Gate api endpoint paths to  always include business partner or relation term:
- add business partner into path where necessary
- standardize the relation path name
Implements #1327

feat(Gate): business partner and relation endpoint paths

---

charts/bpdm/Chart.yaml
charts/bpdm/README.md
charts/bpdm/charts/bpdm-cleaning-service-dummy/Chart.yaml
charts/bpdm/charts/bpdm-cleaning-service-dummy/README.md
charts/bpdm/charts/bpdm-common/Chart.yaml
charts/bpdm/charts/bpdm-gate/Chart.yaml
charts/bpdm/charts/bpdm-gate/README.md
charts/bpdm/charts/bpdm-orchestrator/Chart.yaml
charts/bpdm/charts/bpdm-orchestrator/README.md
charts/bpdm/charts/bpdm-pool/Chart.yaml
charts/bpdm/charts/bpdm-pool/README.md
docs/api/gate.json
docs/api/gate.yaml
docs/api/orchestrator.json
docs/api/orchestrator.yaml
docs/api/pool.json
docs/api/pool.yaml
pom.xml

This pull request releases the release candidate 1 for BPDM App version 7.0.0 and BPDM Chart 6.0.0.
Also updated below with new release candidate version,

build(release-candidate): BPDM 7.0.0-rc1 & BPDM Charts 6.0.0-rc1

---

CHANGELOG.md
docs/admin/README.md
docs/api/README.md
docs/architecture/08_Crosscutting_Concepts.md
docs/architecture/11_Risks_And_Technical_Debts.md

This pull request adds several minor updates to the documentation for information that has become outdated for BPDM version 7.0.0.
Contributes to #1333 

docs: add minor documentation adaptions for BPDM version 7.0.0

---

docs/postman/EDC BPDM Consumer.postman_collection.json

This pull request updates postman collection for BPDM consumer EDC.
Postman collection now contains new business partner relation endpoints as well as updates on old payload for business partner endpoints.
Contributes to #1333 

docs: updated edc bpdm consumer postman collection

---

CHANGELOG.md
charts/bpdm/CHANGELOG.md
charts/bpdm/Chart.yaml
charts/bpdm/README.md
charts/bpdm/charts/bpdm-cleaning-service-dummy/CHANGELOG.md
charts/bpdm/charts/bpdm-cleaning-service-dummy/Chart.yaml
charts/bpdm/charts/bpdm-cleaning-service-dummy/README.md
charts/bpdm/charts/bpdm-gate/CHANGELOG.md
charts/bpdm/charts/bpdm-gate/Chart.yaml
charts/bpdm/charts/bpdm-gate/README.md
charts/bpdm/charts/bpdm-orchestrator/CHANGELOG.md
charts/bpdm/charts/bpdm-orchestrator/Chart.yaml
charts/bpdm/charts/bpdm-orchestrator/README.md
charts/bpdm/charts/bpdm-pool/CHANGELOG.md
charts/bpdm/charts/bpdm-pool/Chart.yaml
charts/bpdm/charts/bpdm-pool/README.md
docs/api/gate.json
docs/api/gate.yaml
docs/api/orchestrator.json
docs/api/orchestrator.yaml
docs/api/pool.json
docs/api/pool.yaml
pom.xml

This pull request, creates new SNAPSHOT version for BPDM app and BPDM charts.

build: BPDM 7.1.0-SNAPSHOT & BPDM Charts 6.1.0-SNAPSHOT

---

bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/config/OpenApiConfig.kt
bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/dto/PaginationRequest.kt
bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/model/request/AddressSearchRequest.kt
bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/model/request/LegalEntitySearchRequest.kt
bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/model/request/SiteBpnSearchRequest.kt
bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/model/request/SiteSearchRequest.kt

This pull request changes the logic how to generate OpenAPI from object model to fix the required constraints.
Workaround for open-api issue: https://github.com/springdoc/springdoc-openapi/issues/2978

fix(API): wrong required constraints on parameters

---

README.md
bpdm-cleaning-service-dummy/README.md
bpdm-gate/README.md
bpdm-orchestrator/README.md
bpdm-pool/README.md

This PR updates the service descriptions, which also shall be used in the data space service map.
Resolves https://github.com/eclipse-tractusx/bpdm/issues/1368.

doc: Update Service Descriptions

---

CHANGELOG.md
bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/RelationType.kt
bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/SharableRelationType.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/GoldenRecordUpdateServices.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/RelationSharingStateService.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/RelationTaskCreationService.kt
bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/RelationTaskResolutionService.kt
bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/service/RelationTaskCreationServiceIT.kt
bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/service/RelationTaskResolutionServiceIT.kt
bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/model/BusinessPartnerRelations.kt
bpdm-orchestrator/src/main/kotlin/org/eclipse/tractusx/bpdm/orchestrator/entity/RelationsGoldenRecordTaskDb.kt
bpdm-orchestrator/src/main/kotlin/org/eclipse/tractusx/bpdm/orchestrator/service/RelationsRequestMapper.kt
bpdm-orchestrator/src/main/kotlin/org/eclipse/tractusx/bpdm/orchestrator/service/RelationsResponseMapper.kt
bpdm-orchestrator/src/test/kotlin/org/eclipse/tractusx/bpdm/orchestrator/controller/RelationsGoldenRecordTaskControllerIT.kt
bpdm-orchestrator/src/test/kotlin/org/eclipse/tractusx/bpdm/orchestrator/controller/RelationsGoldenRecordTaskEventControllerIT.kt
bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/model/RelationType.kt
bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/repository/RelationRepository.kt
bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/OwnedByRelationUpsertService.kt
bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/TaskRelationsStepBuildService.kt
bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/service/TaskRelationsResolutionServiceTest.kt
docs/api/gate.json
docs/api/gate.yaml
docs/api/orchestrator.json
docs/api/orchestrator.yaml
docs/api/pool.json
docs/api/pool.yaml

This pull request adds the IsOwnedBy relationhip type to the golden record process components. This relationship type depicts legal hierarchies for majority ownerships.
Implements #1399

feat: add IsOwnedBy relation to golden record process components

---

charts/bpdm/Chart.yaml
charts/bpdm/README.md
charts/bpdm/charts/bpdm-cleaning-service-dummy/Chart.yaml
charts/bpdm/charts/bpdm-cleaning-service-dummy/README.md
charts/bpdm/charts/bpdm-gate/Chart.yaml
charts/bpdm/charts/bpdm-gate/README.md
charts/bpdm/charts/bpdm-orchestrator/Chart.yaml
charts/bpdm/charts/bpdm-orchestrator/README.md
charts/bpdm/charts/bpdm-pool/Chart.yaml
charts/bpdm/charts/bpdm-pool/README.md
docs/api/gate.json
docs/api/gate.yaml
docs/api/orchestrator.json
docs/api/orchestrator.yaml
docs/api/pool.json
docs/api/pool.yaml
pom.xml

This pull request releases the release candidate 1 for BPDM App version 7.1.0 and BPDM Chart 6.1.0.
Also updated below with new release candidate version,

build(release-candidate): BPDM 7.1.0-rc1 & BPDM Charts 6.1.0-rc1

---

charts/bpdm/Chart.yaml
charts/bpdm/README.md
charts/bpdm/charts/bpdm-cleaning-service-dummy/Chart.yaml
charts/bpdm/charts/bpdm-cleaning-service-dummy/README.md
charts/bpdm/charts/bpdm-gate/Chart.yaml
charts/bpdm/charts/bpdm-gate/README.md
charts/bpdm/charts/bpdm-orchestrator/Chart.yaml
charts/bpdm/charts/bpdm-orchestrator/README.md
charts/bpdm/charts/bpdm-pool/Chart.yaml
charts/bpdm/charts/bpdm-pool/README.md
docs/api/gate.json
docs/api/gate.yaml
docs/api/orchestrator.json
docs/api/orchestrator.yaml
docs/api/pool.json
docs/api/pool.yaml
pom.xml

This pull request taking back to app BPDM 7.1.0-SNAPSHOT & chart BPDM Charts 6.1.0-SNAPSHOT version to work on bug fix.

build: Back to BPDM 7.1.0-SNAPSHOT & BPDM Charts 6.1.0-SNAPSHOT

---

charts/bpdm/Chart.yaml
charts/bpdm/README.md
charts/bpdm/charts/bpdm-cleaning-service-dummy/Chart.yaml
charts/bpdm/charts/bpdm-cleaning-service-dummy/README.md
charts/bpdm/charts/bpdm-gate/Chart.yaml
charts/bpdm/charts/bpdm-gate/README.md
charts/bpdm/charts/bpdm-orchestrator/Chart.yaml
charts/bpdm/charts/bpdm-orchestrator/README.md
charts/bpdm/charts/bpdm-pool/Chart.yaml
charts/bpdm/charts/bpdm-pool/README.md
docs/api/gate.json
docs/api/gate.yaml
docs/api/orchestrator.json
docs/api/orchestrator.yaml
docs/api/pool.json
docs/api/pool.yaml
pom.xml

This pull request releases the release candidate 4 for BPDM App version 7.1.0 and BPDM Chart 6.1.0.
Also updated below with new release candidate version,

build(release-candidate): BPDM 7.1.0-rc4 & BPDM Charts 6.1.0-rc4

---

charts/bpdm/Chart.yaml
charts/bpdm/charts/bpdm-cleaning-service-dummy/Chart.yaml
charts/bpdm/charts/bpdm-gate/Chart.yaml
charts/bpdm/charts/bpdm-orchestrator/Chart.yaml
charts/bpdm/charts/bpdm-pool/Chart.yaml
docs/api/gate.json
docs/api/gate.yaml
docs/api/orchestrator.json
docs/api/orchestrator.yaml
docs/api/pool.json
docs/api/pool.yaml
pom.xml

This pull request sets the BPDM version back to SNAPSHOT after release candidate version 4

build(version): SNAPSHOT version for app 7.1.0 and Charts 6.1.0

---

CHANGELOG.md
DEPENDENCIES
charts/bpdm/CHANGELOG.md
charts/bpdm/Chart.yaml
charts/bpdm/README.md
charts/bpdm/charts/bpdm-cleaning-service-dummy/CHANGELOG.md
charts/bpdm/charts/bpdm-cleaning-service-dummy/Chart.yaml
charts/bpdm/charts/bpdm-cleaning-service-dummy/README.md
charts/bpdm/charts/bpdm-gate/CHANGELOG.md
charts/bpdm/charts/bpdm-gate/Chart.yaml
charts/bpdm/charts/bpdm-gate/README.md
charts/bpdm/charts/bpdm-orchestrator/CHANGELOG.md
charts/bpdm/charts/bpdm-orchestrator/Chart.yaml
charts/bpdm/charts/bpdm-orchestrator/README.md
charts/bpdm/charts/bpdm-pool/CHANGELOG.md
charts/bpdm/charts/bpdm-pool/Chart.yaml
charts/bpdm/charts/bpdm-pool/README.md
docs/api/gate.json
docs/api/gate.yaml
docs/api/orchestrator.json
docs/api/orchestrator.yaml
docs/api/pool.json
docs/api/pool.yaml
pom.xml

This pull request releases BPDM/ BPDM Charts in version 7.1.0/6.1.0

build(version): 7.1.0 BPDM / 6.1.0 BPDM Charts
