- charts/gate/Chart.yaml
- charts/gate/values.yaml
- charts/pool/Chart.yaml
- charts/pool/values.yaml
Docker images should be pulled from the catenax-ng fork of this repository for now.
> cicd(Charts): set docker images for pool and gate to tx-bpdm

- .github/workflows/build-docker-all.yaml
- README.adoc
- bpdm-gate/Dockerfile
- bpdm-pool/Dockerfile
Based on [Docker release guidelines](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-2)
> cicd(Dockerfiles): exchange Docker base image to eclipse-temurin

- .github/workflows/deploy-maven.yaml
Remove push path conditions for maven deploy workflow. This enables the workflow to try to deploy a maven library module everytime a push to main or release candidate branch has happened.
> cicd(worfklows): remove deploy-maven.yaml workflow path conditions

- pom.xml
Increase the version of the spring-core dependency to 6.0.8 in order to avoid vulnerability issues.
> feat(pom): increase transitive dependency spring-core to version 6.0.8

- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/GateLegalEntityApi.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/controller/LegalEntityController.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/LegalEntityService.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/LegalEntityControllerInputIT.kt
Add legalentity new endpoint for getting bpn with filter external ids
> Legal entity new endpoint

- bpdm-gate/Dockerfile
- bpdm-pool/Dockerfile
Match default user context with the default security context of the BPDM Pool and Gate Helm Charts.
Relevant Issue: #110
> Dockerfiles: update default user context

- .tractusx
updates eclipse-tractusx/bpdm#108
> docs(meta): add tractusx meta file for repository

- DEPENDENCIES
- README.md
- bpdm-common/pom.xml
- bpdm-gate-api/pom.xml
- bpdm-gate/Dockerfile
- bpdm-gate/pom.xml
- bpdm-pool-api/pom.xml
- bpdm-pool/Dockerfile
- bpdm-pool/pom.xml
- pom.xml
Introduces fixes and optimizations for BPDM services to satisfy Tractus-X quality gate rules in order to be compatible with the 3.1 release.
Bumps the minor version number of BPDM 3.2.x to 3.2.2.
Helm chart appversion changes need to follow.
> Add application fixes for Tractus-X quality gate 3.1

- charts/gate/CHANGELOG.md
- charts/gate/Chart.yaml
- charts/gate/templates/ingress.yaml
- charts/pool/CHANGELOG.md
- charts/pool/Chart.yaml
- charts/pool/templates/ingress.yaml
Resolves issues related to the quality gate rules of tractus-x release 3.1 in scope for the Helm charts:
- Adds missing license headers to the ingress templates.
- Updates the app version in the charts to 3.3.2
- Updates the chart versions themselved
> Fix Tractus-X QG 3.1 Helm Chart Issues

- charts/gate/Chart.yaml
- charts/gate/templates/ingress.yaml
- charts/pool/Chart.yaml
- charts/pool/templates/ingress.yaml
This avoids the license information coming first in the ingress resource as it causes the helm deployment to be corrupted under helmv2
updates eclipse-tractusx/bpdm#143
> fix(helm): move license "header" of ingress under metadata

- charts/gate/CHANGELOG.md
- charts/gate/Chart.yaml
- charts/gate/templates/ingress.yaml
- charts/pool/CHANGELOG.md
- charts/pool/Chart.yaml
- charts/pool/templates/ingress.yaml
Move License Headers under the metadata section so that they don't break the deployment.
Updates issue #143
> Version 3.2.x: Fix License Header issues for Helmv2 

- bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/util/CollectionUtils.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/AddressIdentifier.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/AddressState.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/AlternativePostalAddress.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/GeographicCoordinate.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/LogisticAddress.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/PhysicalPostalAddress.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/Region.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/Street.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/repository/GateAddressRepository.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/AddressPersistenceService.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/AddressService.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/ResponseMappings.kt
- bpdm-gate/src/main/resources/db/migration/V0_1_0_0__table_creation_address.sql
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/AddressControllerInputIT.kt
When a sharing member shares a business partner via the Gate API, the information can be persisted in the database. If the information is already present in the database, then the entries are overwritten and updated. First implementation for the Addresses logic. Relationships between Legal Entities and Addresses not in place.
> Persistence of shared business partners - (Logistic Addresses)

- bpdm-bridge-dummy/src/test/kotlin/com/catenax/bpdm/bridge/dummy/ApplicationTests.kt
- bpdm-bridge-dummy/src/test/kotlin/com/catenax/bpdm/bridge/dummy/util/BpdmGateContextInitializer.kt
- bpdm-bridge-dummy/src/test/kotlin/com/catenax/bpdm/bridge/dummy/util/BpdmPoolContextInitializer.kt
- bpdm-bridge-dummy/src/test/kotlin/com/catenax/bpdm/bridge/dummy/util/OpenSearchContextInitializer.kt
- bpdm-bridge-dummy/src/test/kotlin/com/catenax/bpdm/bridge/dummy/util/PostgreSQLContextInitializer.kt
- bpdm-bridge-dummy/src/test/resources/application-test.properties
Add BPDM pool and gate for Test Env
> feat(Gate-Pool): Add Bpdm pool and gate containers to test env

- bpdm-bridge-dummy/src/main/kotlin/com/catenax/bpdm/bridge/dummy/service/GateQueryService.kt
When querying the legal entities, sites and addresses the bridge dummy should iterate over every page.
Issue related #213
> Fix - Pagination Error for Gate Import

- bpdm-bridge-dummy/src/main/kotlin/com/catenax/bpdm/bridge/dummy/service/GateQueryService.kt
- bpdm-bridge-dummy/src/main/kotlin/com/catenax/bpdm/bridge/dummy/service/GateUpdateService.kt
- bpdm-bridge-dummy/src/main/kotlin/com/catenax/bpdm/bridge/dummy/service/PoolUpdateService.kt
- bpdm-bridge-dummy/src/main/kotlin/com/catenax/bpdm/bridge/dummy/service/SyncService.kt
- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/GateChangelogApi.kt
- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/request/ChangeLogSearchRequest.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/controller/ChangelogController.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/repository/ChangelogRepository.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/AddressService.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/ChangelogService.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/LegalEntityService.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/SiteService.kt
- bpdm-gate/src/main/resources/db/migration/V4_0_0_0__uppercase_lsa_types.sql
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/ChangeLogControllerIT.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/SharingStateControllerIT.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/util/CommonValues.kt
Merge the two changelog endpoints of the BPDM Gate and create a new endpoint which contains the filters fromTime, external-ids and lsaTypes. Fixes issue #241
> Gate API: Overhaul Changelog Endpoint

- bpdm-bridge-dummy/src/main/kotlin/com/catenax/bpdm/bridge/dummy/service/PoolUpdateService.kt
- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/LogisticAddressGateDto.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/AddressPersistenceService.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/ResponseMappings.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/SaasRequestMappingService.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/util/RequestValues.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/util/ResponseValues.kt
In the Gate API replaces the field name with the array nameParts for each DTO describing a logistic address.
> Gate API: Replace Name with Nameparts in Logistic Address

- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/LegalEntityPersistenceService.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/LegalEntityService.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/SitePersistenceService.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/SiteService.kt
When the legal entity is updated there should be a changelog entry for the legal address. Likewise there should be a changelog entry for the main address if a site is updated.
Related Issue: fix #270
> Fix - Legal/Main Address Changelogs on Update/Create

- docs/postman/BPDM Bridge Dummy.postman_collection.json
- docs/postman/BPDM Gate.postman_collection.json
- docs/postman/BPDM Pool.postman_collection.json
- docs/postman/Local.postman_environment.json
Updated postman collection with new data model for Gate, Pool and Bridge dummy services.
Related to issue : [#288 ](#288)
> API-Model: Update postman collection with new data model #288

- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/controller/ChangelogController.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/ChangelogEntry.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/repository/ChangelogRepository.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/AddressService.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/ChangelogService.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/LegalEntityPersistenceService.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/LegalEntityService.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/SitePersistenceService.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/SiteService.kt
- bpdm-gate/src/main/resources/db/migration/V4_0_0_1__update_change_log_entry_add_column.sql
- bpdm-gate/src/main/resources/db/migration/V4_0_0_2__update_change_log_entry_add_column.sql
---
title: 'feat: Add dataType column to ChangelogEntry entity'
---
This PR enhances the ChangelogService by updating it to use the new dataType column introduced in the ChangelogEntry entity. This allows the service to filter changelog entries based on the dataType value, providing more precise and efficient querying capabilities.
Fixes #https://github.com/eclipse-tractusx/bpdm/issues/269
> Feat(Gate): Add dataType column to ChangelogEntry entity

- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/controller/AddressController.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/controller/ChangelogController.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/controller/LegalEntityController.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/controller/SharingStateController.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/controller/SiteController.kt
---
title: 'fix: Fix error 500 when calling sharing api'
---
Fix error when calling sharing state api /api/catena/sharing-state
Missing annotation on var for pre auth 
Added and removed unused declared vars
Fixes # 
- Check out our guide on [how to contribute](https://eclipse-tractusx.github.io/docs/oss/how-to-contribute)
- Check out our [Release …
> Fix(Gate): Fix error 500 when calling sharing api

- .github/workflows/build-docker-all.yaml
- .github/workflows/build-docker.yaml
- bpdm-bridge-dummy/DOCKER_NOTICE.md
- bpdm-gate/DOCKER_NOTICE.md
- bpdm-pool/DOCKER_NOTICE.md
This pull request changes the docker build and push workflow to push built images to Dockerhub together with a Notice file. 
Currently, will push to these repositories:
[pool](https://hub.docker.com/r/tractusx/bpdm-pool)
[gate](https://hub.docker.com/r/tractusx/bpdm-gate)
[bridge-dummy](https://hub.docker.com/r/tractusx/bpdm-bridge-dummy)
Fixes #114
- Check out our guide on …
> (feat): Push Images to Dockerhub

- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/StreetGateDto.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/LegalEntity.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/LegalEntityRoles.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/LogisticAddress.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/PhysicalPostalAddress.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/Roles.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/Site.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/Street.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/AddressPersistenceService.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/LegalEntityPersistenceService.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/LegalEntityService.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/ResponseMappings.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/SitePersistenceService.kt
- bpdm-gate/src/main/resources/db/migration/V4_0_0_5__add_roles_table.sql
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/util/RequestValues.kt
---
---
This PR adds an table (Roles) to be able to persist the Roles in Legal Entities, Addresses and Sites. Also fixes the administrativeAreaLevel1 mapping, and adds new Street suffixes and prefixes with the correct mapping.
Related issues: fix #280 fix #285
---
> fix(gate): Gate persist new fields and fix fields retrieval

- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/LegalEntity.kt
- bpdm-gate/src/main/resources/db/migration/V4_0_0_6__make_legal_form_id_optional.sql
---
title: 'Gate Persistence: Legal Form should be optional'
---
This pull request makes column 'legal_form_id' from table 'bpdmgate.legal_entities' to accept Null values. And making Legal Form as optional attribute for Legal Entity on Gate Service.
Fixes #272 
> Gate Persistence: Legal Form should be optional

- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/LegalEntity.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/LegalEntityIdentifier.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/LegalEntityPersistenceService.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/ResponseMappings.kt
- bpdm-gate/src/main/resources/db/migration/V4_0_0_7__create_table_legal_entity_identifiers.sql
fixed the persistence of the identifiers collection on the legal entity
> fix(gate): fixed the persistence of LegalEntityIdentifier

- charts/bpdm/Chart.yaml
- charts/bpdm/charts/bpdm-bridge-dummy/CHANGELOG.md
- charts/bpdm/charts/bpdm-bridge-dummy/Chart.yaml
- charts/bpdm/charts/bpdm-bridge-dummy/values.yaml
- charts/bpdm/charts/bpdm-gate/CHANGELOG.md
- charts/bpdm/charts/bpdm-gate/Chart.yaml
- charts/bpdm/charts/bpdm-gate/values.yaml
- charts/bpdm/charts/bpdm-pool/CHANGELOG.md
- charts/bpdm/charts/bpdm-pool/Chart.yaml
- charts/bpdm/charts/bpdm-pool/values.yaml
- charts/bpdm/values.yaml
BPDM Helm Chart: Default image registry for bpdm images is now docker.io
> BPDM Helm 3.0.2-alpha.4: Change default image registry to dockerhub

- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/ResponseMappings.kt
- GeographicCoordinate.latitude/longitude was switched due to wrong order of constructor parameters.
- LegalEntity.identifiers were not persisted initially because the field was missing in LegalEntityGateOutputRequest.toLegalEntity.
Fixes #328
Fixes #329
> fix: Fix mapping errors in Gate persistence

- bpdm-bridge-dummy/src/main/kotlin/com/catenax/bpdm/bridge/dummy/dto/DtoConversionHelper.kt
- bpdm-bridge-dummy/src/main/kotlin/com/catenax/bpdm/bridge/dummy/dto/GateLegalEntityInfo.kt
- bpdm-bridge-dummy/src/main/kotlin/com/catenax/bpdm/bridge/dummy/service/GateQueryService.kt
- bpdm-bridge-dummy/src/main/kotlin/com/catenax/bpdm/bridge/dummy/service/GateUpdateService.kt
- bpdm-bridge-dummy/src/main/kotlin/com/catenax/bpdm/bridge/dummy/service/PoolUpdateService.kt
- bpdm-bridge-dummy/src/main/kotlin/com/catenax/bpdm/bridge/dummy/service/SyncService.kt
After successfully upserting a BP in the Pool its response is converted and upserted as the output version of the BP in the Gate.
Bridge helper methods for converting between Gate and Pool versions are moved to DtoConversionHelper.
Missing legalNameParts was added to GateQueryService.getLegalEntityInfos.
Fixes #279
> feat: Bridge writes back output data from Pool to Gate

- docs/dev-process/branching-strategy.mmd
Adds a branching strategy diagram in mermaid notation to the docs folder.
In order to review it, best use a renderer for mermaid diagrams (intellij plugin or similar).
In Github you can also preview it under the "view file" option.
> docs(branching) add branching strategy diagram to docs

- bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/PoolSiteApi.kt
- bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/model/response/SiteMatchVerboseDto.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/component/opensearch/SearchService.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/component/opensearch/impl/service/SearchServiceImpl.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/component/opensearch/mock/service/SearchServiceMock.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/controller/SiteController.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/ResponseMappings.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/SiteService.kt
- bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/controller/SiteControllerIT.kt
---
name: Fetch the number of records in CX Pool
---
In this PR, it was added an new endpoint for the Sites, which returns a list of paginated sites, and also the needed total number of all results in all pages.
- Check out our guide on [how to contribute](https://eclipse-tractusx.github.io/docs/oss/how-to-contribute)
- Check out our [Release …
> Feat - Fetch the number of records in CX Pool

- charts/bpdm/Chart.yaml
- charts/bpdm/charts/bpdm-bridge-dummy/Chart.yaml
- charts/bpdm/charts/bpdm-gate/Chart.yaml
- charts/bpdm/charts/bpdm-pool/Chart.yaml
This pull request increases the app version of the BPDM chart and its subcharts to 4.0.0-alpha.9. Also bumps the alpha versions of those charts.
Will introduce alpga release 3.0.2-alpha.6 of the BPDM chart.
> feat: Increase BPDM Chart app-version to 4.0.0-alpha.9

- bpdm-bridge-dummy/src/main/kotlin/com/catenax/bpdm/bridge/dummy/dto/DtoConversionHelper.kt
- bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/dto/response/AlternativePostalAddressVerboseDto.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/ResponseMappings.kt
Rename field **type** to **deliveryServiceType** in class **AlternativePostalAddressVerboseDto**
Fixes #357
> feat: API - Rename Type to DeliveryServiceType in AlternativePostalAddressVerboseDto

- bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/dto/response/RelationVerboseDto.kt
- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/response/AddressGateOutputDto.kt
- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/response/LegalEntityGateOutputDto.kt
- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/response/SiteGateOutputDto.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/ResponseMappings.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/util/ResponseValues.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/ResponseMappings.kt
Rename generic field name **bpn** to **bpnl**, **bpns** or **bpna** depending on actual business partner type.
Fixes #354
> feat: API - Rename generic BPN -> BPNL/BPNS/BPNA

- .tractusx
Adding the missing `repositories` key for listing connected repositories to the "BPDM" product.
File structure description in [TRG 2.05](https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-5), or directly in [metadata.go](https://github.com/eclipse-tractusx/tractusx-quality-checks/blob/main/pkg/product/metadata.go#L31)
Fixes #364
> chore: fix .tractusx metadata; add missing repositories key

- bpdm-bridge-dummy/src/main/kotlin/com/catenax/bpdm/bridge/dummy/service/SyncRecordService.kt
- bpdm-bridge-dummy/src/test/kotlin/com/catenax/bpdm/bridge/dummy/SyncStateIT.kt
- bpdm-bridge-dummy/src/test/kotlin/com/catenax/bpdm/bridge/dummy/util/DbTestHelpers.kt
- bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/model/BaseSyncRecord.kt
- bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/model/SyncStatus.kt
- bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/service/BaseSyncRecordService.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/SyncRecordService.kt
SyncStateIT tests if during a sync the bridge polls the Gate changelogs starting at the correct timestamp.
The SyncRecord and SyncRecordService is improved.
Fixes #212
> feat: Bridge tests for recorded sync state

- bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/config/OpenApiConfig.kt
title: '(feat): Added Client Credentials Flow to Swagger and Updated Role Configuration'
This PR introduces a new feature
It adds the Client Credentials Flow to the Swagger configuration to make possible new ways of authentication
- Check out our guide on [how to contribute](https://eclipse-tractusx.github.io/docs/oss/how-to-contribute)
- Check out our [Release Guidelines](https://eclipse-tractusx.github.io/docs/release)
- Check out the [Eclipse Foundation contribution …
> feat: Added Client Credentials Flow to Swagger and Updated Role Configuration

- .github/workflows/trivy.yml
- .github/workflows/veracode.yaml
- DEPENDENCIES
- pom.xml
In this pull request, update spring boot version and on veracode scan added bridge dummy jar.
This pull request is in draft state to check scan details and will update once we get expected results.
> fix: updated springboot version and veracode scan file

- bpdm-bridge-dummy/src/main/kotlin/com/catenax/bpdm/bridge/dummy/config/BridgeAuthProperties.kt
created class BridgeAuthProperties to validate sync authorities for bridge sync endpoint
Fixes #334
> fix(bridge): Sync Endpoint Auth Leads to 500

- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/controller/AddressController.kt
This pull request fixes a bug on invoking the authorised BPDM Gate PUT Address Output endpoint.  Basically, the Pre-Authorize annotation on the respective controller method was fault as it references a non-existing bean path. Fixed the path and the error is gone.
Fixes #373
Create a local configuration for the BPDM Gate with security enabled connecting to an openId server for token validation. Invoke the PUT Address Output endpoint with a valid token and a valid address business partner request. You should receive a 200 OK response. Before, performing these steps lead to a 500 response.
> Fix: Error on Invoking Authorised PUT Address Output Endpoint

- bpdm-bridge-dummy/src/main/kotlin/com/catenax/bpdm/bridge/dummy/service/GateQueryService.kt
- bpdm-bridge-dummy/src/test/kotlin/com/catenax/bpdm/bridge/dummy/SyncStateIT.kt
- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/ChangelogType.java
- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/response/ChangelogGateDto.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/controller/ChangelogController.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/ChangelogEntry.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/AddressPersistenceService.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/AddressService.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/LegalEntityPersistenceService.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/ResponseMappings.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/SitePersistenceService.kt
- bpdm-gate/src/main/resources/db/migration/V4_0_0_12__add_changelog_type.sql
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/ChangeLogControllerIT.kt
- bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/model/request/ChangelogSearchRequest.kt
- bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/model/response/ChangelogEntryVerboseDto.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/controller/ChangelogController.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/dto/ChangelogEntryCreateRequest.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/entity/PartnerChangelogEntry.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/BusinessPartnerBuildService.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/PartnerChangelogService.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/ResponseMappings.kt
- bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/controller/ChangelogControllerIT.kt
- docs/postman/BPDM Gate.postman_collection.json
- docs/postman/BPDM Pool.postman_collection.json
- Rename **fromTime** and **modifiedAt** in changelog reponse to **timestamp**
- Rename query parameter to **timestampAfter**
- For Gate add changelogType to entry & response to be consistent with Pool
- Make Gate changelog request parameters optional
Fixes #353
> Feat: API - Rename changelog timestamp

- bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/util/JpaMermaidCreator.kt
- bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/util/JpaMetaModelReader.kt
- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/GateDocumentationApi.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/controller/GateDocumentationController.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/controller/LegalEntityController.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/DocumentationService.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/LegalEntityService.kt
- bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/PoolDocumentationApi.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/controller/MetadataController.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/controller/PoolDocumentationController.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/GateDocumentationService.kt
Generate Mermaid Persistence Class Diagram from JPA metadata. Add temporary a Rest endpoint to gate and pool to test the generated diagram
Enums are depicted as attributes without reference to the UML Enum Class, Max 15 enum entries are displayed
Not Null Attributes are extended by [1]
@OneToMany elements are depicted as refrence 
@ManyToOne are displayed as attributes without reference. (Mostly they are back references)
Start gate and pool 
In the Browser (Chrome) call
http://localhost:8080/api/catena/mermaid/
http://localhost:8081/api/catena/mermaid/
Copy result in the mermaid live editor to see result: https://mermaid.live/edit 
Fixes #338 #339
> feat/doc: Generate Mermaid Persistence Class Diagram from JPA metadata

- CHANGELOG.md
In this pull request, updated ChangeLog markdown file for recent application version.
> fix(docs): updated changelog for app version

- DEPENDENCIES
- bpdm-bridge-dummy/pom.xml
- bpdm-common/pom.xml
- bpdm-gate/pom.xml
- bpdm-pool/pom.xml
- pom.xml
In this pull request, removed restricted dependency introduced  for spring-boot-configuration-processor library  in DEPENDENCIES list. 
This library does not need to go into the actual build so excluded the same.
Fixes #391
> fix(bpdm): removed restricted dependencies

- .github/workflows/trivy.yml
This pull request points Trivy image scan to the latest BPDM images on Dockerhub. Previously, Trivy only scanned the deprecated images of the repository, leading to old results.
> fix(trivy): image reference now points to BPDM dockerhub images

- INSTALL.md
- bpdm-bridge-dummy/pom.xml
- bpdm-gate/pom.xml
- bpdm-pool/pom.xml
In this pull request, added support to include LICENSE, NOTICE and DEPENDENCIES files in the META-INF directory of generated jars as per the  TRG 7.05. Also, added notice section to INSTALL.md as per the TRG 7.07.
> fix(bpdm): TRG quality gate issue

- charts/bpdm/Chart.yaml
- charts/bpdm/values.yaml
title description: '(fix): Remove Unused Datasource Environment Variable from Deployment'
The changes include disabling certain components (bpdm-pool, bpdm-bridge-dummy, opensearch) and updating the Postgres configuration to override the name of the Postgres deploy. The changes aim to streamline the deployment configuration and remove unnecessary elements.
fix # https://github.com/eclipse-tractusx/bpdm/issues/381
> feat(charts): Remove Unused Datasource Environment Variable from Deployment

- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/RequestValidationService.kt
- bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/controller/LegalEntityControllerIT.kt
- bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/util/CommonValues.kt
Added service validation when a request is made with identifier with the same values at the legal entity level.
Added unit test for testing the error return
issue: [#412](https://github.com/eclipse-tractusx/bpdm/issues/412)
> fix(Pool): Fix Duplicate Identifier Validation on New Business Partners

- bpdm-bridge-dummy/src/test/kotlin/com/catenax/bpdm/bridge/dummy/util/BpdmGateContextInitializer.kt
- bpdm-bridge-dummy/src/test/kotlin/com/catenax/bpdm/bridge/dummy/util/BpdmPoolContextInitializer.kt
- bpdm-bridge-dummy/src/test/kotlin/com/catenax/bpdm/bridge/dummy/util/OpenSearchContextInitializer.kt
- bpdm-gate/Dockerfile
- bpdm-pool/Dockerfile
Adjusted BpdmPoolContextInitializer / BpdmGateContextInitializer to enable remote-debugging in the containers. The external (localhost) debug port is managed by Docker and therefore dynamic. 
So there is a log message announcing the port to connect to.
Solves #410
> feat(tests): Remote-debugging the Testcontainers

- docs/decision-records/004-openapi_descriptions.md
ADR regarding limitations of OpenAPI text descriptions.
This explains the problems encountered, possible workarounds and the decision taken.
See #409
> feat(ADR): ADR regarding limitations of OpenAPI text descriptions

- README.md
- bpdm-cleaning-service-dummy/DOCKER_NOTICE.md
- bpdm-cleaning-service-dummy/Dockerfile
- bpdm-cleaning-service-dummy/pom.xml
- bpdm-cleaning-service-dummy/src/main/kotlin/org/eclipse/tractusx/bpdm/cleaning/Application.kt
- bpdm-cleaning-service-dummy/src/main/resources/application.properties
- bpdm-cleaning-service-dummy/src/test/kotlin/org/eclipse/tractusx/bpdm/cleaning/ApplicationTests.kt
- pom.xml
Create maven module for the Cleaning Service Dummy.
I used org.eclipse.tractusx.bpdm.cleaning as base package name because org.eclipse.tractusx.bpdm.cleaning-service-dummy seems a little bit long.
At the moment no persistence to a database is configured.
#421
> Feat: Setup new Maven Module for CleaningServiceDummy

- bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/dto/AlternativePostalAddressDto.kt
- bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/service/CommonMappings.kt
- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/GateBusinessPartnerApi.kt
- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/client/GateClient.kt
- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/client/GateClientImpl.kt
- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/BusinessPartnerIdentifierDto.kt
- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/PhysicalPostalAddressGateDto.kt
- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/request/BusinessPartnerInputRequest.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/controller/BusinessPartnerController.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/repository/generic/BusinessPartnerRepository.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/BusinessPartnerMappings.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/BusinessPartnerService.kt
This implements the logic for persisting generic business partners and querying for existing BPs (stage input and output). This involves mapping between DTO and entity model. Some small changes to the DTO model were needed.
Solves #456
> Feat: Implement generic business partner service logic in Gate

- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/generic/BusinessPartner.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/generic/PostalAddress.kt
- bpdm-gate/src/main/resources/db/migration/V4_0_0_14__generic_data_model_changes.sql
Changes to entity model (including DB migration):
- Make BusinessPartner.isOwner mandatory
- Rename DB fields for BusinessPartner.bpnL/bpnS/bpnA
- Make PostalAddress.addressType optional
Fixes for #428
> Fix: Generic business partner entity fields in Gate

- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/BusinessPartnerMappings.kt
This pull request fixes a bug in which an incorrect mapping between generic business partner entity and its output DTO leads to nullable/non-nullable type mismatch breaking the build of the Gate.
The culprit is the addressType field in the PostalAddress which is nullable in the entity and non-nullable in the output DTO. Since we always map from the output stage of entity to the output DTO we can expect the entity to have a non-null address type. Therefore, I casted the addressType field to non-null when assigning it to its output DTO counterpart.
Compile the BPDM Gate module and it should succeed without any errors.
Fixes #465
> Fix: Mapping AddressType from Generic entity to Output DTO in Gate

- bpdm-orchestrator/pom.xml
Currently the orchestrator module breaks the build as the referenced parent pom version is outdated. The current version 4.1.0-SNAPSHOT was shortly introduced and took over the old 4.0.2-SNAPSHOT version.
I fixed the build again by setting the correct version 4.1.0-SNAPSHOT  for the orchestrator's parent pom.
> Fix: Orchestrator Parent Pom Version

- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/IBaseBusinessPartnerDto.kt
- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/request/BusinessPartnerInputRequest.kt
- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/response/BusinessPartnerInputDto.kt
- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/response/BusinessPartnerOutputDto.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/BusinessPartnerMappings.kt
Small improvements to the DTO model:
- optional BPN fields are added for input
- named bpnL/S/A instead of bpnl/s/a
- fixed assigment for isOwner, addressType after changes to optional/mandatory
- improved OpenAPI description (clarified sorting and de-duping behaviour)
Solves #384
> feat: Adjustments to Generic Business Partner model

- bpdm-bridge-dummy/src/main/kotlin/com/catenax/bpdm/bridge/dummy/service/GateQueryService.kt
- bpdm-bridge-dummy/src/main/kotlin/com/catenax/bpdm/bridge/dummy/service/GateUpdateService.kt
- bpdm-bridge-dummy/src/main/kotlin/com/catenax/bpdm/bridge/dummy/service/PoolUpdateService.kt
- bpdm-bridge-dummy/src/test/kotlin/com/catenax/bpdm/bridge/dummy/BridgeSyncIT.kt
- bpdm-bridge-dummy/src/test/kotlin/com/catenax/bpdm/bridge/dummy/util/TestHelpers.kt
- bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/service/ParameterObjectArgumentResolver.kt
- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/client/GateClient.kt
- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/client/GateClientImpl.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/ChangeLogControllerIT.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/LegalEntityControllerInputIT.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/LegalEntityControllerOutputIT.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/PostalAddressControllerInputIT.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/PostalAddressControllerOutputIT.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/SharingStateControllerIT.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/SiteControllerInputIT.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/SiteControllerOutputIT.kt
- bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/client/PoolApiClient.kt
- bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/client/PoolClientImpl.kt
- bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/component/opensearch/InvalidIndexStartupIT.kt
- bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/component/opensearch/ValidIndexStartupIT.kt
- bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/component/opensearch/controller/OpenSearchControllerIT.kt
- bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/controller/AddressControllerIT.kt
- bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/controller/AddressControllerSearchIT.kt
- bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/controller/BpnControllerIT.kt
- bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/controller/ChangelogControllerIT.kt
- bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/controller/LegalEntityControllerIT.kt
- bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/controller/LegalEntityControllerSearchIT.kt
- bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/controller/MetadataControllerIT.kt
- bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/controller/SiteControllerIT.kt
- bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/util/TestHelpers.kt
Directly expose lazy properties, not functions, for the different APIs.
This is more straight-forward in Kotlin and simplifies the API client implementations.
> Refactor: Simplify Gate/Pool API clients

- docs/arc42/diagrams/create_legal_entity_diagram.md
- docs/arc42/diagrams/search_legal_entity_diagram.md
- docs/arc42/diagrams/update_legal_entity_diagram.md
Create mermaid sequence diagrams showing the different services/components of the BPDM Pool and how they interact each other on these use cases:
- Create legal entity
- Update legal entity
- Search legal entity
https://github.com/eclipse-tractusx/bpdm/issues/472
> Docs: Add diagrams for pool components

- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/util/RequestValues.kt
Currently the tests on the Gate break because some test values used are referencing incorrect DTO types (BusinessPartnerPostalAddressInputDto instead of BusinessPartnerPostalAddressDto).
I fixed the bug by providing address test values of the expected type with equivalent values.
> Fix: Gate tests referencing incorrect address DTO types

- bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/dto/IBaseBusinessPartnerDto.kt
- bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/exception/BpdmUpsertLimitException.kt
- bpdm-orchestrator-api/pom.xml
- bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/CleaningTaskApi.kt
- bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/client/OrchestrationApiClient.kt
- bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/client/OrchestrationApiClientImpl.kt
- bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/model/AlternativePostalAddressDto.kt
- bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/model/BusinessPartnerDto.kt
- bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/model/CleaningStep.kt
- bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/model/PhysicalPostalAddressDto.kt
- bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/model/PostalAddressDto.kt
- bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/model/ReservationState.kt
- bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/model/ResultState.kt
- bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/model/StreetDto.kt
- bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/model/TaskCreateRequest.kt
- bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/model/TaskCreateResponse.kt
- bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/model/TaskError.kt
- bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/model/TaskErrorType.kt
- bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/model/TaskMode.kt
- bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/model/TaskProcessingStateDto.kt
- bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/model/TaskRequesterState.kt
- bpdm-orchestrator/pom.xml
- bpdm-orchestrator/src/main/kotlin/org/eclipse/tractusx/bpdm/orchestrator/Application.kt
- bpdm-orchestrator/src/main/kotlin/org/eclipse/tractusx/bpdm/orchestrator/config/ApiConfigProperties.kt
- bpdm-orchestrator/src/main/kotlin/org/eclipse/tractusx/bpdm/orchestrator/controller/CleaningTaskController.kt
- bpdm-orchestrator/src/test/kotlin/org/eclipse/tractusx/bpdm/orchestrator/config/OrchestratorClientConfig.kt
- bpdm-orchestrator/src/test/kotlin/org/eclipse/tractusx/bpdm/orchestrator/controller/CleaningTaskControllerIT.kt
- bpdm-orchestrator/src/test/kotlin/org/eclipse/tractusx/bpdm/orchestrator/util/TestValues.kt
- bpdm-orchestrator/src/test/resources/application-test.properties
- pom.xml
This pull request adds the first endpoint to the orchestrator API and implements a dummy return value for that endpoint. 
As always the endpoint comes with client functionality which is validated through tests.
The DTO model for the endpoint is based on the BusinessPartner interfaces in the common module, by this connecting it to the other API models while still having its own DTO implementations.
This pull request solves issue #425 
> Feat: Add Orchestrator API Endpoint for Requesting Cleaning Tasks

- bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/CleaningTaskApi.kt
- bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/model/TaskStateRequest.kt
- bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/model/TaskStateResponse.kt
- bpdm-orchestrator/src/main/kotlin/org/eclipse/tractusx/bpdm/orchestrator/controller/CleaningTaskController.kt
- bpdm-orchestrator/src/test/kotlin/org/eclipse/tractusx/bpdm/orchestrator/controller/CleaningTaskControllerIT.kt
Introduced a new endpoint in the CleaningTaskApi interface for querying the state of finished cleaning tasks by task identifiers. The endpoint is defined as a POST request to /cleaning-tasks/state/search.
Implemented the above endpoint in the CleaningTaskController class. 
Currently, it returns dummy data as a placeholder.
Created a unit test for the CleaningTaskController to verify that the new endpoint is reachable and returns the expected dummy data.
This pull request solves issue (https://github.com/eclipse-tractusx/bpdm/issues/426)
> Feat(Orchestrator): Add taskId search Api

- bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/CleaningTaskApi.kt
- bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/model/TaskStateRequest.kt
- bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/model/TaskStateResponse.kt
- Use constant for Swagger-Tag
- Remove duplicate path segment in /api/cleaning-tasks/cleaning-tasks/state/search
- Improve field name in TaskStateRequest
- Improve schema description
> fix: Small improvements and fix of inconsistencies in CleaningTaskApi

- bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/CleaningTaskApi.kt
- bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/model/CleaningResultEntry.kt
- bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/model/CleaningResultRequest.kt
- bpdm-orchestrator/src/main/kotlin/org/eclipse/tractusx/bpdm/orchestrator/controller/CleaningTaskController.kt
- bpdm-orchestrator/src/main/kotlin/org/eclipse/tractusx/bpdm/orchestrator/exception/BpdmEmptyResultException.kt
- bpdm-orchestrator/src/test/kotlin/org/eclipse/tractusx/bpdm/orchestrator/controller/CleaningTaskControllerIT.kt
- bpdm-orchestrator/src/test/kotlin/org/eclipse/tractusx/bpdm/orchestrator/util/BusinessPartnerTestValues.kt
This pull request introduces an endpoint to post cleaning results for previously reserved cleaning tasks to the orchestrator. The API endpoint is implemented in the orchestrator controller and returns dummy data on invocation.
I also added tests checking the upsert limit and whether the endpoint can be invoked.
For the necessary test I created template objects for L/S/A business partners that can be used by the tests.
Solves issue #458
> Feat: Add Endpoint for Posting Cleaning Results to Orchestrator

- bpdm-bridge-dummy/src/main/kotlin/com/catenax/bpdm/bridge/dummy/service/GateQueryService.kt
- bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/dto/IBaseBusinessPartnerDto.kt
- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/request/BusinessPartnerInputRequest.kt
- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/request/BusinessPartnerOutputRequest.kt
- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/response/ChangelogGateDto.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/ChangelogEntry.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/generic/BusinessPartner.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/BusinessPartnerMappings.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/BusinessPartnerService.kt
- bpdm-gate/src/main/resources/db/migration/V4_0_0_16__add_parent_type-generic.sql
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/entity/generic/BusinessPartnerIT.kt
Added Parent references for Generic related to LSA Type and Changelog Type rework
New fields we're added in the Generic Business Partner (ParentID and ParentType) in order to be backwards compatible with the BPDM Gate's L/S/A endpoints. Logic for relationship verification in Sites and Addresses was added.
Changelogs creation was altered, and now businessPartnerType is optional. Mapping of Address Type to Business Partner Type was done as well.
New service for Generic Output persistence was created.
Related issues #490 and #489 
> Feat (Gate) - Added Parent references for Generic related to LSA Type and Changelog Type rework

- bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/service/CommonMappings.kt
- bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/PoolMetadataApi.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/controller/MetadataController.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/repository/RegionRepository.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/MetadataService.kt
- bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/controller/MetadataControllerIT.kt
- bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/util/TestHelpers.kt
Create api/catena/administrative-areas-level1 (GET) endpoint as replacement for the confusingly named api/catena/regions (GET and POST) endpoints. The later two endpoints are marked as deprectated in OpenAPI.
The endpoint sorts the returned regions by `countryCode` and `regionCode`.
Solves #499
> Feat: Create administrative areas level 1 endpoint

- charts/bpdm/Chart.yaml
- charts/bpdm/charts/bpdm-bridge-dummy/Chart.yaml
- charts/bpdm/charts/bpdm-cleaning-service-dummy/Chart.yaml
- charts/bpdm/charts/bpdm-gate/Chart.yaml
- charts/bpdm/charts/bpdm-pool/Chart.yaml
This pull request increases the supported BPDM app version for the BDPM charts to 4.1.0-alpha.2
> Feat: Increase BPDM Charts app version 4.1.0-alpha.2

- .github/workflows/trivy.yml
Add Model Orchestrator Service to trivy scan
https://github.com/eclipse-tractusx/bpdm/issues/422
> CICD: Add Orchestrator service to trivy.yml

- bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/dto/AddressType.kt
- bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/util/CollectionUtils.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/PhysicalPostalAddress.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/generic/BusinessPartner.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/generic/Classification.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/generic/State.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/exception/BpdmMissingStageException.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/BusinessPartnerMappings.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/BusinessPartnerService.kt
This pull request is a proposal on how services employ business logic to DTOs and entities. Currently, often a service takes a DTO and employs business logic on it, especially in the case of updates or inserts. The problem here is that a lot of this business logic can not be reused and need to be duplicated if a new DTO is introduced to the service. 
There is the option to convert from DTO to DTO but this establishes more dependencies between the DTOs as well as dependency between service and the DTO which should actually abstract from the model. Instead, I propose for the services to use the actual model classes as early as possible. Only applying logic for DTO-specific validation before converting the DTO to its model representation and then employ the business logic from there.
In the …
>  refactor(gate): business partner service

- bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/dto/response/CountrySubdivisionDto.kt
- bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/PoolMetadataApi.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/controller/MetadataController.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/MetadataService.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/ResponseMappings.kt
- bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/controller/MetadataControllerIT.kt
For endpoint and DTOs rephrase *region* to *administrativeAreaLevel1* and *country subdivision* because region is not an official term according to ISO 3166-2.
Solves #499
> Feat: Administrative Level 1 endpoint - don't call it "region" in descriptions and properties

- charts/bpdm/Chart.yaml
- charts/bpdm/charts/bpdm-bridge-dummy/Chart.yaml
- charts/bpdm/charts/bpdm-cleaning-service-dummy/Chart.yaml
- charts/bpdm/charts/bpdm-gate/Chart.yaml
- charts/bpdm/charts/bpdm-pool/Chart.yaml
Increases the BPDM Helm Chart app version to 4.1.0-alpha.3
>  Feat: increase BPDM Charts to appversion 4.1.0-alpha.3

- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/response/SharingStateDto.kt
- bpdm-gate/pom.xml
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/config/OrchestratorClientConfig.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/config/OrchestratorConfigProperties.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/SharingState.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/BusinessPartnerMappings.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/BusinessPartnerService.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/OrchestratorMappings.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/SharingStateService.kt
- bpdm-gate/src/main/resources/application.properties
- bpdm-gate/src/main/resources/db/migration/V4_0_0_17__add_cleaning_task_id_sharing_states.sql
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/BusinessPartnerControllerIT.kt
Request Cleaning for Own Business Partner Update,Persist cleaning task identifier and associate with business partner in the SharingStateDto and update sharing state of business partner to Pending
solves #429
> Feat: Request Cleaning for Own Business Partner Update In Gate

- bpdm-cleaning-service-dummy/src/main/kotlin/org/eclipse/tractusx/bpdm/cleaning/service/CleaningServiceDummy.kt
- bpdm-cleaning-service-dummy/src/test/kotlin/org/eclipse/tractusx/bpdm/cleaning/service/CleaningServiceApiCallsTest.kt
- bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/GoldenRecordTaskApi.kt
- bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/model/TaskStepResultRequest.kt
- bpdm-orchestrator/src/main/kotlin/org/eclipse/tractusx/bpdm/orchestrator/service/GoldenRecordTaskService.kt
- bpdm-orchestrator/src/main/kotlin/org/eclipse/tractusx/bpdm/orchestrator/service/GoldenRecordTaskStateMachine.kt
- bpdm-orchestrator/src/test/kotlin/org/eclipse/tractusx/bpdm/orchestrator/controller/GoldenRecordTaskControllerIT.kt
- bpdm-orchestrator/src/test/kotlin/org/eclipse/tractusx/bpdm/orchestrator/service/GoldenRecordTaskStateMachineIT.kt
When posting task results (`POST /api/golden-record-tasks/step-results`) the request DTO now requires a `step` enum.
This is a precondition for authorization because permission should be checked based on step-based roles.
Relates to #534
> feat: Extend TaskStepResultRequest in orchestrator-api with step

- bpdm-orchestrator/src/main/kotlin/org/eclipse/tractusx/bpdm/orchestrator/config/BpdmSecurityConfigurerAdapterImpl.kt
- bpdm-orchestrator/src/main/kotlin/org/eclipse/tractusx/bpdm/orchestrator/config/OrchestratorConfigProperties.kt
- bpdm-orchestrator/src/main/kotlin/org/eclipse/tractusx/bpdm/orchestrator/controller/GoldenRecordTaskController.kt
- bpdm-orchestrator/src/main/resources/application-auth.properties
Spring profile `auth` enables authentication/authorization.
The endpoints in `GoldenRecordTaskController` then require the following permissions:
- `createTasks()` requires role "create_task"
- `searchTaskStates()` requires role "view_task"
- `reserveTasksForStep()` and `resolveStepResults()` require a step-specific role, e.g. for `CleanAndSync` the role "process_task_step_CleanAndSync" is required
> feat: Add authentication and authorization to Orchestrator

- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/Application.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/repository/SharingStateRepository.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/BusinessPartnerService.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/OrchestratorMappings.kt
- bpdm-gate/src/main/resources/application.properties
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/BusinessPartnerControllerIT.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/util/BusinessPartnerGenericValues.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/util/BusinessPartnerNonVerboseValues.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/util/BusinessPartnerVerboseValues.kt
- bpdm-orchestrator/src/main/kotlin/org/eclipse/tractusx/bpdm/orchestrator/controller/GoldenRecordTaskController.kt
In this PR, the BPDM Gate can poll the BPDM Orchestrator whether there is already a final cleaning result for the respective cleaning task. When a new cleaning result for a finished cleaning task has been returned by the Orchestrator the Gate then saves the cleaning result as a generic business partner output, resolves the task identifier and updates the sharing state of the respective business partner. Also, some Unit tests have been added.
Related to #430 
> Feat (Gate) - Resolve Finished Cleaning Task

- .github/workflows/build-docker-all.yaml
- .github/workflows/helm-chart-lint.yaml
- charts/bpdm/Chart.yaml
- charts/bpdm/charts/bpdm-orchestrator/.helmignore
- charts/bpdm/charts/bpdm-orchestrator/CHANGELOG.md
- charts/bpdm/charts/bpdm-orchestrator/Chart.yaml
- charts/bpdm/charts/bpdm-orchestrator/LICENSE
- charts/bpdm/charts/bpdm-orchestrator/README.md
- charts/bpdm/charts/bpdm-orchestrator/templates/NOTES.txt
- charts/bpdm/charts/bpdm-orchestrator/templates/_helpers.tpl
- charts/bpdm/charts/bpdm-orchestrator/templates/configMap.yaml
- charts/bpdm/charts/bpdm-orchestrator/templates/deployment.yaml
- charts/bpdm/charts/bpdm-orchestrator/templates/ingress.yaml
- charts/bpdm/charts/bpdm-orchestrator/templates/secret.yaml
- charts/bpdm/charts/bpdm-orchestrator/templates/service.yaml
- charts/bpdm/charts/bpdm-orchestrator/values.yaml
- charts/bpdm/values.yaml
We added a new helm chart to the existing structure to be able to deploy the new Orchestrator service module.
issue: https://github.com/eclipse-tractusx/bpdm/issues/461
> Feat: Add Orchestrator Helm chart to the existing BPDM Charts

- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/BpnIssuingService.kt
Fixes the BPN issuers behaviour of creating and returning always one too many BPNs
> Fix(Pool): Number of BPNs issued on Request

- bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/dto/AddressStateDto.kt
- bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/dto/ClassificationDto.kt
- bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/dto/IBaseLegalEntityDto.kt
- bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/dto/LegalEntityDto.kt
- bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/dto/LegalEntityIdentifierDto.kt
- bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/dto/LegalEntityStateDto.kt
- bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/dto/LogisticAddressDto.kt
- bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/dto/SiteStateDto.kt
- bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/model/LegalEntityDto.kt
- bpdm-pool/pom.xml
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/component/opensearch/impl/service/OpenSearchSyncStarterService.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/config/OrchestratorClientConfig.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/config/OrchestratorClientConfigProperties.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/exception/BpdmValidationException.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/BusinessPartnerBuildService.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/MetadataService.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/RequestValidationService.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/TaskStepBuildService.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/TaskStepFetchAndReserveService.kt
- bpdm-pool/src/main/resources/application.properties
- bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/service/TaskStepFetchAndReserveServiceTest.kt
upsert L/S/A Entities from task steps into pool database
Implements #432  partly
Validation of the legal entities, sites and addresses
Persist mapping of mapping 'BPN request identifier' to 'BPN' and use it in the next maping
Add Tests
> Feat(pool): Upsert Business Partners from Cleaning Result

- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/entity/BpnRequestIdentifierMapping.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/repository/BpnRequestIdentifierRepository.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/TaskEntryBpnMapping.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/TaskStepBuildService.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/TaskStepFetchAndReserveService.kt
- bpdm-pool/src/main/resources/db/migration/V4_1_0_0__bpn_mapping.sql
- bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/service/TaskStepFetchAndReserveServiceTest.kt
mapping between request indentifiers and bpn
Implements #432  partly
Validation of the legal entities, sites and addresses
Add Tests
> Feat(pool): Request indentifier mapping for Upserted Business Partners

- DEPENDENCIES
- pom.xml
Upgrade parent pom spring version to 3.1.4
https://github.com/eclipse-tractusx/bpdm/issues/532
> Fix: Upgrade parent pom 

- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/controller/BusinessPartnerController.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/exception/BpdmInvalidStateRequestException.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/repository/SharingStateRepository.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/AddressPersistenceService.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/BusinessPartnerService.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/LegalEntityPersistenceService.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/SharingStateService.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/SitePersistenceService.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/BusinessPartnerControllerIT.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/SharingStateControllerIT.kt
Currently, the sharing state service is somewhat of a glorified repository. It just takes a DTO, maps it to the entity and saves whatever is inside. This means the logic of managing sharing state transitions is left to the invoking services.
The goal of this pull request is to move such sharing state transition logic to the sharing state, by this capsulating responsibitilies between the services better.
In addition I added some validation logic for transitioning to shring states making sure essential information for that state is given. At the same time, information that is irrelevant for the transitioned sharing state is being ignored (such as error information for any other state than Error).
Please ensure to do as many of the following checks as possible, before asking for committer …
> Feat: Move Sharing State Transition Logic to the Sharing State Service

- charts/bpdm/Chart.yaml
- charts/bpdm/charts/bpdm-orchestrator/Chart.yaml
- charts/bpdm/charts/bpdm-orchestrator/templates/ingress.yaml
Orchestrator ingress yaml was with failed identation
> Fix: Correct Chart Ingress Identation

- charts/bpdm/Chart.yaml
- charts/bpdm/charts/bpdm-bridge-dummy/Chart.yaml
- charts/bpdm/charts/bpdm-bridge-dummy/templates/deployment.yaml
- charts/bpdm/charts/bpdm-cleaning-service-dummy/Chart.yaml
- charts/bpdm/charts/bpdm-cleaning-service-dummy/templates/deployment.yaml
- charts/bpdm/charts/bpdm-gate/Chart.yaml
- charts/bpdm/charts/bpdm-gate/templates/deployment.yaml
- charts/bpdm/charts/bpdm-orchestrator/Chart.yaml
- charts/bpdm/charts/bpdm-orchestrator/templates/deployment.yaml
- charts/bpdm/charts/bpdm-pool/Chart.yaml
- charts/bpdm/charts/bpdm-pool/templates/deployment.yaml
Add configmap hash to deployment yamls so it can be reloaded when the configmap changes
> Feat: Add configmap Hash reload

- bpdm-bridge-dummy/Dockerfile
- bpdm-cleaning-service-dummy/Dockerfile
- bpdm-gate/Dockerfile
- bpdm-orchestrator/Dockerfile
- bpdm-pool/Dockerfile
Add health check on docker image for fixing trivy findings
> Fix: Add Health check on docker images

- bpdm-cleaning-service-dummy/src/main/kotlin/org/eclipse/tractusx/bpdm/cleaning/service/GenericBusinessPartnerMappings.kt
- bpdm-cleaning-service-dummy/src/test/kotlin/org/eclipse/tractusx/bpdm/cleaning/testdata/CommonValues.kt
- bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/dto/BusinessPartnerIdentifierDto.kt
- bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/dto/BusinessPartnerStateDto.kt
- bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/dto/ClassificationBusinessPartnerDto.kt
- bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/dto/IBaseBusinessPartnerDto.kt
- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/request/BusinessPartnerInputRequest.kt
- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/response/BusinessPartnerInputDto.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/BusinessPartnerMappings.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/OrchestratorMappings.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/BusinessPartnerControllerIT.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/util/BusinessPartnerVerboseValues.kt
- bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/model/LegalEntityDto.kt
- bpdm-orchestrator/src/test/kotlin/org/eclipse/tractusx/bpdm/orchestrator/testdata/BusinessPartnerTestValues.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/BusinessPartnerBuildService.kt
Some fields on the DTO's for upserting a Business Partner have been altered to only require an External-ID for creating an new 
Business Partner. All other fields are optional. (Duplicate of #523 PR)
Related issues: #476
> feat(Gate) - Allow user to input nullable values

- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/controller/AddressController.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/controller/BusinessPartnerController.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/controller/LegalEntityController.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/controller/SiteController.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/util/Extensions.kt
Moved the Extensions class in the BPDM Gate to a subpackage. This should be more in line with our project structure requirements.
> refactor(Gate): move Extensions.kt to a util package

- charts/bpdm/Chart.yaml
- charts/bpdm/charts/bpdm-bridge-dummy/Chart.yaml
- charts/bpdm/charts/bpdm-cleaning-service-dummy/Chart.yaml
- charts/bpdm/charts/bpdm-gate/Chart.yaml
- charts/bpdm/charts/bpdm-orchestrator/Chart.yaml
- charts/bpdm/charts/bpdm-pool/Chart.yaml
This pull request updats the BPDM chart to support BPDM app version 4.1.0-alpha.4
> feat(Charts): increase app version to 4.1.0-alpha.4

- .github/workflows/build-docker.yaml
- .github/workflows/trivy.yml
A new Latest-Alpha tag will be released when a push to main is done
It can be checked in this registry https://hub.docker.com/u/tractusx
It will be used for trivy scan 
Issue fix for: https://github.com/eclipse-tractusx/bpdm/issues/561 https://github.com/eclipse-tractusx/bpdm/issues/560
> feat(Workflows): Add latest-alpha tag and use it for trivy.yml

- .github/workflows/build-docker.yaml
A new Latest-Alpha tag will be released when a push to main is done
It can be checked in this registry https://hub.docker.com/u/tractusx
It will be used for trivy scan 
Issue fix for:  https://github.com/eclipse-tractusx/bpdm/issues/560
> Fix: Add latest-alpha tag and use it for trivy.yml

- DEPENDENCIES
- pom.xml
This pull requests updates the Spring Boot Start parent version to 3.1.5. By this, a lot of dependencies used in the BPDM application are updated as well.
> feat(App): update to Spring Boot Parent 3.1.5

- bpdm-cleaning-service-dummy/src/main/kotlin/org/eclipse/tractusx/bpdm/cleaning/config/ClientsConfig.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/config/OrchestratorClientConfig.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/config/OrchestratorConfigProperties.kt
- Added client configuration to have authentication when connecting to orchestrator Apis.
- This should handle for both auth and no auth options
- Fixed some wrong naming on props for cleaning module regarding auth
[](https://github.com/eclipse-tractusx/bpdm/issues/582)
> Feat: Add Authentication connection to Orchestrator

- bpdm-cleaning-service-dummy/src/main/kotlin/org/eclipse/tractusx/bpdm/cleaning/service/CleaningServiceDummy.kt
- bpdm-cleaning-service-dummy/src/test/kotlin/org/eclipse/tractusx/bpdm/cleaning/service/CleaningServiceDummyTest.kt
- bpdm-cleaning-service-dummy/src/test/kotlin/org/eclipse/tractusx/bpdm/cleaning/testdata/CommonValues.kt
- bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/dto/IBaseBusinessPartnerDto.kt
- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/request/BusinessPartnerInputRequest.kt
- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/request/BusinessPartnerOutputRequest.kt
- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/response/BusinessPartnerInputDto.kt
- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/response/BusinessPartnerOutputDto.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/BusinessPartnerMappings.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/OrchestratorMappings.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/BusinessPartnerControllerIT.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/util/BusinessPartnerGenericValues.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/util/BusinessPartnerVerboseValues.kt
- bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/model/BusinessPartnerGenericDto.kt
- bpdm-orchestrator/src/test/kotlin/org/eclipse/tractusx/bpdm/orchestrator/controller/GoldenRecordTaskControllerIT.kt
- bpdm-orchestrator/src/test/kotlin/org/eclipse/tractusx/bpdm/orchestrator/testdata/BusinessPartnerTestValues.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/TaskStepBuildService.kt
- bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/service/TaskStepFetchAndReserveServiceTest.kt
This pull request aligns with the specification of the Generic Business Partner model for BPN fields: #382.  I renamed the generic business partner's BPN fields in order to better represent their meaning, as explained in the linked issue. 
I changed the code of the API but left entities unchanged.
Fixes #594 
> fix(Generic): naming of BPN fields in generic business partner

- bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/dto/AlternativePostalAddressDto.kt
- bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/dto/IBaseAlternativePostalAddressDto.kt
- bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/dto/IBasePhysicalPostalAddressDto.kt
- bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/dto/IBaseSiteDto.kt
- bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/dto/PhysicalPostalAddressDto.kt
- bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/dto/RequestWithKey.kt
- bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/dto/response/AlternativePostalAddressVerboseDto.kt
- bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/dto/response/PhysicalPostalAddressVerboseDto.kt
- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/AlternativePostalAddressGateDto.kt
- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/PhysicalPostalAddressGateDto.kt
- bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/model/AlternativePostalAddressDto.kt
- bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/model/PhysicalPostalAddressDto.kt
- bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/model/SiteDto.kt
- bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/model/TaskStepReservationEntryDto.kt
- bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/model/request/AddressPartnerCreateRequest.kt
- bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/model/request/AddressPartnerUpdateRequest.kt
- bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/model/request/LegalEntityPartnerCreateRequest.kt
- bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/model/request/LegalEntityPartnerUpdateRequest.kt
- bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/model/request/SitePartnerCreateRequest.kt
- bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/model/request/SitePartnerUpdateRequest.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/BusinessPartnerBuildService.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/MetadataService.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/RequestValidationService.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/TaskStepBuildService.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/TaskStepFetchAndReserveService.kt
Refactor code to reuse the logic to convert dtos to entities. Add some abstrct methods to Interfaces to suport this.
Solves issue #556 partly
> feat(pool): #556 Upsert Business Partners from Cleaning Result - refactoring

- bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/PoolLegalEntityApi.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/controller/LegalEntityController.kt
- bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/controller/LegalEntityControllerIT.kt
Change of name in the endpoint method /api/catena/legal-entities/search method was named searchSites when it is intended to find legal entities.
Refactor usage on UnitTest and Controller calls 
> Refactor(Pool): Fix controller naming

- charts/bpdm/Chart.yaml
- charts/bpdm/charts/bpdm-cleaning-service-dummy/Chart.yaml
- charts/bpdm/charts/bpdm-cleaning-service-dummy/README.md
- charts/bpdm/charts/bpdm-cleaning-service-dummy/templates/_helpers.tpl
- charts/bpdm/charts/bpdm-cleaning-service-dummy/templates/configMap.yaml
- charts/bpdm/charts/bpdm-cleaning-service-dummy/templates/deployment.yaml
- charts/bpdm/charts/bpdm-cleaning-service-dummy/templates/secret.yaml
- charts/bpdm/charts/bpdm-cleaning-service-dummy/templates/service.yaml
- charts/bpdm/charts/bpdm-cleaning-service-dummy/values.yaml
- charts/bpdm/charts/bpdm-orchestrator/Chart.yaml
- charts/bpdm/charts/bpdm-orchestrator/templates/_helpers.tpl
- charts/bpdm/charts/bpdm-orchestrator/templates/configMap.yaml
- charts/bpdm/charts/bpdm-orchestrator/templates/deployment.yaml
- charts/bpdm/charts/bpdm-orchestrator/templates/secret.yaml
- charts/bpdm/charts/bpdm-orchestrator/templates/service.yaml
- charts/bpdm/charts/bpdm-orchestrator/values.yaml
Fixed trivy finding for https://avd.aquasec.com/misconfig/kubernetes/general/avd-ksv-0104/
Artifact: charts/bpdm/charts/bpdm-orchestrator/templates/deployment.yaml
Type: helm
Vulnerability KSV104
Severity: MEDIUM
Message: container bpdm-orchestrator of deployment bpdm-orchestrator in default namespace should specify a seccomp profile
Link: [KSV104](https://avd.aquasec.com/misconfig/ksv104)
This was happening on both cleaning and orchestrator deployment
https://github.com/eclipse-tractusx/bpdm/issues/599
> fix(Charts): Fix trivy scan on chart orchestrator

- docs/api/bridge-dummy.json
- docs/api/gate.json
- docs/api/orchestrator.json
- docs/api/pool.json
Reintroduce OpenApi descriptions for the BPDM applications in JSON format as they are being referenced by the BPDM standard documents.
Just automatically converted the Yaml documents to Json, no new content.
> Docs(Api): add OpenAPI descriptions for BPDM applications in JSON format

- DEPENDENCIES
- INSTALL.md
- README.md
- charts/bpdm/Chart.yaml
- charts/bpdm/charts/bpdm-cleaning-service-dummy/Chart.yaml
- charts/bpdm/charts/bpdm-cleaning-service-dummy/README.md
- docs/postman/BPDM Orchestrator.postman_collection.json
- docs/postman/Local.postman_environment.json
In this pull request, update documentation for BPDM which is needed for quality gate 4
> Docs: bpdm document update for QG4 23.12

- CHANGELOG.md
- DEPENDENCIES
- bpdm-bridge-dummy/Dockerfile
- bpdm-cleaning-service-dummy/Dockerfile
- bpdm-gate/Dockerfile
- bpdm-orchestrator/Dockerfile
- bpdm-pool/Dockerfile
- pom.xml
Dependency update in pom.xml to fix vulnerabilities detected in the Trivy scan.
https://github.com/catenax-ng/tx-bpdm/security/code-scanning/4377
Update of DockerFile to fix vulnerabilities detected in the Trivy scan.
https://avd.aquasec.com/nvd/2023/cve-2023-5678/
https://github.com/eclipse-tractusx/bpdm/issues/624
> Fix trivy findings

- bpdm-bridge-dummy/src/main/kotlin/com/catenax/bpdm/bridge/dummy/config/BpdmSecurityConfigurerAdapterImpl.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/config/BpdmSecurityConfigurerAdapterImpl.kt
- bpdm-orchestrator/src/main/kotlin/org/eclipse/tractusx/bpdm/orchestrator/config/BpdmSecurityConfigurerAdapterImpl.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/config/BpdmSecurityConfigurerAdapterImpl.kt
Adapt `BpdmSecurityConfigurerAdapter` configuration for each module to the new Spring version, there some of the old methods where deprecated.
Solves #600
> fix: Adapt Spring Security configuration to new Spring version

- bpdm-bridge-dummy/src/main/kotlin/com/catenax/bpdm/bridge/dummy/controller/BridgeController.kt
- bpdm-bridge-dummy/src/main/kotlin/com/catenax/bpdm/bridge/dummy/service/GateUpdateService.kt
- bpdm-bridge-dummy/src/test/kotlin/com/catenax/bpdm/bridge/dummy/BridgeSyncIT.kt
- bpdm-cleaning-service-dummy/src/test/kotlin/org/eclipse/tractusx/bpdm/cleaning/testdata/CommonValues.kt
- bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/dto/LegalEntityIdentifierDto.kt
- bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/service/DataClassUnwrappedJsonDeserializer.kt
- bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/service/ParameterObjectArgumentResolver.kt
- bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/util/JpaMermaidCreator.kt
- bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/util/JpaMetaModelReader.kt
- bpdm-common/src/test/kotlin/org/eclipse/tractusx/bpdm/common/service/DataClassUnwrappedJsonDeserializerTest.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/exception/BpdmInvalidPartnerException.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/AddressService.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/ResponseMappings.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/BusinessPartnerControllerIT.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/util/BusinessPartnerNonVerboseValues.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/util/BusinessPartnerVerboseValues.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/util/EndpointValues.kt
- bpdm-orchestrator/src/test/kotlin/org/eclipse/tractusx/bpdm/orchestrator/controller/GoldenRecordTaskControllerIT.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/repository/ImportEntryRepository.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/repository/LegalEntityRepository.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/TaskEntryBpnMapping.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/TaskStepFetchAndReserveService.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/util/CreateSQLScriptToInsertRegions.kt
- bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/controller/MetadataControllerIT.kt
- bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/util/BusinessPartnerVerboseValues.kt
General code improvement in all Modules.
Removal of imports.
Removal of unused code and variables.
Logic improvement in separate ifs with equal conditions.
Removal of unnecessary assert not null.
Issues: https://github.com/eclipse-tractusx/bpdm/issues/578 https://github.com/eclipse-tractusx/bpdm/issues/579 https://github.com/eclipse-tractusx/bpdm/issues/576
> Refactor(BPDM): Clean import and unused vars for code smelling

- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/BusinessPartnerBuildService.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/MetadataService.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/RequestValidationService.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/TaskStepFetchAndReserveService.kt
- bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/service/RequestValidationServiceTest.kt
Upsert Business Partners from Cleaning Result - refactor validation 
prepare validation so that it can be called also by orchstrator
Solves: #556 
> feat(pool): #556 Upsert Business Partners from Cleaning Result - refactor validation

- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/GateAddressApi.kt
- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/GateLegalEntityApi.kt
- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/GateSharingStateApi.kt
- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/GateSiteApi.kt
This pull requests deprecates the Gate's L/S/A endpoints as well as the PUT sharing states endpoint. This is the first step towards building back the Bridge Dummy sharing process.
I have not deprecated the business partner filter properties in the changelog and sharing state endpoints as they could still be relevant later. A generic business partner can count as of type L/S/A if you so will and could be filterable like that.
Solves #548
> Docs (Gate-API): Deprecate Endpoints

- bpdm-cleaning-service-dummy/src/main/kotlin/org/eclipse/tractusx/bpdm/cleaning/service/GenericBusinessPartnerMappings.kt
- bpdm-cleaning-service-dummy/src/test/kotlin/org/eclipse/tractusx/bpdm/cleaning/testdata/CommonValues.kt
- bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/dto/IBaseAddressStateDto.kt
- bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/dto/IBaseBusinessPartnerDto.kt
- bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/dto/IBaseClassificationDto.kt
- bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/dto/IBaseIdentifierDto.kt
- bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/dto/IBaseLegalEntityStateDto.kt
- bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/dto/IBaseStateDto.kt
- bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/dto/IBusinessPartnerIdentifierDto.kt
- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/BusinessPartnerClassificationDto.kt
- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/BusinessPartnerIdentifierDto.kt
- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/BusinessPartnerPostalAddressDto.kt
- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/BusinessPartnerStateDto.kt
- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/request/BusinessPartnerInputRequest.kt
- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/request/BusinessPartnerOutputRequest.kt
- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/response/BusinessPartnerInputDto.kt
- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/response/BusinessPartnerOutputDto.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/BusinessPartnerMappings.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/OrchestratorMappings.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/BusinessPartnerControllerIT.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/util/BusinessPartnerGenericValues.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/util/BusinessPartnerVerboseValues.kt
- bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/model/BusinessPartnerClassificationDto.kt
- bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/model/BusinessPartnerGenericDto.kt
- bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/model/BusinessPartnerIdentifierDto.kt
- bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/model/BusinessPartnerStateDto.kt
- bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/model/PostalAddressDto.kt
- bpdm-orchestrator/src/test/kotlin/org/eclipse/tractusx/bpdm/orchestrator/testdata/BusinessPartnerTestValues.kt
The DTOs related to the Generic Business Partner were refactored, making sure all its data classes are located in the appropriate API modules (gate-api and orchestrator-api). Common interfaces are used whenever possible.
This meant splitting up some DTOs for the different modules which were formerly in the common module.
This is the first step towards #570
> Refactoring: Generic Business Partner DTO Locations

- bpdm-bridge-dummy/DOCKER_NOTICE.md
- bpdm-cleaning-service-dummy/DOCKER_NOTICE.md
- bpdm-gate/DOCKER_NOTICE.md
- bpdm-orchestrator/DOCKER_NOTICE.md
- bpdm-pool/DOCKER_NOTICE.md
Updated correct DockerHub image link for each service on BPDM under docker notice files
Fixes #642 #636 
> Docs(bpdm): updated correct url for docker hub image

- bpdm-common/pom.xml
- bpdm-gate-api/pom.xml
- bpdm-pool-api/pom.xml
This pull request changes the URL in the POM distributionManagement to the exclipse-tractusx bpdm repository. This way we lose dependencies to other github repositories.
Fixes #648
> Cicd(Pom): Change repo URL for deployment to eclipse-tractux/bpdm

- .gitignore
After changing from Spring `properties` to `yml` files, we need to add `application-developer.yml` to .gitignore.
> chore: Add application-developer.yml to .gitignore

- bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/model/TaskProcessingStateDto.kt
- bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/model/TaskStepReservationResponse.kt
- bpdm-orchestrator/src/main/kotlin/org/eclipse/tractusx/bpdm/orchestrator/Application.kt
- bpdm-orchestrator/src/main/kotlin/org/eclipse/tractusx/bpdm/orchestrator/config/TaskConfigProperties.kt
- bpdm-orchestrator/src/main/kotlin/org/eclipse/tractusx/bpdm/orchestrator/model/TaskProcessingState.kt
- bpdm-orchestrator/src/main/kotlin/org/eclipse/tractusx/bpdm/orchestrator/service/GoldenRecordTaskService.kt
- bpdm-orchestrator/src/main/kotlin/org/eclipse/tractusx/bpdm/orchestrator/service/GoldenRecordTaskStateMachine.kt
- bpdm-orchestrator/src/main/kotlin/org/eclipse/tractusx/bpdm/orchestrator/service/GoldenRecordTaskStorage.kt
- bpdm-orchestrator/src/main/resources/application.yml
- bpdm-orchestrator/src/test/kotlin/org/eclipse/tractusx/bpdm/orchestrator/controller/GoldenRecordTaskControllerIT.kt
- bpdm-orchestrator/src/test/kotlin/org/eclipse/tractusx/bpdm/orchestrator/service/GoldenRecordTaskStateMachineIT.kt
In the Orchestrator a cron-job checks if any of the two timeouts have been reached for any of the tasks:
- A task remaining in state "Pending" for a specified time (*taskPendingTimeout*) after its creation should go into state "Error" with error type "Timeout".
- A specified time (*taskRetentionTimeout*) after its creation a task should be completely removed from the Orchestrator.
**TaskStepReservationResponse.timeout** has been marked as deprecated as this field doesn't make much sense for a cleaning service.
We might add a task specific timeout in **TaskStepReservationEntryDto** but this is still up for debate.
Integration tests for the timeout cases have been added.
Solves #588
> feat(orchestrator): Service logic for timeout

- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/exception/GateErrorCodes.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/BusinessPartnerService.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/BusinessPartnerControllerIT.kt
This PR adds a new error message to a sharing state, when a request is done to the orchestrator with the task-id, but no related task is found.
Related issues: #589
> Feat (Gate) - Added new error for missing task in orchestrator

- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/TaskStepBuildService.kt
Currently, it is not possible in the Pool for a legal address to be also a main site address at the same time. This PR adjust the way a Address is persisted if both Legal Entity and Site share it.
Related issues: #657 
> Fix (Pool) - Added way to LegalAddress to be Main Site Address in Pool

- bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/dto/IBaseBusinessPartnerDto.kt
- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/IBaseBusinessPartnerGateDto.kt
- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/response/BusinessPartnerDto.kt
- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/response/BusinessPartnerOutputDto.kt
- bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/model/BusinessPartnerGenericDto.kt
- bpdm-orchestrator/src/test/kotlin/org/eclipse/tractusx/bpdm/orchestrator/controller/GoldenRecordTaskControllerIT.kt
- bpdm-orchestrator/src/test/kotlin/org/eclipse/tractusx/bpdm/orchestrator/testdata/BusinessPartnerTestValues.kt
This pull request moves L/S/A specific attirbutes in the generic business partner model of the Orchestrator to L/S/A subclasses. This way such attributes are categorized in the model.
In order to keep backwards compatibility with the other modules for now I also added an additional constructor and copy method. When other modules have integrated the new structure we can remove these additional constructs.
This pull request contributes to #669 
> Feat(Orchestrator): Separate LSA attributes in generic business partner

- bpdm-cleaning-service-dummy/src/main/kotlin/org/eclipse/tractusx/bpdm/cleaning/service/CleaningServiceDummy.kt
- bpdm-cleaning-service-dummy/src/main/kotlin/org/eclipse/tractusx/bpdm/cleaning/service/GenericBusinessPartnerMappings.kt
- bpdm-cleaning-service-dummy/src/test/kotlin/org/eclipse/tractusx/bpdm/cleaning/service/CleaningServiceDummyTest.kt
- bpdm-cleaning-service-dummy/src/test/kotlin/org/eclipse/tractusx/bpdm/cleaning/testdata/CommonValues.kt
In this pull request the Cleaning Service Dummy now correctly uses the new L/S/A separated attributes in the generic business partner model of the Orchestrator.
Contributes to #669 
> Feat(Cleaning-Service-Dummy): Map to L/S/A separated generic business partner attributes

- bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/dto/IBaseBusinessPartnerDto.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/OrchestratorMappings.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/BusinessPartnerControllerIT.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/util/BusinessPartnerGenericValues.kt
- bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/model/BusinessPartnerGenericDto.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/TaskStepBuildService.kt
- bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/service/TaskStepFetchAndReserveServiceTest.kt
This pull request adapts the gate orchestration mappings for the generic business partner to the L/S/A separated attributes.
Since this was the last BPDM module needing bigger changes to accomodate the L/S/A separation in the generic business partner I also removed the legacy attributes ensuring backwards compatibility.
Contributes to #669
> Refactor(Gate): Map to L/S/A separated generic business partner attributes 

- bpdm-cleaning-service-dummy/src/main/kotlin/org/eclipse/tractusx/bpdm/cleaning/service/CleaningServiceDummy.kt
- bpdm-cleaning-service-dummy/src/main/kotlin/org/eclipse/tractusx/bpdm/cleaning/service/GenericBusinessPartnerMappings.kt
- bpdm-cleaning-service-dummy/src/test/kotlin/org/eclipse/tractusx/bpdm/cleaning/testdata/CommonValues.kt
- bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/dto/IBaseBusinessPartnerDto.kt
- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/response/BusinessPartnerDto.kt
- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/response/BusinessPartnerOutputDto.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/generic/BusinessPartner.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/BusinessPartnerMappings.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/BusinessPartnerService.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/OrchestratorMappings.kt
- bpdm-gate/src/main/resources/db/migration/V5_0_0_0__add_site_address_name.sql
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/entity/generic/BusinessPartnerIT.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/util/BusinessPartnerGenericValues.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/util/BusinessPartnerNonVerboseValues.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/util/BusinessPartnerVerboseValues.kt
- bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/model/BusinessPartnerGenericDto.kt
- bpdm-orchestrator/src/test/kotlin/org/eclipse/tractusx/bpdm/orchestrator/testdata/BusinessPartnerTestValues.kt
This pull request adds site name and address name to the generic business partner model. By this changing the gate and the orchestrator api. I also added a migration script for the Gate to persist the new names.
Since we now have specific names the cleaning service now uses site and address name of the generic business partner to fill the respective names in the L/S/A model. Legal name will be still taken from the name parts though because we don't expect sharing members to provide the legal name themselves.
Test values and tests have been adapted where appropriate.
Contributes to #672 
> Feat: Add Site Name and Address Name to Generic Business Partner Model

- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/GateSharingStateApi.kt
- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/request/PostSharingStateReadyRequest.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/config/GoldenRecordProcessConfigProperties.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/controller/SharingStateController.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/exception/BpdmInvalidStateException.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/exception/BpdmMissingPartnerException.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/repository/SharingStateRepository.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/BusinessPartnerService.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/GoldenRecordTaskService.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/SharingStateService.kt
- bpdm-gate/src/main/resources/application.yml
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/BusinessPartnerControllerIT.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/SharingStateControllerIT.kt
This pull request now introduces the feature to share business partners to the golden record process on demand. This means, when upserting business partners they are not shared automatically.
- created API endpoint to set sharing state to ready
- created scheduled function to poll ready business partners and share them to the orchestrator
- moved all scheduled functions to their own golden record task service
- aligned the configuration properties and made them less error prone
- created additional tests for the new API endpoint and adapted existing tests accordingly
Solves #613
> feat(Gate): generic business partners can now be shared on demand

- bpdm-cleaning-service-dummy/src/main/kotlin/org/eclipse/tractusx/bpdm/cleaning/service/GenericBusinessPartnerMappings.kt
- bpdm-cleaning-service-dummy/src/test/kotlin/org/eclipse/tractusx/bpdm/cleaning/testdata/CommonValues.kt
- bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/dto/IBaseBusinessPartnerDto.kt
- bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/dto/IBaseSiteDto.kt
- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/response/BusinessPartnerOutputDto.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/generic/BusinessPartner.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/generic/ConfidenceCriteria.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/BusinessPartnerMappings.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/OrchestratorMappings.kt
- bpdm-gate/src/main/resources/db/migration/V5_0_0_2__create_confidence_criteria.sql
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/BusinessPartnerControllerIT.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/entity/generic/BusinessPartnerIT.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/util/BusinessPartnerGenericValues.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/util/BusinessPartnerVerboseValues.kt
- bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/model/BusinessPartnerGenericDto.kt
- bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/model/ConfidenceCriteriaDto.kt
- bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/model/LegalEntityDto.kt
- bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/model/LogisticAddressDto.kt
- bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/model/SiteDto.kt
- bpdm-orchestrator/src/test/kotlin/org/eclipse/tractusx/bpdm/orchestrator/testdata/BusinessPartnerTestValues.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/BusinessPartnerBuildService.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/TaskStepBuildService.kt
- bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/service/TaskStepFetchAndReserveServiceTest.kt
This pull request adds confidence criteria fields to the generic business partner model.
- add confidence criteria fields to generic API DTOs
- added persistence for the confidence criteria in the Gate
- changed test and test values accordingly
- made adjustments to the common base DTO interfaces for better integration
Solves #670 after #692 has been merged
> Feat: Add confidence criteria to generic business partner model

- bpdm-cleaning-service-dummy/src/test/kotlin/org/eclipse/tractusx/bpdm/cleaning/testdata/CommonValues.kt
- bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/dto/IBaseStreetDto.kt
- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/StreetDto.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/PhysicalPostalAddress.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/Street.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/BusinessPartnerMappings.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/OrchestratorMappings.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/ResponseMappings.kt
- bpdm-gate/src/main/resources/db/migration/V5_0_0_3__add_house_number_supplement.sql
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/entity/generic/BusinessPartnerIT.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/util/BusinessPartnerGenericValues.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/util/BusinessPartnerVerboseValues.kt
- bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/model/StreetDto.kt
- bpdm-orchestrator/src/test/kotlin/org/eclipse/tractusx/bpdm/orchestrator/testdata/BusinessPartnerTestValues.kt
- bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/model/StreetDto.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/entity/PhysicalPostalAddress.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/entity/Street.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/BusinessPartnerBuildService.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/ResponseMappings.kt
- bpdm-pool/src/main/resources/db/migration/V5_0_0_2__add_house_number_supplement.sql
- bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/service/TaskStepFetchAndReserveServiceTest.kt
- bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/util/BusinessPartnerVerboseValues.kt
This pull requests adds a new field to the business partner street: house number supplement. The field is added to both the LSA and generic business partner models.
- added field to API model
- added new field and column to persistence
- adjusted mappings accordingly
- adjusted tests accordingly
Solves #679. Requires pull request #690 to be merged first.
> Feat: add house number supplement

- bpdm-gate/src/main/resources/db/migration/V5_0_0_4__create_temp_confidence_criteria.sql
- bpdm-pool/src/main/resources/db/migration/V5_0_0_1__add_confidence_criteria.sql
This pull request adds default confidence criteria to existing business partners where needed. This solves a bug when trying to add confidence criteria to databases with existing business partners.
> fix(Confidence): add default confidence criteria

- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/GoldenRecordTaskService.kt
When the gate writes back sharing process errors to the business partner record's sharing state, the amount of errors could be too long, leading to an error when trying to save them to the database. 
Now the error message is cut off, if too long.
> fix(Gate): error when persisting too long sharing process error messages

- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/StatsApi.kt
- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/response/StatsSharingStatesResponse.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/controller/StatsController.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/repository/SharingStateRepository.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/StatsService.kt
This pull request adds an endpoint to count busines partners by sharing state type.
> feat(Gate): add stats endpoint for counting sharing state types

- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/StatsApi.kt
- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/response/StatsAddressTypesResponse.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/controller/StatsController.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/StatsService.kt
This pull request adds an endpoint to count address types of business partners per stage. The stage must be given as a path variable to the query.
> feat(Gate): add stats endpoint for counting address types per stage

- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/StatsApi.kt
- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/response/StatsConfidenceCriteriaResponse.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/controller/StatsController.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/repository/generic/BusinessPartnerRepository.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/repository/generic/ConfidenceCriteriaRepository.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/StatsService.kt
This pull request add an endpoint for the gate showing aggregation stats for confidence criteria:
* numberOfBusinessPartnersAverage: average number of how many sharing members have shared the same business partners
* unqiueTotal: number of business partners that are unique to the sharing members
* sharedByOwnerTotal: number of business partners that have been shared by the owning sharing member
* checkedByExternalDataSourceTotal: number of business partners that have been validated against an external data source
* confidenceLevelAverage : average confidence level among business partner records in the gate
> feat(Gate): add endpoint for confidence criteria stats

- charts/bpdm/Chart.yaml
- charts/bpdm/charts/bpdm-bridge-dummy/Chart.yaml
- charts/bpdm/charts/bpdm-cleaning-service-dummy/Chart.yaml
- charts/bpdm/charts/bpdm-gate/Chart.yaml
- charts/bpdm/charts/bpdm-orchestrator/Chart.yaml
- charts/bpdm/charts/bpdm-pool/Chart.yaml
This pull request increases the appversion of the BPDM charts to 5.0.0-alpha.1
> feat(Charts): increase to appversion 5.0.0-alpha.1

- bpdm-cleaning-service-dummy/src/main/kotlin/org/eclipse/tractusx/bpdm/cleaning/service/CleaningServiceDummy.kt
- bpdm-gate/src/main/resources/db/migration/V5_0_0_5__create_site_confidence_criteria.sql
This pull request fixes the missing confidence criteria in the generic business partner. Basically the cleaning service now additionally to LSA also adds the confidence criteria to the generic business partner. This way when Gate requests the business partner data from the Orchestrator it will also find the confidence criteria there.
On the same note I also made the cleaning service add the correct address type to the generic business partner. So now it should never be null, even if it was not provided by the sharing member.
> fix(Cleaning-Service-Dummy): missing confidence criteria

- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/GoldenRecordTaskService.kt
This pull request sets the maximum length of the Gate's sharing process error message to exactly the columns size definition in order to avoid errors on persisting the sharing status.
> fix(Gate): maximum length of sharing process error

- charts/bpdm/Chart.yaml
- charts/bpdm/charts/bpdm-bridge-dummy/Chart.yaml
- charts/bpdm/charts/bpdm-cleaning-service-dummy/Chart.yaml
- charts/bpdm/charts/bpdm-gate/Chart.yaml
- charts/bpdm/charts/bpdm-orchestrator/Chart.yaml
- charts/bpdm/charts/bpdm-pool/Chart.yaml
This pull request increases the appversion of the BPDM Charts to 5.0.0-alpha.2
> feat(Charts): increase appversion to 5.0.0-alpha.2

- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/GateSharingStateApi.kt
This pull request fixes the POST endpoint to set a given number of business partners into sharing state ready. The endpoint now correctly is named sharing-states/ready instead of just sharing-states. 
> fix(Gate-Api): name of POST endpoint to set sharing state to ready

- CHANGELOG.md
- DEPENDENCIES
- pom.xml
Fix Spring vulnerability's reported by Trivy Scan
https://github.com/eclipse-tractusx/bpdm/issues/706
> Fix trivy findings on spring boot image

- bpdm-bridge-dummy/src/main/kotlin/com/catenax/bpdm/bridge/dummy/config/BridgeAuthProperties.kt
- bpdm-bridge-dummy/src/main/resources/application-auth.yml
- bpdm-bridge-dummy/src/main/resources/application-gate-auth.yml
- bpdm-bridge-dummy/src/main/resources/application-pool-auth.yml
- bpdm-bridge-dummy/src/main/resources/application.yml
- bpdm-cleaning-service-dummy/src/main/resources/application-orchestrator-auth.yml
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/OrchestratorMappings.kt
- bpdm-gate/src/main/resources/application-auth.yml
- bpdm-gate/src/main/resources/application-orchestrator-auth.yml
- bpdm-gate/src/main/resources/application-pool-auth.yml
- bpdm-orchestrator/src/main/resources/application-auth.yml
- bpdm-orchestrator/src/main/resources/application.yml
- bpdm-pool/src/main/resources/application-orchestrator-auth.yml
Solves remaining points raised on PR #623.
Solve #572
Should be merged only after #623 conclusion.
> Refactor (bpdm) - Creation of Auth YML's and Path changes

- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/config/OrchestratorClientConfigProperties.kt
This pull request fixes the path of the orchestrator client base-url configuration property. The properties file specifies correctly bpdm.client.orchestrator-pool but the config properties bind to bpdm.orchestrator-pool. I adapted the binding to the correct path.
> fix(Pool): orchestrator client config properties binding

- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/BusinessPartnerService.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/controller/SiteController.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/BusinessPartnerBuildService.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/BusinessPartnerEquivalenceService.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/TaskStepBuildService.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/TaskStepFetchAndReserveService.kt
- bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/controller/ChangelogControllerIT.kt
This pull request fixes an error on updating business partners with legal and site main addresses
- optimized equivalence check to be used in business partner build service
- heavily refactored task step build service to fit new structure
- adapted tests to work with fixed equivalence check
> fix(Golden Record): Update on Legal and Site Main Address

- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/BusinessPartnerBuildService.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/BusinessPartnerEquivalenceMapper.kt
This pull request fixes a bug where the Pool updates legal entities and addresses even though they contain no new data.
> fix(Pool): equivalence check on legal entities and addresses

- charts/bpdm/Chart.yaml
- charts/bpdm/charts/bpdm-bridge-dummy/Chart.yaml
- charts/bpdm/charts/bpdm-cleaning-service-dummy/Chart.yaml
- charts/bpdm/charts/bpdm-gate/Chart.yaml
- charts/bpdm/charts/bpdm-orchestrator/Chart.yaml
- charts/bpdm/charts/bpdm-pool/Chart.yaml
This pull request increases the appversion of the BPDM Charts to 5.0.0-alpha.3
> feat(Charts): increase appversion to 5.0.0-alpha.3

- bpdm-cleaning-service-dummy/src/main/kotlin/org/eclipse/tractusx/bpdm/cleaning/service/CleaningServiceDummy.kt
- bpdm-cleaning-service-dummy/src/main/kotlin/org/eclipse/tractusx/bpdm/cleaning/service/GenericBusinessPartnerMappings.kt
- bpdm-cleaning-service-dummy/src/main/kotlin/org/eclipse/tractusx/bpdm/cleaning/util/StringExtensions.kt
- bpdm-cleaning-service-dummy/src/test/kotlin/org/eclipse/tractusx/bpdm/cleaning/service/CleaningServiceDummyTest.kt
This pull request changes the strategy on how the cleaning service performs duplicate checks. It is now based on names (legal entity name, site name and address name). Based on the name it creates a BPN reference hash string. This means the names have to be exactly the same to determine a duplicate.
> feat(Cleaning Service): create BPN references based on name

- charts/bpdm/Chart.yaml
- charts/bpdm/charts/bpdm-bridge-dummy/Chart.yaml
- charts/bpdm/charts/bpdm-cleaning-service-dummy/Chart.yaml
- charts/bpdm/charts/bpdm-gate/Chart.yaml
- charts/bpdm/charts/bpdm-orchestrator/Chart.yaml
- charts/bpdm/charts/bpdm-pool/Chart.yaml
This pull request increases the BPDM Chart appversion to 5.0.0-alpha.4
> feat(Charts): increase appversion to 5.0.0-alpha.4

- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/repository/PartnerChangelogEntryRepository.kt
This pull request fixes the timestampAfter filter for changelog entries of the Pool. Instead of returning changelogs with a timestamp greater and equals the filter now correctly only returns timestamps greater than the specified one.
Fixes #721 
> Fix: Pool Changelog Timestamp After Filter Also Including Equal

- bpdm-cleaning-service-dummy/src/main/kotlin/org/eclipse/tractusx/bpdm/cleaning/service/CleaningServiceDummy.kt
- bpdm-cleaning-service-dummy/src/main/kotlin/org/eclipse/tractusx/bpdm/cleaning/util/StringExtensions.kt
this pull request fixes a bug in which the legal, site and address name stays null in the cleaned generic business partner, when the BPDM cleaning service dummy performs a cleaning of a golden record task.
> fix(Cleaning Service): generic LSA names being null in cleaning result

- bpdm-bridge-dummy/Dockerfile
- bpdm-cleaning-service-dummy/Dockerfile
- bpdm-gate/Dockerfile
- bpdm-orchestrator/Dockerfile
- bpdm-pool/Dockerfile
This pull request increases the used GIDs in the Dockerfiles to a value over 10000 in order to increase the security.
Contributes to solve #728
> fix(Docker): increase the default user group ID to over 10000

- charts/bpdm/Chart.yaml
- charts/bpdm/charts/bpdm-bridge-dummy/CHANGELOG.md
- charts/bpdm/charts/bpdm-bridge-dummy/Chart.yaml
- charts/bpdm/charts/bpdm-bridge-dummy/values.yaml
- charts/bpdm/charts/bpdm-cleaning-service-dummy/CHANGELOG.md
- charts/bpdm/charts/bpdm-cleaning-service-dummy/Chart.yaml
- charts/bpdm/charts/bpdm-cleaning-service-dummy/values.yaml
- charts/bpdm/charts/bpdm-gate/CHANGELOG.md
- charts/bpdm/charts/bpdm-gate/Chart.yaml
- charts/bpdm/charts/bpdm-gate/values.yaml
- charts/bpdm/charts/bpdm-orchestrator/CHANGELOG.md
- charts/bpdm/charts/bpdm-orchestrator/Chart.yaml
- charts/bpdm/charts/bpdm-orchestrator/values.yaml
- charts/bpdm/charts/bpdm-pool/CHANGELOG.md
- charts/bpdm/charts/bpdm-pool/Chart.yaml
- charts/bpdm/charts/bpdm-pool/values.yaml
This pull request increases the default groupid of the BPDM containers to over 10001 for security reasons.
Contributes to #728 
Can only be merged after #729 and when a new alpha-release 5.0.0-alpha.5 is available on the Dockerhub
> Fix: GID for BPDM Charts

- charts/bpdm/CHANGELOG.md
- charts/bpdm/Chart.yaml
- charts/bpdm/charts/bpdm-bridge-dummy/CHANGELOG.md
- charts/bpdm/charts/bpdm-bridge-dummy/Chart.yaml
- charts/bpdm/charts/bpdm-bridge-dummy/templates/deployment.yaml
- charts/bpdm/charts/bpdm-bridge-dummy/values.yaml
- charts/bpdm/charts/bpdm-cleaning-service-dummy/CHANGELOG.md
- charts/bpdm/charts/bpdm-cleaning-service-dummy/Chart.yaml
- charts/bpdm/charts/bpdm-cleaning-service-dummy/templates/deployment.yaml
- charts/bpdm/charts/bpdm-cleaning-service-dummy/values.yaml
- charts/bpdm/charts/bpdm-gate/CHANGELOG.md
- charts/bpdm/charts/bpdm-gate/Chart.yaml
- charts/bpdm/charts/bpdm-gate/templates/deployment.yaml
- charts/bpdm/charts/bpdm-gate/values.yaml
- charts/bpdm/charts/bpdm-orchestrator/CHANGELOG.md
- charts/bpdm/charts/bpdm-orchestrator/Chart.yaml
- charts/bpdm/charts/bpdm-orchestrator/templates/deployment.yaml
- charts/bpdm/charts/bpdm-orchestrator/values.yaml
- charts/bpdm/charts/bpdm-pool/CHANGELOG.md
- charts/bpdm/charts/bpdm-pool/Chart.yaml
- charts/bpdm/charts/bpdm-pool/templates/deployment.yaml
- charts/bpdm/charts/bpdm-pool/values.yaml
By default root file systems of the BPDM Chart container's are now mounted read-only for security reasons.
Solves #731
Can only be merged after #730 
> Fix: Mount Chart container's root file systems as read-only

- DEPENDENCIES
- pom.xml
This pull request fixes  vulnerability issues in current dependencies by increasing dependency versions:
- increase spring-boot to version 3.18
- increase wiremock to version 2.35.1
- increase kotlin to version 1.9.22
- increase springdoc to version 2.3.0
> fix(Pom): vulnerability issues in current dependencies by increasing dependency versions

- bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/config/CustomJwtAuthenticationConverter.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/config/BpnConfigProperties.kt
- bpdm-gate/src/main/resources/application.yml
When setting null to owner BPNL in Gate, no endpoint can't be accessed anymore as Forbidden is returned.
This pull request fixes empty owner BPNL leading to forbidden errors in Gate
- Made the owner BPNL now not nullable because of binding behaviour of Spring (https://github.com/spring-projects/spring-framework/issues/19986)
- Rather check whether BPNL is blank than null since property normally will not be bound as null anyway
> fix(Gate): empty owner BPNL leading to forbidden errors

- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/config/GoldenRecordTaskConfigProperties.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/TaskStepFetchAndReserveService.kt
- bpdm-pool/src/main/resources/application.yml
Currently, the configuration property in Pool for scheduling the golden record task processing is not working. 
Fixed it by:
- moved the property to a more fitting prefix under 'tasks'
- use bound property in scheduler to reduce mismatch chance
> Fix(Pool): Property for Golden Record Task Processing

- charts/bpdm/Chart.yaml
- charts/bpdm/charts/bpdm-bridge-dummy/Chart.yaml
- charts/bpdm/charts/bpdm-bridge-dummy/templates/ingress.yaml
Fix some faulty formatting on Bridge chart's ingress
> fix(charts): ingress formatting of bridge chart

- charts/bpdm/CHANGELOG.md
- charts/bpdm/Chart.yaml
- charts/bpdm/charts/bpdm-bridge-dummy/CHANGELOG.md
- charts/bpdm/charts/bpdm-bridge-dummy/Chart.yaml
- charts/bpdm/charts/bpdm-cleaning-service-dummy/CHANGELOG.md
- charts/bpdm/charts/bpdm-cleaning-service-dummy/Chart.yaml
- charts/bpdm/charts/bpdm-gate/CHANGELOG.md
- charts/bpdm/charts/bpdm-gate/Chart.yaml
- charts/bpdm/charts/bpdm-orchestrator/CHANGELOG.md
- charts/bpdm/charts/bpdm-orchestrator/Chart.yaml
- charts/bpdm/charts/bpdm-pool/CHANGELOG.md
- charts/bpdm/charts/bpdm-pool/Chart.yaml
This pull request increases the appversion of the BPDM charts to 5.0.0 and also increases the chart version to release 4.0.0
> feat(charts): inrease appversion to 5.0.0

- .github/workflows/helm-chart-lint.yaml
- removing not needed helm chart repo out of Chart Liniting and helm validation
fixes: https://github.com/eclipse-tractusx/bpdm/issues/765
> chore: remove opensearch chart repo

- charts/bpdm/CHANGELOG.md
- charts/bpdm/Chart.yaml
- charts/bpdm/README.md
- charts/bpdm/charts/bpdm-bridge-dummy/CHANGELOG.md
- charts/bpdm/charts/bpdm-bridge-dummy/Chart.yaml
- charts/bpdm/charts/bpdm-bridge-dummy/values.yaml
- charts/bpdm/charts/bpdm-cleaning-service-dummy/CHANGELOG.md
- charts/bpdm/charts/bpdm-cleaning-service-dummy/Chart.yaml
- charts/bpdm/charts/bpdm-cleaning-service-dummy/values.yaml
- charts/bpdm/charts/bpdm-gate/CHANGELOG.md
- charts/bpdm/charts/bpdm-gate/Chart.yaml
- charts/bpdm/charts/bpdm-gate/values.yaml
- charts/bpdm/charts/bpdm-orchestrator/CHANGELOG.md
- charts/bpdm/charts/bpdm-orchestrator/Chart.yaml
- charts/bpdm/charts/bpdm-orchestrator/values.yaml
- charts/bpdm/charts/bpdm-pool/CHANGELOG.md
- charts/bpdm/charts/bpdm-pool/Chart.yaml
- charts/bpdm/charts/bpdm-pool/README.md
- charts/bpdm/charts/bpdm-pool/values.yaml
This pull request aligns the BPDM Chart's memory request and memory limit by setting both to 512Mi on default values.
Additionally, I removed some mentions of Opensearch configuration from the chart's READMEs.
Fixes #767 
> Charts: Update to 4.0.1

- README.md
This pull request adds installation instructions to the README file. 
Actually the instructions just provide links to our two main installation documentation: Local installation and Helm Chart installation.
I have the feeling that the TRGs have a slightly different strategy for documentation. But I believe that there is an advantage to put the relevant installation instructions for the Helm charts directly in the Helm Chart README and not in the docs folder or repo root. I guess this is debatable.
fixes #759
> docs(README): add installation instructions

- CHANGELOG.md
- bpdm-bridge-dummy/pom.xml
- bpdm-cleaning-service-dummy/pom.xml
- bpdm-common/pom.xml
- bpdm-gate-api/pom.xml
- bpdm-gate/pom.xml
- bpdm-orchestrator-api/pom.xml
- bpdm-orchestrator/pom.xml
- bpdm-pool-api/pom.xml
- bpdm-pool/pom.xml
- pom.xml
This pull request increases the BPDM version in the POM files to 6.0.0-SNAPSHOT. With this the main branch will now follow the BPDM release 6.0.0
> feat(app): increase BPDM version to snapshot 6.0.0

- bpdm-common-test/pom.xml
This pull request fixes the currently broken main due to the BPDM Common Test module referencing the outdated POM 5.0.1-SNAPSHOT. Increased it to the now correct version 6.0.0-SNAPSHOT
> fix(Common-Test): POM referencing outdated BPDM version

- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/GateSharingStateApi.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/config/GoldenRecordProcessConfigProperties.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/config/GoldenRecordTaskConfiguration.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/controller/SharingStateController.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/GoldenRecordTaskService.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/SharingStateService.kt
- bpdm-gate/src/main/resources/application.yml
This pull request adds a configuration property for the Gate enabling new business partner data to be automatically set to ready to be shared state.
- added new configuration property under tasks
- added documentation for all task properties
- refactor: made the configuration properties class immutable
- refactor: added a configuration class for scheduling task service methods (so no SpEL needed)
- added initial or ready logic in sharing state service
> feat(Gate): Configuration for Automatic Ready State

- bpdm-bridge-dummy/src/main/kotlin/com/catenax/bpdm/bridge/dummy/service/PoolUpdateService.kt
- bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/model/response/PoolErrorCodes.kt
Handle error on BPDM Bridge when sync from Gate To Pool
Exception is thrown when mapping logistic address
Fixes: https://github.com/eclipse-tractusx/bpdm/issues/783
> Bridge: Handle 500 Error 

- .github/workflows/codeql.yml
This PR introduces an open-source SAST tool called CodeQL which is native to GitHub.
This is requested as part of the transition from commercial tool vendor to an open source tool that offers better GitHub integration, at no extra cost, making our security setup more efficient.
CodeQL will be added as a mandatory tool to perform SAST scans as part of the TRG 8.0 Security.
> SAST Scans using CodeQl

- charts/bpdm/CHANGELOG.md
- charts/bpdm/Chart.yaml
- charts/bpdm/charts/bpdm-bridge-dummy/CHANGELOG.md
- charts/bpdm/charts/bpdm-bridge-dummy/Chart.yaml
- charts/bpdm/charts/bpdm-bridge-dummy/templates/_helpers.tpl
- charts/bpdm/charts/bpdm-bridge-dummy/templates/configMap.yaml
- charts/bpdm/charts/bpdm-cleaning-service-dummy/CHANGELOG.md
- charts/bpdm/charts/bpdm-cleaning-service-dummy/Chart.yaml
- charts/bpdm/charts/bpdm-cleaning-service-dummy/templates/_helpers.tpl
- charts/bpdm/charts/bpdm-cleaning-service-dummy/templates/configMap.yaml
- charts/bpdm/charts/bpdm-gate/CHANGELOG.md
- charts/bpdm/charts/bpdm-gate/Chart.yaml
- charts/bpdm/charts/bpdm-gate/templates/_helpers.tpl
- charts/bpdm/charts/bpdm-gate/templates/configMap.yaml
- charts/bpdm/charts/bpdm-orchestrator/CHANGELOG.md
- charts/bpdm/charts/bpdm-orchestrator/Chart.yaml
- charts/bpdm/charts/bpdm-pool/CHANGELOG.md
- charts/bpdm/charts/bpdm-pool/Chart.yaml
- charts/bpdm/charts/bpdm-pool/templates/_helpers.tpl
- charts/bpdm/charts/bpdm-pool/templates/configMap.yaml
- charts/bpdm/charts/bpdm-pool/values.yaml
- charts/bpdm/values.yaml
This pull request fixes how the BPDM Charts resolve default service names of dependencies. The umbrella and subcharts now find the postgres dependency and the password on default without any configuration needed.
Also fixed how the Charts resolve the default service names for other BPDM charts that they are dependend on.
Fixes #786 
> fix(charts): fix default dependency service

- bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/PoolMembersApi.kt
- bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/model/request/AddressSearchRequest.kt
- bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/model/request/LegalEntitySearchRequest.kt
- bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/model/request/SiteSearchRequest.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/controller/MemberController.kt
- docs/api/pool.json
This pull request adds endpoint definitions for querying Catena-X member business partner information in the Pool. The endpoints are not functional for now.
Contributes to #793
> feat(Pool): add API stubs for Catena-X member query endpoints

- bpdm-cleaning-service-dummy/src/main/kotlin/org/eclipse/tractusx/bpdm/cleaning/service/GenericBusinessPartnerMappings.kt
- bpdm-common-test/src/main/kotlin/org/eclipse/tractusx/bpdm/test/testdata/gate/BusinessPartnerGenericCommonValues.kt
- bpdm-common-test/src/main/kotlin/org/eclipse/tractusx/bpdm/test/testdata/gate/BusinessPartnerVerboseValues.kt
- bpdm-common-test/src/main/kotlin/org/eclipse/tractusx/bpdm/test/testdata/pool/BusinessPartnerVerboseValues.kt
- bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/dto/IConfidenceCriteriaDto.kt
- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/ConfidenceCriteriaDto.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/BusinessPartnerMappings.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/OrchestratorMappings.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/util/BusinessPartnerGenericValues.kt
- bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/model/ConfidenceCriteriaDto.kt
- bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/model/ConfidenceCriteriaDto.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/BusinessPartnerBuildService.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/BusinessPartnerEquivalenceMapper.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/TaskStepBuildService.kt
- bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/service/TaskStepFetchAndReserveServiceTest.kt
Corrects naming mistake of the field "numberOfBusinessPartners" in the confidence criteria to "numberOfSharingMembers".
Solves #788
> fix(model): wrong name for confidence criteria number of sharing members

- bpdm-common-test/src/main/kotlin/org/eclipse/tractusx/bpdm/test/testdata/pool/BusinessPartnerVerboseValues.kt
- bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/model/LogisticAddressVerboseDto.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/ResponseMappings.kt
- bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/controller/AddressControllerIT.kt
- bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/controller/SiteControllerIT.kt
- bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/service/BusinessPartnerComparator.kt
- bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/service/TaskStepFetchAndReserveServiceTest.kt
This pull request removes the flags "isLegalAddress" and "isSiteMainAddress" from the Pool's address model.
The flags are not needed anymore since the information is already stored in the address type enumeration.
Adjusted tests accordingly.
Solves #680 
> feat(Pool): remove isLegalAddress and isMainSiteAddress flags

- bpdm-bridge-dummy/src/main/kotlin/com/catenax/bpdm/bridge/dummy/service/PoolUpdateService.kt
- bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/model/response/PoolErrorCodes.kt
This pull request adds the fix for the BPDM Bridge responding with 500 to the 5.0.x release branch. Context on #790 
> feat(BPDM Bridge): Handle 500 error on create entities from Gate to Pool

- charts/bpdm/CHANGELOG.md
- charts/bpdm/Chart.yaml
- charts/bpdm/charts/bpdm-bridge-dummy/CHANGELOG.md
- charts/bpdm/charts/bpdm-bridge-dummy/Chart.yaml
- charts/bpdm/charts/bpdm-cleaning-service-dummy/CHANGELOG.md
- charts/bpdm/charts/bpdm-cleaning-service-dummy/Chart.yaml
- charts/bpdm/charts/bpdm-gate/CHANGELOG.md
- charts/bpdm/charts/bpdm-gate/Chart.yaml
- charts/bpdm/charts/bpdm-orchestrator/CHANGELOG.md
- charts/bpdm/charts/bpdm-orchestrator/Chart.yaml
- charts/bpdm/charts/bpdm-pool/CHANGELOG.md
- charts/bpdm/charts/bpdm-pool/Chart.yaml
This pull request increases the current BPDM chart's appversion to 5.0.1
> feat(charts): increase app version to 5.0.1

- bpdm-cleaning-service-dummy/src/main/kotlin/org/eclipse/tractusx/bpdm/cleaning/service/GenericBusinessPartnerMappings.kt
- bpdm-cleaning-service-dummy/src/test/kotlin/org/eclipse/tractusx/bpdm/cleaning/testdata/CommonValues.kt
- bpdm-common-test/src/main/kotlin/org/eclipse/tractusx/bpdm/test/testdata/gate/BusinessPartnerGenericCommonValues.kt
- bpdm-common-test/src/main/kotlin/org/eclipse/tractusx/bpdm/test/testdata/gate/BusinessPartnerVerboseValues.kt
- bpdm-common-test/src/main/kotlin/org/eclipse/tractusx/bpdm/test/testdata/pool/BusinessPartnerVerboseValues.kt
- bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/dto/IBaseLegalEntityDto.kt
- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/LegalEntityDto.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/ResponseMappings.kt
- bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/model/LegalEntityDto.kt
- bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/model/LegalEntityDto.kt
- bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/model/LegalEntityVerboseDto.kt
- bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/model/LogisticAddressDto.kt
- bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/model/LogisticAddressVerboseDto.kt
- bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/model/SiteDto.kt
- bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/model/SiteVerboseDto.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/controller/LegalEntityController.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/entity/LegalEntityDb.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/repository/SiteRepository.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/BusinessPartnerBuildService.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/BusinessPartnerEquivalenceMapper.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/ResponseMappings.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/SiteService.kt
- bpdm-pool/src/main/resources/db/migration/V6_0_0_0__add_is_catena_member.sql
- bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/service/BusinessPartnerCreator.kt
- bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/service/TaskStepFetchAndReserveServiceTest.kt
This pull request implements the logic to set the isCatenaXMemberData field of the business partners based on the confidence criteria sharedByOwner flag.
- Cleaning Service Dummy know sets the isCatenaXMemberData field based on whether a owner BPNL has been provided
- isCatenaXMemberData is now part of the legal entity database table and is initialized with the same value as the confidence criteria sharedByOwner
- added correct mappings in the Pool
- isCatenaXMemberData now also appears in the Orchestrator API model where it is set by the cleaning service dummy
- adjusted tests accordingly
Contributes to #793 
> feat(Member): set isCatenaXMemberData based on ownership information

- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/config/GoldenRecordProcessConfigProperties.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/SharingStateService.kt
- bpdm-gate/src/main/resources/application.yml
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/BusinessPartnerControllerAndSharingControllerIT.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/util/MockAndAssertUtils.kt
On Bpn creation pass the sharing state to ready by default
Change Unit Test to contemplate both states Initial and Ready
Rework and organize Unit Test
issue: https://github.com/eclipse-tractusx/bpdm/issues/815
> Change State to Ready on BPDM Create

- bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/config/AppInfoProperties.kt
- bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/config/OpenApiConfig.kt
- bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/util/OpenApiCustomizerFactory.kt
- bpdm-gate/src/main/resources/application.yml
- bpdm-orchestrator/src/main/resources/application.yml
- bpdm-pool/src/main/resources/application.yml
This pull request creates additionally to the normal OpenAPI documents, special versioned OpenAPI documents that have the API's URL + version as base-url. This serves the following purpose: 
When we support multiple API versions at the same time we can generate separate OpenAPI documents based on each version
This is useful to create versioned Postman collections from these documents as well as publish the different api versions separately.
Only merge after #830
> Feat: Create V6 versioned OpenAPI Document

- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/response/SharingStateDto.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/controller/SharingStateController.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/SharingStateDb.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/repository/SharingStateRepository.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/BusinessPartnerService.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/GoldenRecordTaskService.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/SharingStateService.kt
- bpdm-gate/src/main/resources/db/migration/V6_0_0_2__drop_sharing_state_bp_bpn.sql
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/BusinessPartnerControllerAndSharingControllerIT.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/BusinessPartnerControllerIT.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/util/MockAndAssertUtils.kt
This pull request removes the sharing state's business partner type and BPN from the API. Since we now only deal with generic business partners, those fields are not necessary anymore.
Merge only after #833 
> Feat: Prune sharing state

- bpdm-cleaning-service-dummy/src/main/kotlin/org/eclipse/tractusx/bpdm/cleaning/service/GenericBusinessPartnerMappings.kt
- bpdm-cleaning-service-dummy/src/test/kotlin/org/eclipse/tractusx/bpdm/cleaning/testdata/CommonValues.kt
- bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/dto/IBaseBusinessPartnerDto.kt
- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/response/BusinessPartnerDto.kt
- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/response/BusinessPartnerOutputDto.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/generic/StateDb.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/BusinessPartnerMappings.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/OrchestratorMappings.kt
- bpdm-gate/src/main/resources/db/migration/V6_0_0_4__add_LSA_states.sql
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/entity/generic/BusinessPartnerIT.kt
- bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/model/BusinessPartnerGenericDto.kt
This pull request adds LSA state fields to the generic business partner model. This way LSA specific state information can be shared to the golden record process as well as can be returned from the process back to the sharing member.
#789 
> Feat: Add LSA States to generic business partner

- bpdm-cleaning-service-dummy/src/test/kotlin/org/eclipse/tractusx/bpdm/cleaning/service/CleaningServiceApiCallsTest.kt
- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/ApiCommons.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/util/MockAndAssertUtils.kt
- bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/GoldenRecordTaskApi.kt
- bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/ApiCommons.kt
This pull request fixes the BPDM API clients not correctly assembling the base url path of endpoints.
> fix(api-clients): base url path for endpoints

- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/BusinessPartnerService.kt
This pull request fixes business partner outputdata not updating confidence criteria from the golden record process.
> fix(gate): not updating confidence values for business partners

- charts/bpdm/CHANGELOG.md
- charts/bpdm/Chart.yaml
- charts/bpdm/charts/bpdm-common/templates/_helpers.tpl
- charts/bpdm/charts/bpdm-gate/CHANGELOG.md
- charts/bpdm/charts/bpdm-gate/Chart.yaml
- charts/bpdm/charts/bpdm-pool/CHANGELOG.md
- charts/bpdm/charts/bpdm-pool/Chart.yaml
This pull request increases the postgres dependency version to 15
> feat(charts): increase supported postgres version to 15

- README.md
This pull request satisfies TRG 4.06 by adding links to the Docker notice files in the top-level README.
> docs(docker): add links to notice files in top-level readme

- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/config/PermissionConfigProperties.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/controller/BusinessPartnerController.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/controller/ChangelogController.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/controller/SharingStateController.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/controller/StatsController.kt
- bpdm-gate/src/main/resources/application-auth.yml
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/config/PermissionConfigProperties.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/controller/ChangelogController.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/controller/MemberController.kt
- bpdm-pool/src/main/resources/application-auth.yml
This pool request adds new, more fine-granular - permissions to the BPDM Gate and Pool API. This way we can better fine tune the access logic to the existing resources.
Contributes to implementing eclipse-tractusx/sig-release#565
> feat(Auth): add additional permissions to the pool and gate APIs

- charts/bpdm/Chart.yaml
- charts/bpdm/charts/bpdm-cleaning-service-dummy/Chart.yaml
- charts/bpdm/charts/bpdm-gate/Chart.yaml
- charts/bpdm/charts/bpdm-orchestrator/Chart.yaml
- charts/bpdm/charts/bpdm-pool/Chart.yaml
This pull request increases the supported app version of the BPDM Charts to 6.0.0-alpha.1
> feat(charts): increase app version to 6.0.0-alpha.1

- docker/docker-compose.yml
- docker/postgres/init.sh
Add Keycloak container to docker compose file for setting up BPDM app dependencies.
The Keycloak container is configured with a default realm which corresponds to the default auth configuration of the BPDM apps. This makes executing BPDM apps locally with authentication profile running much easier.
> chore(Docker): add Keycloak container to docker compose file

- bpdm-common-test/src/main/kotlin/org/eclipse/tractusx/bpdm/test/containers/KeycloakContextInitializer.kt
- docker/docker-compose.yml
- pom.xml
Increases the used Keycloak version in tests and Docker to 23.0
> feat(Keycloak): increase supported Keycloak version to 23.0

- bpdm-orchestrator/src/main/kotlin/org/eclipse/tractusx/bpdm/orchestrator/config/PermissionConfigProperties.kt
- bpdm-orchestrator/src/main/resources/application.yml
- pom.xml
This pull request fixes the permission configuration in the application properties
> fix(Orchestrator): permission names and structure in the configuration

- charts/bpdm/CHANGELOG.md
- charts/bpdm/Chart.yaml
- charts/bpdm/charts/bpdm-cleaning-service-dummy/Chart.yaml
- charts/bpdm/charts/bpdm-gate/Chart.yaml
- charts/bpdm/charts/bpdm-orchestrator/Chart.yaml
- charts/bpdm/charts/bpdm-pool/Chart.yaml
- charts/bpdm/templates/keycloakRealmSecret.yaml
- charts/bpdm/values.yaml
> feat(charts): increase app version to 6.0.0-alpha.4

- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/config/GoldenRecordTaskConfiguration.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/generic/ConfidenceCriteriaDb.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/generic/IdentifierDb.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/repository/generic/BusinessPartnerRepository.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/BusinessPartnerMappings.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/BusinessPartnerService.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/GoldenRecordTaskService.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/GoldenRecordUpdateService.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/OrchestratorMappings.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/util/BusinessPartnerComparisonUtil.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/util/BusinessPartnerCopyUtil.kt
- bpdm-gate/src/main/resources/application.yml
- bpdm-gate/src/main/resources/db/migration/V6_0_0_5__add_LSA_identifiers.sql
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/BusinessPartnerControllerAndSharingControllerIT.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/BusinessPartnerControllerIT.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/entity/generic/BusinessPartnerIT.kt
- bpdm-gate/src/test/resources/application-test.yml
This pull request fixes the Gate's golden record update schedule. Making sure that updates from the golden record Pool are incorporated correctly into the business partner output data of the Gate.
> fix(Gate): not updating output data from golden record updates

- .github/workflows/trivy.yml
This pull request changes the Trivy workflow to not fail on any discovered issues. Failing the workflow on this trigger should indicates that there is something wrong with the workflow itself, which is not the case.
> cicd(Trivy): stop trivy workflow from failing on any issues

- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/GateSharingStateApi.kt
- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/client/SharingStateApiClient.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/controller/SharingStateController.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/auth/AuthTestBase.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/BusinessPartnerControllerAndSharingControllerIT.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/BusinessPartnerControllerIT.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/util/MockAndAssertUtils.kt
Removes the unused business partner type filter form the sharing state endpoint - making the OpenAPi documentation clearer.
> fix(gate): remove unused business partner type filter from sharing state

- bpdm-cleaning-service-dummy/src/main/resources/application-no-auth.yml
- bpdm-gate/src/main/resources/application-no-auth.yml
- bpdm-orchestrator/src/main/resources/application-no-auth.yml
- bpdm-pool/src/main/resources/application-no-auth.yml
> chore: add no-auth profile to all BPDM applications

- docker/cleaning-service-dummy/Dockerfile
- docker/gate/Dockerfile
- docker/orchestrator/Dockerfile
- docker/pool/Dockerfile
Removes modifiying the base image by installing wget. Removed also the healtcheck that was only possible by adding this package to the alpine base image.
fixes #924
> fix(docker): remove wget and health check from docker images

- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/response/BusinessPartnerDto.kt
- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/response/BusinessPartnerOutputDto.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/BusinessPartnerMappings.kt
This pull request fixes a bug in which the Gate refuses a business partner record without an alternative address.
> fix(gate): not accepting null value for alternative address

- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/repository/LegalEntityRepository.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/repository/LogisticAddressRepository.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/repository/SiteRepository.kt
This pull request fixes limitations in the name search of legal entities, sites and addresses.
Now the search
- is case-insensitive
- matches on parts of words
> fix(pool): name search behaviour

- README.md
- docs/api/README.md
- docs/decision-records/001-multitenancy_approach.md
- docs/decision-records/002-edc_for_pool_api.md
- docs/decision-records/003-orchestrator_serviceApi_vs_messagebus_approach.md
- docs/decision-records/004-openapi_descriptions.md
- docs/decision-records/005-edc-usage-for-third-party-services.md
- docs/developer/README.md
- docs/security-assessment/README.md
- docs/templates/README.md
- docs/templates/decision-record.md
- docs/templates/use-case.md
This pull request updates the copyright notice information for the BPDM documentation by adding SAP and Bosch to the notice.
Also added the copyright where it was missing previously.
> docs: update copyright notice in the BPDM documentation

- charts/bpdm/CHANGELOG.md
- charts/bpdm/Chart.yaml
- charts/bpdm/README.md
- charts/bpdm/charts/bpdm-cleaning-service-dummy/CHANGELOG.md
- charts/bpdm/charts/bpdm-cleaning-service-dummy/Chart.yaml
- charts/bpdm/charts/bpdm-cleaning-service-dummy/README.md
- charts/bpdm/charts/bpdm-gate/CHANGELOG.md
- charts/bpdm/charts/bpdm-gate/Chart.yaml
- charts/bpdm/charts/bpdm-gate/README.md
- charts/bpdm/charts/bpdm-orchestrator/CHANGELOG.md
- charts/bpdm/charts/bpdm-orchestrator/Chart.yaml
- charts/bpdm/charts/bpdm-orchestrator/README.md
- charts/bpdm/charts/bpdm-pool/CHANGELOG.md
- charts/bpdm/charts/bpdm-pool/Chart.yaml
- charts/bpdm/charts/bpdm-pool/README.md
This pull request updates the chart READMEs with default values descriptions
Fixes #925
> docs(charts): add default value descriptions to the README

- .github/workflows/kics.yml
> cicd: add kics scan to pull request checks

- .github/workflows/deploy-docker-all.yaml
- .github/workflows/deploy-docker.yaml
- docs/developer/README.md
This pull request createsdocker image tags based on maven versioning
- now only deploy docker images when the apps have been changed
- deploy snapshot or release version based on maven version
> cicd: create docker image tags based on maven versioning

- .github/workflows/helm-chart-release.yaml
This pull request changes the Charts release behaviour by only releasing the chart if it is a release version
- Charts should now have snapshot versions which prevent the chart from being released
For non-release versions we currently have no solution on where to deploy them. A candidate for this could be dockerhub. Alternatively something akin to a 'next' release could be a solution for  Chart SNAPSHOT versions as well.
> cicd: only release chart if it is a release version

- .github/workflows/helm-chart-release.yaml
This pull request fixes a typo in a shell script executed by the Github workflow to release helm charts. This caused the workflow to fail when checking for the Helm Chart version.
> ci(workflows): fix typo in helm chart release script

- CHANGELOG.md
- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/GatePartnerUploadApi.kt
- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/client/PartnerUploadApiClient.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/controller/PartnerUploadController.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/PartnerUploadService.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/auth/AuthAdminIT.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/auth/AuthInputConsumerIT.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/auth/AuthInputManagerIT.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/auth/AuthOutputConsumerIT.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/auth/AuthTestBase.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/auth/NoAuthIT.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/PartnerUploadControllerIT.kt
This pull request introduces new REST api endpoint in BPDM Gate. 
**New Feature**
- *GET Endpoint*: Provides the functionality to download a CSV template for business partner uploads, ensuring users have the correct format for data submission.
> feat(bpdm-gate): GET endpoint to download csv file template for business partner upload process.

- bpdm-common-test/src/main/kotlin/org/eclipse/tractusx/bpdm/test/testdata/pool/BusinessPartnerVerboseValues.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/BpnIssuingService.kt
- bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/controller/SiteControllerIT.kt
Including the BPN prefix into the checksum calculation .
It solves the issue : 
eclipse-tractusx/sig-release#699
> feat: Checksum change to include also the Prefix BPN(L-S-A)

- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/GatePartnerUploadApi.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/controller/PartnerUploadController.kt
Updated swagger documentation for business partner upload api and also removed unwanted dependencies. 
[700](https://github.com/eclipse-tractusx/sig-release/issues/700)
> docs(bpdm-gate): refactored swagger docs for partner upload api

- CONTRIBUTING.md
- LICENSES/CC-BY-4.0.txt
- LICENSE_non-code
- NOTICE.md
- Updated licensing and legal docs
#956 
> chore(TRG-7): update licensing and legal docs

- CHANGELOG.md
- bpdm-cleaning-service-dummy/pom.xml
- bpdm-common-test/pom.xml
- bpdm-common-test/src/main/kotlin/org/eclipse/tractusx/bpdm/test/testdata/pool/BusinessPartnerVerboseValues.kt
- bpdm-common/pom.xml
- bpdm-gate-api/pom.xml
- bpdm-gate/pom.xml
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/OrchestratorMappings.kt
- bpdm-orchestrator-api/pom.xml
- bpdm-orchestrator/pom.xml
- bpdm-pool-api/pom.xml
- bpdm-pool/pom.xml
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/BpnIssuingService.kt
- bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/controller/SiteControllerIT.kt
- pom.xml
This pull request includes hotfixes for the BPDM applications:
- Checksum for the BPN will now be correctly calculated from the whole BPN (including the prefix) eclipse-tractusx/sig-release#699
- BPDM Gate now correctly sends missing alternative addresses to the Orchestrator as NULL (This solves incorrect validation errors thrown by the Pool on the alternative address) eclipse-tractusx/portal-backend#801
> Patch Version Increase to 6.0.2

- charts/bpdm/CHANGELOG.md
- charts/bpdm/Chart.yaml
- charts/bpdm/README.md
- charts/bpdm/charts/bpdm-cleaning-service-dummy/CHANGELOG.md
- charts/bpdm/charts/bpdm-cleaning-service-dummy/Chart.yaml
- charts/bpdm/charts/bpdm-cleaning-service-dummy/README.md
- charts/bpdm/charts/bpdm-gate/CHANGELOG.md
- charts/bpdm/charts/bpdm-gate/Chart.yaml
- charts/bpdm/charts/bpdm-gate/README.md
- charts/bpdm/charts/bpdm-orchestrator/CHANGELOG.md
- charts/bpdm/charts/bpdm-orchestrator/Chart.yaml
- charts/bpdm/charts/bpdm-orchestrator/README.md
- charts/bpdm/charts/bpdm-pool/CHANGELOG.md
- charts/bpdm/charts/bpdm-pool/Chart.yaml
- charts/bpdm/charts/bpdm-pool/README.md
This pull request increases the BPDM charts app-version to 6.0.2
> build(charts): increase BPDM charts app-version to 6.0.2

- CHANGELOG.md
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/OrchestratorMappings.kt
This pull request adds fix from the 6.0.2 release for the Gate only sending non-null alternative addresses to the Orchestrator. #983
I also took over the Changelog entries for 6.0.2 into main.
> Cherry-Pick(release/6.0.x): Fix Gate Sending Alternative Address To Orchestrator

- CHANGELOG.md
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/BusinessPartnerService.kt
When upserting business partner input to the BPDM Gate that matches the existing business partner input, the Gate would still send the unchanged input data unnecessarily to the Golden Record Process. 
This pull request fixes this behaviour. Now the Gate only sends data to the Golden Record Process if it has been changed.
> fix(gate): Starting Golden Record Process Without Changes

- DEPENDENCIES
- pom.xml
This pull request sets the tomcat-embed-core to a higher version than found in the current Spring-Boot  starter in order to prevent security issues.
Resolves #993
> build(dep): increase tomcat-embed-core dependency version

- CHANGELOG.md
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/TaskCreationService.kt
When the Gate sends business partner data to the Orchestrator, it can happen that it saves the wrong golden record task-ID to the wrong sharing state, by this mixing up the desired results in the output stage. 
This pull request fixes the behaviour making sure that  the task-Ids are assigned to the correct sharing states as long as the Orchestrator returns the tasks in the order in which the requests have been received.
> fix(gate): Assigning Wrong Task-Ids

- .github/workflows/helm-chart-release.yaml
This pull request fixes a bug in our CICD pipeline when checking whether the current Chart is marked as a release version or not.
> ci(Release Chart): fix check for Chart release version

- .github/workflows/app-test-charts.yaml
- charts/bpdm/CHANGELOG.md
- charts/bpdm/Chart.yaml
- charts/bpdm/charts/bpdm-cleaning-service-dummy/CHANGELOG.md
- charts/bpdm/charts/bpdm-cleaning-service-dummy/values.yaml
- charts/bpdm/charts/bpdm-common/templates/_deployment.tpl
- charts/bpdm/charts/bpdm-gate/CHANGELOG.md
- charts/bpdm/charts/bpdm-gate/values.yaml
- charts/bpdm/charts/bpdm-orchestrator/CHANGELOG.md
- charts/bpdm/charts/bpdm-orchestrator/values.yaml
- charts/bpdm/charts/bpdm-pool/CHANGELOG.md
- charts/bpdm/charts/bpdm-pool/values.yaml
This pull request introduces a new value to delay the startup of the BPDM application containers.
This feature is helpful for environments which have limited resources like the Kind cluster setup in the Github workflows where we discovered that the install may take more than 10 minutes due to repeated crash loop backs.
> feat(Charts):  Delay Container Startup

- CHANGELOG.md
- bpdm-cleaning-service-dummy/src/test/kotlin/org/eclipse/tractusx/bpdm/cleaning/service/CleaningServiceApiCallsTest.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/SharingStateDb.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/OrchestratorMappings.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/SharingStateService.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/TaskCreationService.kt
- bpdm-gate/src/main/resources/db/migration/V6_1_0_4__add_orchestrator_record_id.sql
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/entity/generic/BusinessPartnerIT.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/util/MockAndAssertUtils.kt
- bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/model/TaskClientStateDto.kt
- bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/model/TaskCreateRequestEntry.kt
- bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/model/TaskStepReservationEntryDto.kt
- bpdm-orchestrator/src/main/kotlin/org/eclipse/tractusx/bpdm/orchestrator/controller/GoldenRecordTaskController.kt
- bpdm-orchestrator/src/main/kotlin/org/eclipse/tractusx/bpdm/orchestrator/entity/DbTimestampConverter.kt
- bpdm-orchestrator/src/main/kotlin/org/eclipse/tractusx/bpdm/orchestrator/entity/GateRecordDb.kt
- bpdm-orchestrator/src/main/kotlin/org/eclipse/tractusx/bpdm/orchestrator/entity/GoldenRecordTaskDb.kt
- bpdm-orchestrator/src/main/kotlin/org/eclipse/tractusx/bpdm/orchestrator/exception/BpdmRecordNotFoundException.kt
- bpdm-orchestrator/src/main/kotlin/org/eclipse/tractusx/bpdm/orchestrator/repository/GateRecordRepository.kt
- bpdm-orchestrator/src/main/kotlin/org/eclipse/tractusx/bpdm/orchestrator/service/GoldenRecordTaskService.kt
- bpdm-orchestrator/src/main/kotlin/org/eclipse/tractusx/bpdm/orchestrator/service/GoldenRecordTaskStateMachine.kt
- bpdm-orchestrator/src/main/kotlin/org/eclipse/tractusx/bpdm/orchestrator/service/ResponseMapper.kt
- bpdm-orchestrator/src/main/resources/db/migration/V6_1_0_0__create_tables.sql
- bpdm-orchestrator/src/test/kotlin/org/eclipse/tractusx/bpdm/orchestrator/controller/GoldenRecordTaskControllerIT.kt
- bpdm-orchestrator/src/test/kotlin/org/eclipse/tractusx/bpdm/orchestrator/service/GoldenRecordTaskStateMachineIT.kt
- bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/service/TaskStepFetchAndReserveServiceTest.kt
This pull request adds a gate record ID to the Orchestrator tasks. By this, tasks belonging to the same gate record can be identified by the cleaning services.
Implements eclipse-tractusx/sig-release#711
> Feat: Add Record ID to Golden Record Tasks

- .github/workflows/chart-test-lint.yaml
- .github/workflows/helm-chart-release.yaml
- CHANGELOG.md
- bpdm-cleaning-service-dummy/pom.xml
- bpdm-common-test/pom.xml
- bpdm-common/pom.xml
- bpdm-gate-api/pom.xml
- bpdm-gate/pom.xml
- bpdm-orchestrator-api/pom.xml
- bpdm-orchestrator/pom.xml
- bpdm-pool-api/pom.xml
- bpdm-pool/pom.xml
- charts/bpdm/CHANGELOG.md
- charts/bpdm/Chart.yaml
- charts/bpdm/charts/bpdm-cleaning-service-dummy/CHANGELOG.md
- charts/bpdm/charts/bpdm-cleaning-service-dummy/Chart.yaml
- charts/bpdm/charts/bpdm-gate/CHANGELOG.md
- charts/bpdm/charts/bpdm-gate/Chart.yaml
- charts/bpdm/charts/bpdm-orchestrator/CHANGELOG.md
- charts/bpdm/charts/bpdm-orchestrator/Chart.yaml
- charts/bpdm/charts/bpdm-pool/CHANGELOG.md
- charts/bpdm/charts/bpdm-pool/Chart.yaml
- pom.xml
This pull request increases the App version to release 6.1.0.
Also the corresponding Chart Version is increases to release version 5.1.0.
Adapted versions of the Maven POM and Chart.yml, also adapted the Changelogs.
> build(version): increase BPDM app version to 6.1.0 (RELEASE)

- charts/bpdm/CHANGELOG.md
- charts/bpdm/Chart.yaml
- charts/bpdm/charts/bpdm-cleaning-service-dummy/CHANGELOG.md
- charts/bpdm/charts/bpdm-cleaning-service-dummy/Chart.yaml
- charts/bpdm/charts/bpdm-cleaning-service-dummy/values.yaml
- charts/bpdm/charts/bpdm-gate/CHANGELOG.md
- charts/bpdm/charts/bpdm-gate/Chart.yaml
- charts/bpdm/charts/bpdm-gate/values.yaml
- charts/bpdm/charts/bpdm-pool/CHANGELOG.md
- charts/bpdm/charts/bpdm-pool/Chart.yaml
- charts/bpdm/charts/bpdm-pool/values.yaml
Fixed faulty configuration of subcharts that comes into effect when deploying the subchart directly or using the BPDM chart as a dependency in another chart. For anyone using the BPDM chart directly this will have no impact.
> fix(chart): faulty default configuration in subcharts

- .gitignore
- DEPENDENCIES
- bpdm-cleaning-service-dummy/pom.xml
- bpdm-common-test/pom.xml
- bpdm-common/pom.xml
- bpdm-gate-api/pom.xml
- bpdm-gate/pom.xml
- bpdm-orchestrator-api/pom.xml
- bpdm-orchestrator/pom.xml
- bpdm-pool-api/pom.xml
- bpdm-pool/pom.xml
- charts/bpdm/CHANGELOG.md
- charts/bpdm/Chart.yaml
- charts/bpdm/charts/bpdm-cleaning-service-dummy/Chart.yaml
- charts/bpdm/charts/bpdm-gate/Chart.yaml
- charts/bpdm/charts/bpdm-orchestrator/Chart.yaml
- charts/bpdm/charts/bpdm-pool/Chart.yaml
- pom.xml
This pull request makes the maven build more CI friendly and eases the effort when upgrading the BPDM app version.
- include revision property in parent pom
- child modules now refer to parent pom version by revision property
- also clean pom dependencies
for more info visit https://maven.apache.org/maven-ci-friendly.html
> build: make pom more CI friendly by using Maven revision property

- .github/workflows/trivy.yml
Currently, the scheduled trivy job analyzes tags which are not updated anymore. Also, since we already perform trivy scans on the pull requests we already find vulnerabilities early for snapshot versions. That is why I think the scheduled trivy job should rather work on the latest released version, making sure that in the current release are no critical vulnerabilties.
> ci(trivy): let trivy regularly check latest containers

- bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/service/BusinessPartnerComparator.kt
This pull request fixes a possible null exception in Pool tests when comparing dates of expected and actual business partnert data. If one of those dates is null and the other is not (currently not happening during tests) a null-Exception would be thrown.
This potential Null Exception leads to a comilation error in #948 
It seems like the new kotlin compiler is able to detect this potentional null-expection where the old one did not.
> test(Pool): fix possible null exception in Pool tests

- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/BusinessPartnerService.kt
This pull request fixes a bug in which completely blank business partner input data is not persisted into the database.
Fixes #1019 
> fix(Gate): not persisting completely blank business partner input data

- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/OrchestratorMappings.kt
This pull request fixes a bug in which a Gate which has a owner BPNL assigned will always send that owner's BPNL to the golden record process. Now the Gate will only assign the owner BPNL if it the data is marked as owned company data; even if the Gate has a fixed owner assigned.
> fix(Gate): Always Sending Owner BPNL on Owned Gate

- CHANGELOG.md
- bpdm-common-test/src/main/kotlin/org/eclipse/tractusx/bpdm/test/testdata/pool/BusinessPartnerNonVerboseValues.kt
- bpdm-common-test/src/main/kotlin/org/eclipse/tractusx/bpdm/test/testdata/pool/BusinessPartnerRequestFactory.kt
- bpdm-common-test/src/main/kotlin/org/eclipse/tractusx/bpdm/test/testdata/pool/BusinessPartnerVerboseValues.kt
- bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/PoolSiteApi.kt
- bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/client/SiteApiClient.kt
- bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/model/request/SiteCreateRequestWithLegalAddressAsMain.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/controller/SiteController.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/BusinessPartnerBuildService.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/TaskStepBuildService.kt
- bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/auth/AuthTestBase.kt
- bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/controller/SiteControllerIT.kt
- charts/bpdm/Chart.yaml
- charts/bpdm/charts/bpdm-cleaning-service-dummy/Chart.yaml
- charts/bpdm/charts/bpdm-gate/Chart.yaml
- charts/bpdm/charts/bpdm-orchestrator/Chart.yaml
- charts/bpdm/charts/bpdm-pool/Chart.yaml
- pom.xml
What does this PR introduce? 
- Create an endpoint to create site entity
- Create SiteCreateRequestWithLegalAddressAsMain in bpdm-pool-api module
- Add test cases which cover the new code
- This PR solve the https://github.com/eclipse-tractusx/sig-release/issues/739.
Does it fix a bug? 
- Nope
Does it add a new feature?
- Yes
> feat(LegalSiteAPI): New endpoint to create legal site reference

- CHANGELOG.md
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/TaskCreationServices.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/TaskResolutionServices.kt
This pull request fixes a bug in which the Gate can run out of memory when trying to process a large amount of golden records during scheduling.
> fix(Gate): Possible out of memory exception

- CHANGELOG.md
- bpdm-gate/src/main/resources/application.yml
- bpdm-pool/src/main/resources/application.yml
Request sizes can be quite big when interacting with the golden record process due to large business partner data. This may lead to exceptions when the used clients do not support such big request sizes. 
Therefore this pull request reduces the standard batch size for golden record task processing in the Gate and Pool.
> fix(config): lower the standard batch sizes 

- CHANGELOG.md
- bpdm-orchestrator/src/main/kotlin/org/eclipse/tractusx/bpdm/orchestrator/repository/GoldenRecordTaskRepository.kt
- bpdm-orchestrator/src/main/kotlin/org/eclipse/tractusx/bpdm/orchestrator/service/GoldenRecordTaskService.kt
- bpdm-orchestrator/src/main/kotlin/org/eclipse/tractusx/bpdm/orchestrator/service/TimeoutProcessBatchService.kt
This pull request introduces pagination for handling pending and retention timeouts in the orchestrator. By processing tasks in manageable batches, the changes prevent out-of-memory errors during the execution of large volumes of tasks, improving the system's stability and efficiency.
> fix(bpdm-orchestrator): introduced pagination for handling pending and retention timeouts

- CHANGELOG.md
- bpdm-cleaning-service-dummy/src/main/kotlin/org/eclipse/tractusx/bpdm/cleaning/service/CleaningServiceDummy.kt
This pull request now  makes the cleaning service dummy add whitespace between name parts when creating legal name from them. This only happens when no legal name has been given.
> fix(Cleaning Dummy): Add Whitespaces For Legal Name 

- .github/workflows/trufflehog.yml
This PR updated the copyright header and provide minor fix on scan for new pull requests.
> chore: Updated trufflehog secret scanning workflow

- CHANGELOG.md
- bpdm-orchestrator/src/main/kotlin/org/eclipse/tractusx/bpdm/orchestrator/entity/GoldenRecordTaskDb.kt
- bpdm-orchestrator/src/main/kotlin/org/eclipse/tractusx/bpdm/orchestrator/repository/GoldenRecordTaskRepository.kt
- bpdm-orchestrator/src/main/kotlin/org/eclipse/tractusx/bpdm/orchestrator/service/GoldenRecordTaskService.kt
- bpdm-orchestrator/src/main/kotlin/org/eclipse/tractusx/bpdm/orchestrator/service/GoldenRecordTaskStateMachine.kt
- bpdm-orchestrator/src/main/kotlin/org/eclipse/tractusx/bpdm/orchestrator/service/ResponseMapper.kt
- bpdm-orchestrator/src/main/resources/db/migration/V6_2_0_0__add_abort_status_check.sql
- bpdm-orchestrator/src/test/kotlin/org/eclipse/tractusx/bpdm/orchestrator/controller/GoldenRecordTaskControllerIT.kt
- bpdm-orchestrator/src/test/kotlin/org/eclipse/tractusx/bpdm/orchestrator/service/GoldenRecordTaskStateMachineIT.kt
In this pull request the Orchestrator now aborts tasks with outdated business partner data information from the sharing members. On creating new tasks the Gate will check for currently pending tasks for the same record and abort them.
An aborted task counts as a finished tasks and will be removed by the retention timeout check.
> feat(Orchestrator): now aborts outdated tasks

- .github/workflows/deploy-docker.yaml
chore(workflows): allow for deploying any kind of non-snapshot pre-release deployment
Now distinguished between 3 cases:
- RELEASE: no pre-release suffix, make full list of version tags
- SNAPSHOT: SNAPSHOT pre-release suffix, create latest and patch version tag
- PRE-RELEASE: any other pre-release suffix, only create patch version tag (intended for release candidate versions with numbered 'rc' as suffix)
Currently, we can only deploy full releases or SNAPSHOT releases. However, the behaviour of our SNAPSHOT releases is to override tags always to the newest version. This works for SNAPSHOTs but it is still nice to use fixed pre-release tags that stay long term and are not overwritten.
> chore(workflows): Pre-release docker tags

- CHANGELOG.md
- bpdm-common-test/src/main/kotlin/org/eclipse/tractusx/bpdm/test/testdata/gate/BusinessPartnerGenericCommonValues.kt
- bpdm-common-test/src/main/kotlin/org/eclipse/tractusx/bpdm/test/testdata/gate/BusinessPartnerVerboseValues.kt
- bpdm-common-test/src/main/kotlin/org/eclipse/tractusx/bpdm/test/testdata/orchestrator/BusinessPartnerTestDataFactory.kt
- bpdm-common-test/src/main/kotlin/org/eclipse/tractusx/bpdm/test/testdata/pool/BusinessPartnerRequestFactory.kt
- bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/dto/GeoCoordinateDto.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/GeographicCoordinateDb.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/model/upsert/output/GeoCoordinate.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/util/PartnerFileUtil.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/entity/generic/BusinessPartnerIT.kt
- bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/model/BusinessPartner.kt
- bpdm-orchestrator/src/main/kotlin/org/eclipse/tractusx/bpdm/orchestrator/entity/PostalAddressDb.kt
- bpdm-orchestrator/src/main/resources/db/migration/V6_2_0_2__update_geographical_coordinates_type.sql
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/entity/GeographicCoordinateDb.kt
In this pull request, updated double precision data type for geographical coordinate  attributes like longitude, latitude and altitude in all bpdm services. 
Reason  to choose Double as data type - 
-  FLOAT and float4: Essentially the same in most cases, providing 32-bit floating-point precision (~6-7 decimal digits). But rounding issue still persisted with Float data type.
-  String: Using Strings could lead to performance overheads, particularly when performing calculations or comparisons between coordinates. 
- Double: This will give you higher precision and help avoid rounding issues.
Fixes #978 
> fix(bpdm): updated double precision data type for Geographic-data

- CHANGELOG.md
- bpdm-common-test/src/main/kotlin/org/eclipse/tractusx/bpdm/test/testdata/gate/BusinessPartnerVerboseValues.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/OutputUpsertMappings.kt
In previous implementation, the value for Tax Jurisdiction code was appearing as null due to missing mapping for output.
In this pull request, we have enabled Tax Jurisdiction code to save it to the Output on BPDM Gate service.
> fix(bpdm-gate): Add Tax Jurisdiction code to save it to the Output

- CHANGELOG.md
- bpdm-cleaning-service-dummy/src/main/kotlin/org/eclipse/tractusx/bpdm/cleaning/service/CleaningServiceDummy.kt
In this pull request, we have refactored the logic while constructing legal name for business partner.
This change will avoid setting empty value for legal name in clearning process so eventually, this will not allow sharing member to provide business partner data for their legal entity without nameparts or legal entity name(either of both must be shared while performing GR process). 
> fix(bpdm-clearing): refactored legal name construction logic

- CHANGELOG.md
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/util/BusinessPartnerCopyUtil.kt
In this pull request, we are adding business partner type while constructing state and identifiers for business partner input. 
With this changes, states and identifiers will be maintained correctly even after update on business partner data.
> fix(bpdm-gate): refactored construction logic for states in business partner

- bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/util/WebClientProvider.kt
- bpdm-orchestrator/src/main/kotlin/org/eclipse/tractusx/bpdm/orchestrator/entity/BusinessStateDb.kt
- bpdm-orchestrator/src/main/kotlin/org/eclipse/tractusx/bpdm/orchestrator/entity/ConfidenceCriteriaDb.kt
- bpdm-orchestrator/src/main/kotlin/org/eclipse/tractusx/bpdm/orchestrator/entity/DbTimestamp.kt
- bpdm-orchestrator/src/main/kotlin/org/eclipse/tractusx/bpdm/orchestrator/entity/DbTimestampConverter.kt
- bpdm-orchestrator/src/main/kotlin/org/eclipse/tractusx/bpdm/orchestrator/entity/GoldenRecordTaskDb.kt
- bpdm-orchestrator/src/main/kotlin/org/eclipse/tractusx/bpdm/orchestrator/repository/GoldenRecordTaskRepository.kt
- bpdm-orchestrator/src/main/kotlin/org/eclipse/tractusx/bpdm/orchestrator/service/GoldenRecordTaskService.kt
- bpdm-orchestrator/src/main/kotlin/org/eclipse/tractusx/bpdm/orchestrator/service/GoldenRecordTaskStateMachine.kt
- bpdm-orchestrator/src/main/resources/application.yml
- bpdm-orchestrator/src/main/resources/db/migration/V6_2_0_3__add_indexes_on_foreign_keys.sql
- bpdm-orchestrator/src/test/kotlin/org/eclipse/tractusx/bpdm/orchestrator/performance/OrchestratorPerformanceIT.kt
This pull request increases the performance of the Orchestrator's access to the database, improving the speed for querying and inserting tasks:
- Exchanged the attribute converter for entity timestamps to a hibernate type mapper
- introduced hibernate configuration for speeding up inserting and updating
- increased codec size for BPDM webclients to support the Orchestrator's upsert limit
- Made element collection fetching lazy
- Made use of PSQL JOIN FETCH statements for the lazy element collections
- Add indexes for the element collection's join column
- Add a test for measuring the Orchestrator's performance in saving and querying tasks
> perf(Orchestrator): increase performance for database access

- CHANGELOG.md
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/BusinessPartnerMappings.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/BusinessPartnerControllerAndSharingControllerIT.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/BusinessPartnerControllerIT.kt
In this pull request, we have fixed issue where we were retrieving identifiers for all categorise of business partner in output stage.
> fix(bpdm-gate): refactored logic for identifiers on output business partners

- bpdm-cleaning-service-dummy/src/main/kotlin/org/eclipse/tractusx/bpdm/cleaning/config/CleaningServiceConfigProperties.kt
- bpdm-cleaning-service-dummy/src/main/kotlin/org/eclipse/tractusx/bpdm/cleaning/service/CleaningServiceDummy.kt
- bpdm-cleaning-service-dummy/src/main/resources/application.yml
- bpdm-cleaning-service-dummy/src/test/kotlin/org/eclipse/tractusx/bpdm/cleaning/service/CleaningServiceApiCallsTest.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/util/MockAndAssertUtils.kt
- bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/ApiCommons.kt
- bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/GoldenRecordTaskApi.kt
- bpdm-orchestrator/src/main/kotlin/org/eclipse/tractusx/bpdm/orchestrator/config/PermissionConfigProperties.kt
- bpdm-orchestrator/src/main/kotlin/org/eclipse/tractusx/bpdm/orchestrator/config/StateMachineConfig.kt
- bpdm-orchestrator/src/main/kotlin/org/eclipse/tractusx/bpdm/orchestrator/config/StateMachineConfigProperties.kt
- bpdm-orchestrator/src/main/kotlin/org/eclipse/tractusx/bpdm/orchestrator/controller/GoldenRecordTaskController.kt
- bpdm-orchestrator/src/main/kotlin/org/eclipse/tractusx/bpdm/orchestrator/service/GoldenRecordTaskStateMachine.kt
- bpdm-orchestrator/src/main/kotlin/org/eclipse/tractusx/bpdm/orchestrator/service/StepSecurityService.kt
- bpdm-orchestrator/src/main/resources/application.yml
- bpdm-orchestrator/src/test/kotlin/org/eclipse/tractusx/bpdm/orchestrator/auth/AuthAdminIT.kt
- bpdm-orchestrator/src/test/kotlin/org/eclipse/tractusx/bpdm/orchestrator/auth/AuthTaskCreatorIT.kt
- bpdm-orchestrator/src/test/kotlin/org/eclipse/tractusx/bpdm/orchestrator/auth/AuthTaskProcessorCleanIT.kt
- bpdm-orchestrator/src/test/kotlin/org/eclipse/tractusx/bpdm/orchestrator/auth/AuthTaskProcessorPoolTaskProcessingJobApiSyncIT.kt
- bpdm-orchestrator/src/test/kotlin/org/eclipse/tractusx/bpdm/orchestrator/auth/AuthTestBase.kt
- bpdm-orchestrator/src/test/kotlin/org/eclipse/tractusx/bpdm/orchestrator/auth/NoAuthIT.kt
- bpdm-orchestrator/src/test/kotlin/org/eclipse/tractusx/bpdm/orchestrator/controller/GoldenRecordTaskControllerIT.kt
- bpdm-orchestrator/src/test/kotlin/org/eclipse/tractusx/bpdm/orchestrator/controller/GoldenRecordTaskEventControllerIT.kt
- bpdm-orchestrator/src/test/kotlin/org/eclipse/tractusx/bpdm/orchestrator/performance/OrchestratorPerformanceIT.kt
- bpdm-orchestrator/src/test/kotlin/org/eclipse/tractusx/bpdm/orchestrator/service/GoldenRecordTaskStateMachineIT.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/TaskResolutionService.kt
- bpdm-pool/src/main/resources/application.yml
- docs/developer/README.md
This pull request makes task steps configuration easier to adjust
- Extract the Orchestrator's state machine logic to a configuration
- Remove references to explicit steps in the test cases
- Make the step referenced in the Cleaning Service Dummy configurable
- Make the step referenced in the Pool configurable
- Document how to adjust the golden record process steps in code
Solves #1078
> Refactor: Make Task Steps Configuration Easier

- charts/bpdm/Chart.yaml
- charts/bpdm/charts/bpdm-cleaning-service-dummy/Chart.yaml
- charts/bpdm/charts/bpdm-common/Chart.yaml
- charts/bpdm/charts/bpdm-common/templates/_deployment.tpl
- charts/bpdm/charts/bpdm-common/templates/_helpers.tpl
- charts/bpdm/charts/bpdm-gate/Chart.yaml
- charts/bpdm/charts/bpdm-orchestrator/Chart.yaml
- charts/bpdm/charts/bpdm-pool/Chart.yaml
- charts/bpdm/charts/bpdm-pool/values.yaml
- charts/bpdm/values.yaml
- pom.xml
This pull request makes it possible to disable the postgres and the central-idp subcharts in the BPDM charts by fixing the default configuration. Now BPDM Charts can be deployed without having to deploy to its own postgres and central-idp next to it. If these subcharts are disabled it is necessary to specify an external postgres and central-idp in the Charts application configurations.
In order to work this fix now makes subcharts referenced by fullnameOverrides instead of just nameOverrides
Solves #1086
> fix(charts): error on disabling subcharts

- bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/config/LandingPageConfig.kt
In this pull request, made SwaggerUiConfigProperties optional in LandingPageConfig.
- Updated LandingPageConfig to accept a nullable SwaggerUiConfigProperties dependency
- Added null check in addViewControllers to handle cases where SwaggerUiConfigProperties is not available
- Ensures application can start without requiring SwaggerUiConfigProperties, improving flexibility in test and non-Swagger environments
> feat(bpdm-common): SwaggerUiConfigProperties optional in Landing Page

- CHANGELOG.md
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/BusinessPartnerMappings.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/BusinessPartnerControllerAndSharingControllerIT.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/BusinessPartnerControllerIT.kt
In this pull request, we have fixed logic for gate output stage to retrieve states based on business partner type.
> fix(bpdm-gate): output stage to only provide states based on business partner type

- CHANGELOG.md
- bpdm-cleaning-service-dummy/src/main/kotlin/org/eclipse/tractusx/bpdm/cleaning/service/CleaningServiceDummy.kt
- bpdm-cleaning-service-dummy/src/test/kotlin/org/eclipse/tractusx/bpdm/cleaning/service/CleaningServiceApiCallsTest.kt
In this pull request, we have assigned emptylist to the uncategorized collection while performing cleaning task process.
Ideally in cleaning process, Identifiers are being taken as legal identifiers and should be removed from uncategorized collection.
> fix(bpdm-cleaning): Removed assignment of uncategorized identifier while performing cleaning task process.

- docs/api/gate.json
- docs/api/gate.yaml
This pull request updates the outdated open api documentation for the Gate snapshot version of 6.2.0
> docs(api): update gate open-api docs to current 6.2.0-SNAPSHOT version

- docs/api/gate.json
- docs/api/gate.yaml
- docs/api/orchestrator.json
- docs/api/orchestrator.yaml
- docs/api/pool.json
- docs/api/pool.yaml
In this pull request, we have updated open api specification document for all services in bpdm including Pool, Gate and Orchestrator as per release candidate version 5. 
> docs(bpdm): update openApi spec for rc5

- docs/postman/EDC Provider Setup.postman_collection.json
This pull request updates the EDC provider setup postman collection to be compatible with the EDC version 0.8.0 and the new DataExchangeGovernance framework credential. The new credential replaces the outdated businesspartner framework credential for release 24/08 and below.
Also changed the access policy for offer Pool member access to be BPN based, replacing the more generic IsMember policy. That way we now create an offer to access the Pool for each sharing member separately instead of having one for all.
Fixes #1044 
Contributes to #1082 
> docs(Postman): update EDC provider setup collection

- .github/workflows/app-test-charts.yaml
This pull request raises the Kubernetes version on which we perform Chart tests to the newest release v1.31 on default.
Contributes to #1082
> cicd(Chart Test): upgrade the default kubernetes version to 1.31

- bpdm-cleaning-service-dummy/pom.xml
- bpdm-orchestrator/pom.xml
- charts/bpdm/Chart.yaml
- charts/bpdm/charts/bpdm-cleaning-service-dummy/Chart.yaml
- charts/bpdm/charts/bpdm-gate/Chart.yaml
- charts/bpdm/charts/bpdm-orchestrator/Chart.yaml
- charts/bpdm/charts/bpdm-pool/Chart.yaml
- pom.xml
In this pull request, we have updated legal docs for orchestrator and cleaning service dummy to include license, notice and dependency details while building resource. 
Also, we have made change for application version.
> docs(bpdm):updated legal docs for cleaning and orchestrator service with snapshot version

- CHANGELOG.md
- charts/bpdm/CHANGELOG.md
- charts/bpdm/Chart.yaml
- charts/bpdm/charts/bpdm-cleaning-service-dummy/CHANGELOG.md
- charts/bpdm/charts/bpdm-cleaning-service-dummy/Chart.yaml
- charts/bpdm/charts/bpdm-gate/CHANGELOG.md
- charts/bpdm/charts/bpdm-gate/Chart.yaml
- charts/bpdm/charts/bpdm-orchestrator/CHANGELOG.md
- charts/bpdm/charts/bpdm-orchestrator/Chart.yaml
- charts/bpdm/charts/bpdm-pool/CHANGELOG.md
- charts/bpdm/charts/bpdm-pool/Chart.yaml
- docs/api/gate.json
- docs/api/gate.yaml
- docs/api/orchestrator.json
- docs/api/orchestrator.yaml
- docs/api/pool.json
- docs/api/pool.yaml
- pom.xml
This pull raises the BPDM apps and Helm Charts from SNAPSHOT to its release versions:
BPDM 6.2.0 and BPDM Charts 5.2.0
Upon merging this also marks the release of these version.
> build: BPDM app version 6.2.0 - Helm Chart version 5.2.0

- CHANGELOG.md
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/PartnerUploadService.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/util/PartnerFileUtil.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/PartnerUploadControllerIT.kt
In this pull request, we have added functionality for getting Legal Name from Pool service while performing partner upload process via CSV file. As per the standards, we should have legal name attached and now we are fetching legal name for particular legal entity based on tenantBpnl(User BPNL).
Fixes #1141 
> fix(bpdm-gate): fetched and attached legal name of entity while performing partner upload process.

- CHANGELOG.md
- bpdm-orchestrator/src/main/kotlin/org/eclipse/tractusx/bpdm/orchestrator/service/GoldenRecordTaskStateMachine.kt
- bpdm-orchestrator/src/test/kotlin/org/eclipse/tractusx/bpdm/orchestrator/controller/GoldenRecordTaskControllerIT.kt
- bpdm-orchestrator/src/test/kotlin/org/eclipse/tractusx/bpdm/orchestrator/service/GoldenRecordTaskStateMachineIT.kt
This pull request changes the Orchestrator's behaviour when receiving resolutions for already resolved steps for a task.
- return 200 status code when posting resolution already resolved steps ignoring the content
- adapted tests
> feat(Orchestrator): ignore resolutions for already resolved steps

- CHANGELOG.md
- DEPENDENCIES
- bpdm-common-test/src/main/kotlin/org/eclipse/tractusx/bpdm/test/testdata/pool/BusinessPartnerVerboseValues.kt
- bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/PoolBpnApi.kt
- bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/client/BpnApiClient.kt
- bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/model/request/BpnRequestIdentifierSearchRequest.kt
- bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/model/response/BpnRequestIdentifierMappingDto.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/controller/BpnController.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/BusinessPartnerFetchService.kt
- bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/controller/BpnControllerIT.kt
- docs/api/pool.json
- docs/api/pool.yaml
This PR introduces a new endpoint that returns the BPNL/S/A based on the provided request identifiers.
For more information, please refer to https://github.com/eclipse-tractusx/bpdm/issues/1052.
> feat: endpoint to return bpnl/s/a based on the requested identifiers

- CHANGELOG.md
- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/exception/GateErrorCodes.kt
- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/response/SharingStateDto.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/TaskResolutionServices.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/BusinessPartnerControllerAndSharingControllerIT.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/BusinessPartnerControllerIT.kt
- bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/model/TaskErrorDto.kt
- bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/model/TaskErrorType.kt
- bpdm-orchestrator/src/main/resources/db/migration/V6_3_0_0__add_extend_error_code.sql
- docs/api/gate.yaml
- docs/api/orchestrator.yaml
Enhance the error handling mechanism for the orchestrator and gate components by extending the list of available error codes. This will improve the visibility and detail of error information, particularly beneficial for the customer dashboard to understand why a data set could not be processed.
Currently, the orchestrator and gate components have a limited set of error codes. Extending these error codes will provide more granular information on processing failures, aiding in quicker diagnosis and resolution. This feature will update both the orchestrator and gate components to support a more comprehensive list of error codes.
Benefits
- Improved Transparency: Customers can view detailed error reasons on the dashboard, enhancing trust and user experience.
- Enhanced Debugging: Developers …
> feat(bpdm-gate): Extend error code

- pom.xml
This pull request specifies the kotlin API and language version explicitely in the parent POM. From my observations this can help development tools like Intellij. After this it should be possible to configure the project with kotlin 2.1.
Build fix for supporting intellij:
https://youtrack.jetbrains.com/issue/KTIJ-29648/Kotlin-Compiler-ignores-API-version-and-gives-experimental-API-usage-error
> build(pom): explicitly specify kotlin api and language version

- CHANGELOG.md
- DEPENDENCIES
- bpdm-system-tester/README.md
- bpdm-system-tester/pom.xml
- bpdm-system-tester/src/main/kotlin/org/eclipse/tractusx/bpdm/test/system/Application.kt
- bpdm-system-tester/src/main/kotlin/org/eclipse/tractusx/bpdm/test/system/config/GateClientConfig.kt
- bpdm-system-tester/src/main/kotlin/org/eclipse/tractusx/bpdm/test/system/config/PoolClientConfig.kt
- bpdm-system-tester/src/main/kotlin/org/eclipse/tractusx/bpdm/test/system/config/TestDataConfiguration.kt
- bpdm-system-tester/src/main/kotlin/org/eclipse/tractusx/bpdm/test/system/config/TestRunData.kt
- bpdm-system-tester/src/main/kotlin/org/eclipse/tractusx/bpdm/test/system/stepdefinations/ShareGenericNoBpnStepDefs.kt
- bpdm-system-tester/src/main/kotlin/org/eclipse/tractusx/bpdm/test/system/stepdefinations/SpringTestRunConfiguration.kt
- bpdm-system-tester/src/main/kotlin/org/eclipse/tractusx/bpdm/test/system/utils/GateInputFactory.kt
- bpdm-system-tester/src/main/kotlin/org/eclipse/tractusx/bpdm/test/system/utils/GateOutputFactory.kt
- bpdm-system-tester/src/main/kotlin/org/eclipse/tractusx/bpdm/test/system/utils/StepUtils.kt
- bpdm-system-tester/src/main/resources/application.yml
- bpdm-system-tester/src/main/resources/cucumber.properties
- bpdm-system-tester/src/main/resources/cucumber/share_generic_business_partner.feature
- pom.xml
In this pull request, we have created golden record process tester application.
The application can be executed and also packaged as a JAR as usual.
> feat(bpdm-system-test): golden record tester module.

- CHANGELOG.md
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/TaskEntryBpnMapping.kt
- bpdm-pool/src/main/resources/db/migration/V6_3_0_0__fix_request_identifier_uc.sql
- bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/controller/BpnControllerIT.kt
- bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/controller/ChangelogControllerIT.kt
This pull request fixes the Pool's behaviour of creating duplicate BPN request identifier mapping entries
- Remove duplicate BPN request identifier mappings form the database
- Prevent creation of new duplicates
- Fix the request identifier unique constraint so that an exception will be thrown when a duplicate entry tries to be created in the database (just for data integrity, should not happen in normal logic)
Fixes #1159
In order to check the behaviour you can create a business partner with site information via the Gate, full golden record process. Then provide an update to that business partner without changing the names or BPNs (for example change a small field in the address). Look into the database, there should be no duplicate entries. In the previous version you should see a …
> fix(Pool): duplicate BPN request identifier mapping entries

- CHANGELOG.md
- bpdm-cleaning-service-dummy/src/main/kotlin/org/eclipse/tractusx/bpdm/cleaning/config/DependencyHealthScheduler.kt
- bpdm-cleaning-service-dummy/src/main/kotlin/org/eclipse/tractusx/bpdm/cleaning/config/OrchestratorClientConfig.kt
- bpdm-cleaning-service-dummy/src/main/kotlin/org/eclipse/tractusx/bpdm/cleaning/service/DependencyHealthService.kt
- bpdm-cleaning-service-dummy/src/main/kotlin/org/eclipse/tractusx/bpdm/cleaning/util/CleaningServiceStartupListner.kt
- bpdm-cleaning-service-dummy/src/main/kotlin/org/eclipse/tractusx/bpdm/cleaning/util/OrchestratorHealthIndicator.kt
- bpdm-cleaning-service-dummy/src/main/resources/application.yml
- bpdm-cleaning-service-dummy/src/test/kotlin/org/eclipse/tractusx/bpdm/cleaning/config/MockHealthIndicatorConfig.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/config/DependencyHealthScheduler.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/DependencyHealthService.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/util/GateServiceStartupListener.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/util/OrchestratorHealthIndicator.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/util/PoolHealthIndicator.kt
- bpdm-gate/src/main/resources/application.yml
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/config/MockHealthIndicatorConfig.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/config/DependencyHealthScheduler.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/config/OrchestratorClientConfig.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/DependencyHealthService.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/util/OrchestratorHealthIndicator.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/util/PoolServiceStartupListner.kt
- bpdm-pool/src/main/resources/application.yml
- bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/config/MockHealthIndicatorConfig.kt
This pull request adds dependancy check for services in bpdm as below,
Contributes to [#1161](https://github.com/eclipse-tractusx/bpdm/issues/1161)
> feat(bpdm): added connection to dependencies in readiness check for bpdm services

- CHANGELOG.md
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/TaskResolutionMapper.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/TaskStepBuildService.kt
- bpdm-system-tester/src/main/resources/cucumber/share_generic_business_partner.feature
Pool now correctly resolves tasks by providing business partner data based on the database state. This prevents returning inconsistent data.
Fixes #1158 
You can have a look at #1158 for seeing how to test this fix.
> fix(Pool): returning incomplete task results

- charts/bpdm/CHANGELOG.md
- charts/bpdm/Chart.yaml
- charts/bpdm/charts/bpdm-cleaning-service-dummy/CHANGELOG.md
- charts/bpdm/charts/bpdm-common/CHANGELOG.md
- charts/bpdm/charts/bpdm-common/Chart.yaml
- charts/bpdm/charts/bpdm-common/templates/_deployment.tpl
- charts/bpdm/charts/bpdm-gate/CHANGELOG.md
- charts/bpdm/charts/bpdm-gate/values.yaml
- charts/bpdm/charts/bpdm-orchestrator/CHANGELOG.md
- charts/bpdm/charts/bpdm-pool/CHANGELOG.md
- charts/bpdm/charts/bpdm-pool/values.yaml
This pull request adds missing security profile configuratioon to BPDM deployment containers
- adds seccomp profiles
- security context configuration now affects also initcontainers
Fixes #1152 
> fix(charts): add security profiles to BPDM deployment containers

- CHANGELOG.md
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/config/GoldenRecordProcessConfigProperties.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/config/GoldenRecordTaskConfiguration.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/repository/generic/BusinessPartnerRepository.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/GoldenRecordConsistencyService.kt
- bpdm-gate/src/main/resources/application.yml
This pull request introduces a consistency check to the Gate which checks whether referenced BPNs in the output stage are still existing in the Pool. If a discrepancy has been found it will be written as an error in the sharing state for the business partner record in question.
For testing I recommend the following:
1. setup the full golden record process
2. Share some business partners linking to different golden records
3. Set the concistency check to a fairly regular interval in the Gate's configureation
4. See in the logs whether the consistency checks works without issues
5. Go to the Pool database and rename some linked BPNs
6. After the next consistency check is done check the sharing states of affected business partner records
7. You should see the errors in the sharing states
I …
> feat(Gate): Consistency Check with the Pool 

- CHANGELOG.md
- bpdm-common-test/src/main/kotlin/org/eclipse/tractusx/bpdm/test/testdata/gate/BusinessPartnerNonVerboseValues.kt
- bpdm-common-test/src/main/kotlin/org/eclipse/tractusx/bpdm/test/testdata/gate/BusinessPartnerVerboseValues.kt
- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/IBaseBusinessPartnerGateDto.kt
- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/request/BusinessPartnerInputRequest.kt
- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/response/BusinessPartnerDto.kt
- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/response/BusinessPartnerOutputDto.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/generic/BusinessPartnerDb.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/BusinessPartnerMappings.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/BusinessPartnerService.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/util/BusinessPartnerCopyUtil.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/util/Extensions.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/util/PartnerFileUtil.kt
- bpdm-gate/src/main/resources/db/migration/V6_3_0_1__add_externalSequenceTimestamp_column.sql
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/auth/AuthTestBase.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/BusinessPartnerControllerIT.kt
- docs/api/gate.yaml
…quest
The BPDM gate requires functionality to handle data updates from the customer side based on timestamps. This feature ensures that the data is only updated if the new data from the customer has a more recent timestamp than the existing data.
https://github.com/eclipse-tractusx/sig-release/issues/726
- Customer sends data to the gate system with a timestamp attribute (currentness).
- The gate system receives the data and invokes the GR process.
- The GR process compares the received timestamp with the stored timestamp.
- If the received timestamp is newer, the data is updated, and a success message is logged and sent to the customer.
- If the received timestamp is not newer, the update is rejected, and an informative message is logged and sent to the customer.
Please ensure to do as …
> feat(bpdm-gate): Adding a externalSequenceTimestamp attribute to the business partner input request

- CHANGELOG.md
- bpdm-common-test/src/main/kotlin/org/eclipse/tractusx/bpdm/test/testdata/pool/ExpectedBusinessPartnerResultFactory.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/ResponseMappings.kt
- bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/controller/SiteControllerIT.kt
- bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/service/TaskResolutionServiceTest.kt
This pull request updates associated legal entity BPNL details for address of any type with attribute `bpnLegalEntity `. 
Fixes #1191
To test the functionality, I recommend the following way:
1.  Setup golden record process or have pool service running
2. Create legal entity with site and addresses (Legal address, Site main address and Additional Address)
3. Query address with generated bpna
4. You should see legal entity bpnl associated  for particular address in value of attribute  `bpnLegalEntity `.
I have also updated current unit tests in same pull request.
> fix(bpdm-pool): added missing legal entity (BPNL) associated to address in response while performing entity search

- .github/workflows/app-test-charts.yaml
Increase the default kubernetes version of the helm test workflow to 1.32.1
Contributes to quality checks #1203
> cicd(chart-test): increase the default kubernetes version to v1.32.1

- DEPENDENCIES
Updating the DEPENDENCIES file to the newest state. Formerly restricted cucumber dependencies are now approved.
Contributes to quality checks #1203
Contributes to #1202 
> docs(DEPENDENCIES): update with approved cucumber dependencies

- .github/workflows/deploy-docker.yaml
This pull request changes the docker container build workflows to create multi-platform containers for linux/amd64 and linux/arm64.
This contributes to the quality checks (TRG 4.08) in #1203
> cicd(Docker): build docker containers for multi-platform

- bpdm-system-tester/src/main/resources/cucumber/share_generic_business_partner.feature
This pull request fixes issue we were facing while performing E2E tests, as there was same business partner data being checked again and again during step execution which was resulting into unpredicted address type for golden records.
From now on, new business partner data will inserted every time while performing step execution.
> fix(bpdm-system-tester): update cumcumber feature file to generate new partner data

- CHANGELOG.md
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/TaskResolutionMapper.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/TaskStepBuildService.kt
This pull request fixes a bug for the Pool not returning the most up-to-date address information of a legal and site main address when the address has been modified by a sharing member's update to a site record.
Fixes #1209
> fix(Pool): returning the most-up-to-date legal and site main address

- .github/workflows/deploy-docker.yaml
- Buildx required for multi-platform docker image creation
- Added setup of buildx which was missing from the deployment workflow
> cicd(Workflows): fix deployment of multi-platform docker images

- DEPENDENCIES
- pom.xml
This pull request introduces a version overwrite for the json-smart dependency that is referenced by the spring boot framework. Since there is a reported vulnerability in json-smart and spring boot has not come up with a version update we now introduce a manual version overwrite in our bpdm parent pom.
#1220
> build(deps): overwrite json-smart dependency version

- DEPENDENCIES
- pom.xml
This pull request overwrites the netty-handler dependency version referenced by the spring boot framework in order to fix a  vulnerability. Since Spring boot has no newer reference available we manually bump the version of this dependency by overwrite in the pom. 
#1225
> build(deps): overwrite netty-handler version to fix vulnerability

- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/GoldenRecordUpdateServices.kt
This pull request fixes the golden record Pool update process breaking on business partner output data without legal names.
Fixes #1227
> fix(Gate): golden record Pool update process

- charts/bpdm/Chart.yaml
- charts/bpdm/charts/bpdm-cleaning-service-dummy/Chart.yaml
- charts/bpdm/charts/bpdm-common/Chart.yaml
- charts/bpdm/charts/bpdm-gate/Chart.yaml
- charts/bpdm/charts/bpdm-orchestrator/Chart.yaml
- charts/bpdm/charts/bpdm-pool/Chart.yaml
- pom.xml
This pull request releases the release candidate 2 for BPDM version 6.3.0 and BPDM Chart  5.3.0.
> build: BPDM 6.3.0-rc2 / BPDM Chart 5.3.0-rc2

- CHANGELOG.md
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/TaskStepBuildService.kt
- bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/service/TaskResolutionServiceTest.kt
This pull request introduces a validation check for incoming golden record tasks making sure that the Legal Entity, Site and Additional Address hierarchy is consistent in the contained business partner object. Since the Pool does not support changing the parent legal entity or site at the moment, it returns a validation error on encountering such golden record tasks. 
With this, it is up to the cleaning service to make sure that no such invalid business partner reaches the Pool. Otherwise the task will be returned to the sender with a sharing error.
Especially in regards to #1230 . This means, the Pool can also not return inconsistent data like that as it does not allow it to be processed.
Fixes #1230 
Please ensure to do as many of the following checks as possible, before asking for …
> fix(Pool): not checking the LSA parent hierarchy

- CHANGELOG.md
- bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/config/OpenApiConfig.kt
This pull request adds scopes to the clientCredential flow in the generated Open-API documents.
Fixes #1234
> fix: BPDM apps generating Open-API documents

- bpdm-gate/src/main/resources/application.yml
- bpdm-orchestrator/src/main/resources/application.yml
- bpdm-pool/src/main/resources/application.yml
This pull request enables pretty print of the OpenApi specification for BPDM services.
> refactor: BPDM apps now create Open-API documents in pretty JSON

- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/BusinessPartnerMappings.kt
This pull request adds missing value for `externalSequenceTimestamp` attribute in Gate input response. 
Fixes #1245 
> fix(bpdm-gate): added missing value for externalSequenceTimestamp attribute in response

- bpdm-common-test/src/main/kotlin/org/eclipse/tractusx/bpdm/test/testdata/pool/ExpectedBusinessPartnerResultFactory.kt
- bpdm-common-test/src/main/kotlin/org/eclipse/tractusx/bpdm/test/util/PoolAssertHelper.kt
This pull request fixes test assertion logic for how additional addresses of sites are compared.
Beforehand, on querying addresses the addresses' parent BPNL was not expected to be set if the address is an additional address of a site.
> test(Pool): fix how additional addresses of sites are compared

- CHANGELOG.md
- charts/bpdm/CHANGELOG.md
- charts/bpdm/Chart.yaml
- charts/bpdm/README.md
- charts/bpdm/charts/bpdm-cleaning-service-dummy/CHANGELOG.md
- charts/bpdm/charts/bpdm-cleaning-service-dummy/Chart.yaml
- charts/bpdm/charts/bpdm-cleaning-service-dummy/README.md
- charts/bpdm/charts/bpdm-common/CHANGELOG.md
- charts/bpdm/charts/bpdm-common/Chart.yaml
- charts/bpdm/charts/bpdm-gate/CHANGELOG.md
- charts/bpdm/charts/bpdm-gate/Chart.yaml
- charts/bpdm/charts/bpdm-gate/README.md
- charts/bpdm/charts/bpdm-orchestrator/CHANGELOG.md
- charts/bpdm/charts/bpdm-orchestrator/Chart.yaml
- charts/bpdm/charts/bpdm-orchestrator/README.md
- charts/bpdm/charts/bpdm-pool/CHANGELOG.md
- charts/bpdm/charts/bpdm-pool/Chart.yaml
- charts/bpdm/charts/bpdm-pool/README.md
- docs/api/gate.json
- docs/api/gate.yaml
- docs/api/orchestrator.json
- docs/api/orchestrator.yaml
- docs/api/pool.json
- docs/api/pool.yaml
- pom.xml
This pull request releases Catena-X 25.03 version  for BPDM App 6.3.0 and BPDM Chart 5.3.0.
Also updated below with new release version,
> build(release-25.03): BPDM 6.3.0 & BPDM Charts 5.3.0

- .github/workflows/app-test-trivy.yaml
This pull request limits the trivy check during the pull request to not report OS related vulnerabilities.
Since OS vulnerabilities come from the actual base image (we do not add any packages or other modifications to the OS) we are unable to fix any such vulnerabilties per TRG. Therefore, it is a good idea to remove the reporting of such vulnerabilties and rather limit it to JAVA vulnerabilties which we can in fact fix.
NOTE, for transparency we keep the the reporting of OS issues in the scheduled trivy check on main.
> cicd(Workflows): remove OS vulnerabilities from trivy pull request check

- pom.xml
Remove the license-check plugin from any maven phase.
This way the license-check is only executed when explicitly started by the goal and not during the maven lifecycle.
This solves the problem of the license-check interrupting the build process due to a too-many-requests error.
> cicd: remove the license-check plugin from any maven phase

- CHANGELOG.md
- bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/model/BaseEntity.kt
- bpdm-gate-api/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/api/model/RelationType.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/RelationDb.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/RelationConstraintProvider.kt
- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/service/RelationService.kt
- bpdm-gate/src/main/resources/db/migration/V7_0_0_0__fix_relation_unique_constraint.sql
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/auth/AuthAdminIT.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/auth/AuthInputConsumerIT.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/auth/AuthInputManagerIT.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/auth/AuthOutputConsumerIT.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/auth/NoAuthIT.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/RelationControllerIT.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/RelationIsManagedByIT.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/util/MockAndAssertUtils.kt
- bpdm-gate/src/test/resources/application-test-no-auth.yml
- bpdm-gate/src/test/resources/application-test.yml
- docs/api/gate.json
- docs/api/gate.yaml
This pull request adds the 'IsAlternativeHeadquarterFor' relation type to the input business partner relation endpoints.
Contibutes to #1286 
> feat(Gate): add 'IsAlternativeHeadquarterFor' relation

- CHANGELOG.md
- bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/model/BusinessPartnerRelations.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/repository/RelationRepository.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/TaskRelationsBatchResolutionService.kt
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/TaskRelationsStepBuildService.kt
- bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/service/TaskRelationsResolutionServiceTest.kt
This pull request adds functionality for bpdm-pool service to consume relation data from created relation golden record tasks.
- Created logic to reserve relation golden record tasks and consume the relation information
- Relation can retrieve from Legal Entity envolved.
Contributes to #1279 
> feat(bpdm-pool): added functionality to consume relation golden record tasks

- .github/workflows/trivy.yml
The regular trivy workflow check on main currently breaks when finding a vulnerabilty. This indicates that something is wrong with the workflow or some critical part of the cicd is not working correctly. This however, not the case as trivy just reports some found vulnerabilties. 
I propose we change the exit code for this trivy check to 0 making sure that the github workflow does not break but still reports any found vulnerabilities in the security section of github. 
The behaviour of the trivy check during the pull request which breaks on finding a vulnerabilty remains unchanged.
> cicd(Workflows): change trivy exit code

- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/TaskRelationsStepBuildService.kt
This pull request fixes the Pool's behaviour of resolving business partner relations golden record tasks. Now, when a new relation has been added (or updated) the participating legal entities (source and target) will each get a changelog UPDATE entry.
Fixes #1300 
> fix(pool): add changelog entries when updating business partner relations

- CHANGELOG.md
- bpdm-cleaning-service-dummy/src/test/kotlin/org/eclipse/tractusx/bpdm/cleaning/service/CleaningServiceApiCallsTest.kt
- bpdm-common/src/main/kotlin/org/eclipse/tractusx/bpdm/common/config/OpenApiConfig.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/service/GoldenRecordUpdateServiceIT.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/service/RelationTaskCreationServiceIT.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/service/RelationTaskResolutionServiceIT.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/util/MockAndAssertUtils.kt
- bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/ApiCommons.kt
- bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/FinishedTaskEventApi.kt
- bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/GoldenRecordTaskApi.kt
- bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/RelationsFinishedTaskEventApi.kt
- bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/RelationsGoldenRecordTaskApi.kt
- bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/client/FinishedTaskEventApiClient.kt
- bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/client/GoldenRecordTaskApiClient.kt
- bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/client/RelationsFinishedTaskEventApiClient.kt
- bpdm-orchestrator-api/src/main/kotlin/org/eclipse/tractusx/orchestrator/api/client/RelationsGoldenRecordTaskApiClient.kt
- docs/api/orchestrator.json
- docs/api/orchestrator.yaml
This pull request adds new api version for BPDM Orchestrator service. 
The new api version is now v7 along with simultanous support for previous version v6. 
Currently, bpdm-orchestraor service will support for both versioned apis but for round trip test we have enabled only v7.
Contributes to #1294 
> feat(bpdm-orchestrator): api version increased with simultaneous v6 support

- CHANGELOG.md
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/controller/PartnerUploadControllerIT.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/service/GoldenRecordUpdateServiceIT.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/util/MockAndAssertUtils.kt
- bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/ApiCommons.kt
- bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/PoolAddressApi.kt
- bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/PoolBpnApi.kt
- bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/PoolChangelogApi.kt
- bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/PoolCxMembershipApi.kt
- bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/PoolLegalEntityApi.kt
- bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/PoolMembersApi.kt
- bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/PoolMetadataApi.kt
- bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/PoolSiteApi.kt
- bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/client/AddressApiClient.kt
- bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/client/BpnApiClient.kt
- bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/client/ChangeLogApiClient.kt
- bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/client/CxMembershipApiClient.kt
- bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/client/LegalEntityApiClient.kt
- bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/client/MembersApiClient.kt
- bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/client/MetadataApiClient.kt
- bpdm-pool-api/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/api/client/SiteApiClient.kt
- bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/util/EndpointValues.kt
- docs/api/pool.json
- docs/api/pool.yaml
This pull request adds new api version for BPDM Pool service.
The new api version is now v7 along with simultanous support for previous version v6.
Currently, bpdm-pool service will support for both versioned apis but for round trip test we have enabled only v7.
Contributes to https://github.com/eclipse-tractusx/bpdm/issues/1294
> feat(bpdm-pool): api version increased with simultaneous v6 support

- docs/postman/EDC Provider Setup.postman_collection.json
This pull request adds documentation changes for postman collection of EDC consumer and provider as per the standard 25.06.
Contributes to #1304
> docs: renaming attributes and edc assets as per the standards 25.06

- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/ResponseMappings.kt
This pull request fixes the identifier types, making it that every identifier type has at least the category 'OTH' according to https://github.com/eclipse-tractusx/bpdm/issues/1297#issuecomment-2820315829 .
Contributes to #1297
> fix(Pool): all identifier types now have at least the default category 'OTH

- bpdm-migration-helper/README.md
- bpdm-migration-helper/pom.xml
- bpdm-migration-helper/src/main/kotlin/org/eclipse/tractusx/bpdm/migration/helper/Application.kt
- bpdm-migration-helper/src/main/kotlin/org/eclipse/tractusx/bpdm/migration/helper/identifier/type/BusinessPartnerType.kt
- bpdm-migration-helper/src/main/kotlin/org/eclipse/tractusx/bpdm/migration/helper/identifier/type/IdentifierTypeCategory.kt
- bpdm-migration-helper/src/main/kotlin/org/eclipse/tractusx/bpdm/migration/helper/identifier/type/ImportEntryValidator.kt
- bpdm-migration-helper/src/main/kotlin/org/eclipse/tractusx/bpdm/migration/helper/identifier/type/MigrationFileCreator.kt
- bpdm-migration-helper/src/main/kotlin/org/eclipse/tractusx/bpdm/migration/helper/identifier/type/SqlMapper.kt
- bpdm-migration-helper/src/main/kotlin/org/eclipse/tractusx/bpdm/migration/helper/identifier/type/UnvalidatedImportEntry.kt
- bpdm-migration-helper/src/main/kotlin/org/eclipse/tractusx/bpdm/migration/helper/identifier/type/ValidatedImportEntry.kt
- bpdm-migration-helper/src/main/kotlin/org/eclipse/tractusx/bpdm/migration/helper/util/NoArg.kt
- bpdm-migration-helper/src/main/resources/identifier_types/identifier-types.csv
- pom.xml
This pull request creates the new 'Migration Helper' module. This is a tool which helps creating migration scripts from non-SQL source files like CSVs. The intended users for this tool are operators and developers. Instead of being a full fledged productive solution this tool just offers utility functionality for any person who would like to create such migration files for BPDM.
Currently, the tool only supports the process of creating identifier types migration script from a given CSV resource file.
> chore: create Migration Helper tool

- DEPENDENCIES
- pom.xml
This pull request overrides the PostgreSQL depency version coming with the Spring Boot starter to fix vulnerabilities that are present in the default version.
Fixes security issues.
> build(deps): upgrade postgres version to fix vulnerabilties

- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/ManagedRelationUpsertService.kt
- bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/service/TaskRelationsResolutionServiceTest.kt
This pull request supports the broader feature for handling `IsManagedBy` relations in the Pool. 
It ensures validation failures are actionable and traceable by providing clean and precise error messages.
- A Managing Legal Entity cannot also be a Managed Legal Entity
- A Managed Legal Entity cannot have multiple managers
No changes to business logic, only exception message content and structure refined.
Contributes to #1364 
> feat(Pool): Refine 'IsManagedBy' validation error messages for role-specific clarity

- .github/workflows/sonar.yml
- CHANGELOG.md
- pom.xml
This pull request adds proposal for having code coverage using JaCoCo during the build process for BPDM application.
Also, coverage reports and code quality metrics will be analyzed and visualized through SonarQube. Currently the BPDM  does not have an integration in this SonarQube instance which is need to fix first. 
Contributes to #1338
> chore(app): added code coverage check using JaCoCo

- .github/workflows/app-test-charts.yaml
- CHANGELOG.md
- bpdm-cleaning-service-dummy/src/main/kotlin/org/eclipse/tractusx/bpdm/cleaning/config/CleaningServiceConfigProperties.kt
- bpdm-cleaning-service-dummy/src/main/kotlin/org/eclipse/tractusx/bpdm/cleaning/config/RelationCleaningTaskConfiguration.kt
- bpdm-cleaning-service-dummy/src/main/kotlin/org/eclipse/tractusx/bpdm/cleaning/service/RelationCleaningServiceDummy.kt
- bpdm-cleaning-service-dummy/src/main/resources/application-system-tester.yml
- bpdm-cleaning-service-dummy/src/main/resources/application.yml
- bpdm-cleaning-service-dummy/src/test/kotlin/org/eclipse/tractusx/bpdm/cleaning/service/RelationCleaningServiceApiCallsTest.kt
- bpdm-system-tester/README.md
This PR introduces support for relation cleaning task configuration and execution within the cleaning service dummy. 
The changes include:
Contributes to #1383
> feat(bpdm-cleaning): add configuration and scheduling support for relation cleaning tasks with test coverage

- bpdm-coverage-aggregate/pom.xml
- pom.xml
This pull request fixes the code coverage configuration for sonarqube by creating a new maven module responsible for aggregating all code coverage reports.
> cicd(sonar): add jacoco code coverage aggregate module

- charts/bpdm/CHANGELOG.md
- charts/bpdm/Chart.yaml
- charts/bpdm/charts/bpdm-cleaning-service-dummy/Chart.yaml
- charts/bpdm/charts/bpdm-common/Chart.yaml
- charts/bpdm/charts/bpdm-common/templates/_deployment.tpl
- charts/bpdm/charts/bpdm-gate/Chart.yaml
- charts/bpdm/charts/bpdm-orchestrator/Chart.yaml
- charts/bpdm/charts/bpdm-pool/Chart.yaml
This pull request fixes a security vulnerability on the BPDM Helm Charts by making mounting volumes in deployments as read-only.
> fix(charts): make config volume mounts for deployments read-only

- CHANGELOG.md
- bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/service/ManagedRelationUpsertService.kt
- bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/service/TaskRelationsResolutionServiceTest.kt
This pull request enhances the validation for IsManagedBy relation by condition that managing entity must be dataspace participant. Also, when relation validates successfully then made managed legal entity as dataspace participant as well.
Contributes to #1390  
> feat(bpdm-pool): enforce dataspace participant validation for managing entity in IsManagedBy relation

- bpdm-common-test/src/main/kotlin/org/eclipse/tractusx/bpdm/test/containers/KeycloakContextInitializer.kt
- bpdm-gate/src/test/kotlin/org/eclipse/tractusx/bpdm/gate/auth/AuthenticatedIT.kt
- bpdm-orchestrator/src/test/kotlin/org/eclipse/tractusx/bpdm/orchestrator/auth/AuthenticatedIT.kt
- bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/auth/AuthenticatedIT.kt
This pull request adds tests for accessing endpoints by an authenticated user who has no BPDM permissions. The expectation here is that all endpoints should return a 403 Forbidden response.
Implements #1415 
> Test: Add Authenticated User Tests

- bpdm-cleaning-service-dummy/src/test/resources/application-test.yml
This pull request disables the relation cleaning scheduling during the integration tests of the cleaning service dummy. Therefore, we fix a race condition leading the tests to fail sometimes.
> test(cleaning-dummy): fix race condition

- charts/bpdm/CHANGELOG.md
- charts/bpdm/Chart.yaml
- charts/bpdm/README.md
- charts/bpdm/charts/bpdm-cleaning-service-dummy/README.md
- charts/bpdm/charts/bpdm-gate/README.md
- charts/bpdm/charts/bpdm-orchestrator/README.md
- charts/bpdm/charts/bpdm-pool/README.md
- charts/bpdm/values.yaml
Workaround to keep the latest chart running for R25.09.
Bitnami changed their container image availability to provide versioned and security hardened images only for subscribed companies.
We follow this immediate recommendation and:
- switch image to bitnamilegacy images
Contributes to #1455
> fix(charts/bpdm): replace bitnami repository by bitnamilegacy

- bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/controller/v6/SharingStateController.kt
This pull request fixes a bug in which accesses to the V6 GET sharing-states endpoint of the Gate API are always rejected. The change adds the appropriate 'read sharing states' permission  to the endpoint.
Fixes #1470 
> fix(Gate): V6 GET sharing states endpoint not having authorization constraints

- charts/bpdm/Chart.yaml
- charts/bpdm/README.md
- charts/bpdm/charts/bpdm-cleaning-service-dummy/Chart.yaml
- charts/bpdm/charts/bpdm-cleaning-service-dummy/README.md
- charts/bpdm/charts/bpdm-gate/Chart.yaml
- charts/bpdm/charts/bpdm-gate/README.md
- charts/bpdm/charts/bpdm-orchestrator/Chart.yaml
- charts/bpdm/charts/bpdm-orchestrator/README.md
- charts/bpdm/charts/bpdm-pool/Chart.yaml
- charts/bpdm/charts/bpdm-pool/README.md
- docs/api/gate.json
- docs/api/gate.yaml
- docs/api/orchestrator.json
- docs/api/orchestrator.yaml
- docs/api/pool.json
- docs/api/pool.yaml
- pom.xml
This pull request releases the release candidate 5 for BPDM App version 7.1.0 and BPDM Chart 6.1.0.
Also updated below with new release candidate version,
- Upgraded Centralidp chart version for dependency chart
> build(release-candidate): BPDM 7.1.0-rc5 & BPDM Charts 6.1.0-rc5

- DEPENDENCIES
- bpdm-system-tester/pom.xml
This pull request downgrades the cucumber version to 7.28.1 to have restricted free dependencies in BPDM project.
> docs: updated maven cucumber version 7.28.1

- CHANGELOG.md
- charts/bpdm/CHANGELOG.md
- charts/bpdm/Chart.yaml
- charts/bpdm/README.md
- charts/bpdm/charts/bpdm-cleaning-service-dummy/Chart.yaml
- charts/bpdm/charts/bpdm-cleaning-service-dummy/README.md
- charts/bpdm/charts/bpdm-gate/Chart.yaml
- charts/bpdm/charts/bpdm-gate/README.md
- charts/bpdm/charts/bpdm-orchestrator/Chart.yaml
- charts/bpdm/charts/bpdm-orchestrator/README.md
- charts/bpdm/charts/bpdm-pool/Chart.yaml
- charts/bpdm/charts/bpdm-pool/README.md
- docs/api/gate.json
- docs/api/gate.yaml
- docs/api/orchestrator.json
- docs/api/orchestrator.yaml
- docs/api/pool.json
- docs/api/pool.yaml
- pom.xml
This pull request creates snapshot version for release package 25.12 on BPDM side.
Creates BPDM application version - 7.2.0-SNAPSHOT and BPDM chart version - 6.2.0-SNAPSHOT.
> build(version): 7.2.0-SNAPSHOT BPDM / 6.2.0-SNAPSHOT BPDM Chart
